import { claimId } from "./claims";
export const applicationStatuses=["CONSIDERING","PREPARING","READY_TO_APPLY","APPLIED","INTERVIEW_1","INTERVIEW_2","CASE","OFFER","REJECTED","WITHDRAWN"] as const;
export type ApplicationStatus=typeof applicationStatuses[number];
export type ApplicationContent={status:ApplicationStatus;cvVersionId:string|null;appliedOn:string|null;nextFollowUpOn:string|null;contactName:string;contactEmail:string;contactPhone:string;notes:string;applicationText:string};
export type ApplicationCase={id:string;jobId:string;jobTitle:string;content:ApplicationContent;revision:number;createdAt:string;updatedAt:string;history:{status:ApplicationStatus;recordedAt:string;cvVersionId:string|null;appliedOn:string|null}[]};
export const applicationLabels={nb:{CONSIDERING:"Vurderer",PREPARING:"Forbereder",READY_TO_APPLY:"Klar til å søke",APPLIED:"Sendt",INTERVIEW_1:"Første intervju",INTERVIEW_2:"Andre intervju",CASE:"Case / oppgave",OFFER:"Tilbud",REJECTED:"Avslag",WITHDRAWN:"Trukket"},en:{CONSIDERING:"Considering",PREPARING:"Preparing",READY_TO_APPLY:"Ready to apply",APPLIED:"Applied",INTERVIEW_1:"First interview",INTERVIEW_2:"Second interview",CASE:"Case / assignment",OFFER:"Offer",REJECTED:"Rejected",WITHDRAWN:"Withdrawn"}};
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const nullableId=(v:unknown)=>v===null||typeof v==="string"&&claimId.test(v);
const date=(v:unknown)=>v===null||typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
export function isApplicationContent(v:unknown):v is ApplicationContent{return record(v)&&applicationStatuses.includes(v.status as ApplicationStatus)&&nullableId(v.cvVersionId)&&date(v.appliedOn)&&date(v.nextFollowUpOn)&&Object.entries({contactName:200,contactEmail:200,contactPhone:100,notes:5000,applicationText:5000}).every(([key,max])=>typeof v[key]==="string"&&v[key].length<=max);}
export function isApplication(v:unknown):v is ApplicationCase {return record(v)&&typeof v.id==="string"&&claimId.test(v.id)&&typeof v.jobId==="string"&&claimId.test(v.jobId)&&typeof v.jobTitle==="string"&&v.jobTitle.length<=200&&isApplicationContent(v.content)&&Number.isSafeInteger(v.revision)&&Number(v.revision)>0&&[v.createdAt,v.updatedAt].every(x=>typeof x==="string"&&Number.isFinite(Date.parse(x)))&&Array.isArray(v.history)&&v.history.length>0&&v.history.length<=100&&v.history.every(h=>record(h)&&applicationStatuses.includes(h.status as ApplicationStatus)&&nullableId(h.cvVersionId)&&date(h.appliedOn)&&typeof h.recordedAt==="string"&&Number.isFinite(Date.parse(h.recordedAt)));}
export const isApplications=(v:unknown):v is ApplicationCase[]=>Array.isArray(v)&&v.length<=100&&v.every(isApplication);
export function applicationError(code:string,locale:"nb"|"en"){const nb=locale==="nb";const labels:Record<string,string>={APPLICATION_CONFLICT:nb?"Saken er endret. Lukk og hent den på nytt; utkastet er ikke lagret.":"The case changed. Close and reload it; your draft was not saved.",APPLICATION_MATERIALS_REQUIRED:nb?"Velg en godkjent CV og datoen du faktisk sendte søknaden.":"Choose an approved CV and the date you actually submitted the application.",APPLICATION_MATERIALS_LOCKED:nb?"Registrerte innsendingsmaterialer er låst for å bevare hva du sendte.":"Recorded submission materials are locked to preserve what you sent.",APPLICATION_SOURCE_CONFLICT:nb?"Stillingen eller CV-versjonen er utilgjengelig. Velg en godkjent CV for denne stillingen eller en generell CV.":"The job or CV is unavailable. Choose an approved CV for this job or a general CV.",APPLICATION_INVALID:nb?"Kontroller feltene og datoene. Innsendingsdato kan ikke ligge frem i tid.":"Check fields and dates. Submission date cannot be in the future.",PROFILE_NOT_CREATED:nb?"Opprett kandidatprofilen først.":"Create your candidate profile first.",AUTH_REQUIRED:nb?"Logg inn igjen.":"Sign in again."};return labels[code]??(nb?"Saken kunne ikke oppdateres. Det lagrede innholdet er beholdt; prøv igjen.":"Could not update the case. Saved content is retained; try again.");}
