import { claimId, isClaim, type CompetencyClaim } from "./claims";
import { isEntry, type CareerEntry } from "./career-entries";
export type CvIdentity = {name:string;headline:string;email:string;phone:string;location:string;summary:string};
export type CvDraft = {title:string;locale:"nb"|"en";identity:CvIdentity;claims:{id:string;revision:number}[];entries:{id:string;revision:number}[];jobId:string|null};
export type CvVersion = {id:string;title:string;status:"DRAFT"|"APPROVED";revision:number;templateVersion:string;createdAt:string;approvedAt:string|null;stale:boolean;artifacts:{id:string;format:"PDF"|"DOCX";byteSize:number;sha256:string}[];content:{locale:"nb"|"en";identity:CvIdentity;claims:CompetencyClaim[];entries:CareerEntry[];jobId:string|null;jobTitle:string|null}};
const record = (v:unknown):v is Record<string,unknown> => !!v && typeof v === "object" && !Array.isArray(v);
export const emptyIdentity:CvIdentity={name:"",headline:"",email:"",phone:"",location:"",summary:""};
export function isCvIdentity(v:unknown):v is CvIdentity {return record(v) && Object.entries({name:200,headline:200,email:200,phone:100,location:200,summary:1500}).every(([key,max])=>typeof v[key] === "string" && v[key].length<=max) && String(v.name).trim().length>0;}
export function isCv(v:unknown):v is CvVersion {
 if(!record(v) || typeof v.id !== "string" || !claimId.test(v.id) || typeof v.title !== "string" || !v.title.trim() || v.title.length>200 || !["DRAFT","APPROVED"].includes(String(v.status)) || !Number.isSafeInteger(v.revision) || Number(v.revision)<1 || v.templateVersion !== "standard-v1" || typeof v.stale !== "boolean" || typeof v.createdAt !== "string" || !Number.isFinite(Date.parse(v.createdAt)) || v.approvedAt !== null && (typeof v.approvedAt !== "string" || !Number.isFinite(Date.parse(v.approvedAt))) || !record(v.content))return false;
 const c=v.content;
 if(!["nb","en"].includes(String(c.locale)) || !isCvIdentity(c.identity) || !Array.isArray(c.claims) || c.claims.length>30 || !c.claims.every(x=>isClaim(x)&&x.status==="CONFIRMED") || !Array.isArray(c.entries) || c.entries.length>20 || !c.entries.every(x=>isEntry(x)&&x.status==="CONFIRMED") || c.jobId !== null && (typeof c.jobId !== "string" || !claimId.test(c.jobId)) || c.jobTitle !== null && typeof c.jobTitle !== "string")return false;
 return Array.isArray(v.artifacts) && v.artifacts.length === (v.status === "APPROVED" ? 2:0) && v.artifacts.every(a=>record(a)&&typeof a.id==="string"&&claimId.test(a.id)&&["PDF","DOCX"].includes(String(a.format))&&Number.isSafeInteger(a.byteSize)&&Number(a.byteSize)>0&&Number(a.byteSize)<=5000000&&typeof a.sha256==="string"&&/^[a-f0-9]{64}$/.test(a.sha256));
}
export const isCvs = (v:unknown):v is CvVersion[]=>Array.isArray(v)&&v.length<=30&&v.every(isCv);
export function cvError(code:string,locale:"nb"|"en"){const nb=locale==="nb";const labels:Record<string,string>={CV_SOURCE_CONFLICT:nb?"Erfaringen er endret. Lag et nytt utkast fra den oppdaterte profilen.":"Experience has changed. Create a new draft from your updated profile.",CV_CONFLICT:nb?"Versjonen er endret. Hent den på nytt.":"Version changed. Reload it.",CV_CHARACTER_UNSUPPORTED:nb?"PDF-malen støtter ikke alle tegn i utkastet. Fjern spesialtegn som emoji og lag et nytt utkast.":"The PDF template does not support all draft characters. Remove special characters such as emoji and create a new draft.",CV_IN_USE:nb?"Denne CV-en er knyttet til en søknad. Fjern tilknytningen før sletting.":"This CV is linked to an application. Remove that link before deletion.",CV_LIMIT:nb?"Piloten støtter 30 CV-versjoner.":"The pilot supports 30 CV versions.",CV_CONTENT_LIMIT:nb?"Velg færre kompetansepunkter eller kortere beskrivelser.":"Select fewer competencies or shorter descriptions.",CV_BUSY:nb?"En CV blir allerede laget. Vent litt og prøv igjen.":"A CV is already being generated. Wait and try again.",CV_INVALID:nb?"Kontroller navn, felter og valgt erfaring.":"Check your name, fields and selected experience.",PROFILE_NOT_CREATED:nb?"Opprett profilen din først.":"Create your profile first.",AUTH_REQUIRED:nb?"Logg inn igjen.":"Sign in again."};return labels[code]??(nb?"Utkast og originaldokumenter er beholdt. Prøv igjen når eksporten er tilgjengelig.":"Your draft and original documents are retained. Try again when export is available.");}
