import { MAX_JOB_REQUIREMENTS } from "./job-requirements";
import { claimId } from "./claims";
export type MatchClaim = { id: string; revision: number; skill: string; statement: string; context: string };
export type MatchEvidence = { claimId: string; quote: string };
export type MatchAssessment = { requirementIndex: number; classification: "STRONG" | "PARTIAL" | "CLARIFY"; reason: string; evidence: MatchEvidence[]; question: string; evaluated?: boolean; evidenceRelation?: "DIRECT"|"TRANSFERABLE"|"UNKNOWN"|null; requirementNature?: "FORMAL"|"PRACTICAL"|"OTHER"|null };
export type PersonalMatch = { id: string; locale: "nb" | "en"; createdAt: string; assessments: MatchAssessment[]; claims: MatchClaim[]; omittedItems: number; inputCharacters: number; stale: boolean; provider?:"Groq"|"Gemini"; model?:string|null; automaticEvidence?:boolean };
export function isPersonalMatch(value: unknown): value is PersonalMatch {
 if (!value || typeof value !== "object") return false;
 const v = value as PersonalMatch;
 const str = (x: unknown, max: number, empty = false): x is string => typeof x === "string" && x.length <= max && (empty || !!x.trim());
 return (v.automaticEvidence===undefined || typeof v.automaticEvidence==="boolean") && (v.provider===undefined || ["Groq","Gemini"].includes(v.provider)) && (v.model===undefined || v.model===null || str(v.model,100)) && typeof v.id === "string" && claimId.test(v.id) && ["nb", "en"].includes(v.locale) && str(v.createdAt, 40) && Number.isFinite(Date.parse(v.createdAt)) && typeof v.stale === "boolean" && Number.isSafeInteger(v.omittedItems) && v.omittedItems >= 0 && v.omittedItems <= 2048 && Number.isSafeInteger(v.inputCharacters) && v.inputCharacters <= 825000 && v.inputCharacters >= 40 && Array.isArray(v.claims) && v.claims.length <= 500 && v.claims.every(c => !!c && typeof c.id === "string" && claimId.test(c.id) && Number.isSafeInteger(c.revision) && c.revision >= 1 && str(c.skill,120) && str(c.statement,1000) && str(c.context,500)) && Array.isArray(v.assessments) && v.assessments.length <= MAX_JOB_REQUIREMENTS && new Set(v.assessments.map(a=>a?.requirementIndex)).size === v.assessments.length && v.assessments.every(a => !!a && (a.evaluated === undefined || typeof a.evaluated === "boolean") && (a.evidenceRelation==null || ["DIRECT","TRANSFERABLE","UNKNOWN"].includes(a.evidenceRelation)) && (a.requirementNature==null || ["FORMAL","PRACTICAL","OTHER"].includes(a.requirementNature)) && (a.evidenceRelation!=="UNKNOWN" || a.classification==="CLARIFY") && (a.evidenceRelation!=="TRANSFERABLE" || (a.classification!=="STRONG" && (a.requirementNature!=="FORMAL" || a.classification==="CLARIFY"))) && (a.evaluated !== false || a.classification === "CLARIFY" && a.evidence?.length === 0 && a.question === "") && Number.isInteger(a.requirementIndex) && a.requirementIndex >= 0 && a.requirementIndex < MAX_JOB_REQUIREMENTS && ["STRONG", "PARTIAL", "CLARIFY"].includes(a.classification) && str(a.reason,600) && str(a.question,300,true) && Array.isArray(a.evidence) && a.evidence.length <= 5 && a.evidence.every(e => !!e && typeof e.claimId === "string" && v.claims.some(c => c.id === e.claimId) && str(e.quote,500)));
}
export function matchError(code: string, locale: "nb" | "en") {
 const nb = locale === "nb";
 const errors: Record<string,string> = { MATCH_CONSENT_REQUIRED: nb ? "Godkjenn forhåndsvisningen før analysen." : "Approve the preview before analysis.", MATCH_INPUT_INVALID: nb ? "Profilgrunnlaget kunne ikke leses. Hent profilen på nytt og prøv igjen." : "Could not read the profile evidence. Refresh the profile and try again.", MATCH_NO_REQUIREMENTS: nb ? "Denne annonsen mangler sorterte krav i utvalgt tekst. Analyser annonseteksten først." : "There are no structured requirements in the selected text. Analyze the advertisement first.", MATCH_CONFLICT: nb ? "Kompetansen er endret. Lukk stillingen og hent profilen på nytt før analyse." : "Evidence changed. Close the job and reload your profile before analyzing.", AI_RATE_LIMITED: nb ? "AI-kvoten er nådd. Vent til nedtellingen er ferdig." : "AI quota reached. Wait for the countdown.", AI_BUDGET_REACHED: nb ? "Pilotens analysebudsjett er brukt for denne backend-økten." : "The pilot analysis budget is exhausted for this backend process.", AI_INVALID_RESULT: nb ? "AI-svaret kunne ikke kontrolleres. Forrige vurdering er beholdt." : "AI output could not be validated. Your previous assessment is retained.", AI_NOT_CONFIGURED: nb ? "AI er ikke konfigurert på backend." : "AI is not configured on the backend.", AUTH_REQUIRED: nb ? "Sesjonen er utløpt. Logg inn igjen." : "Your session expired. Sign in again." };
 return errors[code] ?? (nb ? "Matchingen er utilgjengelig. Prøv igjen." : "Matching is unavailable. Try again.");
}
