"use client";
import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { Plus,ArrowRight,CalendarDays,Send,Trash2,ClipboardList } from "lucide-react";
import { Button } from "./ui/button";
import { Card,CardContent } from "./ui/card";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Badge } from "./ui/badge";
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from "./ui/sheet";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from "./ui/dialog";
import { useWorkspaceSession } from "../lib/workspace-session";
import { isCvs } from "../lib/cvs";
import { isSavedJobs } from "../lib/saved-jobs";
import { isApplication,isApplications,applicationStatuses,applicationLabels,applicationError,type ApplicationCase,type ApplicationContent,type ApplicationStatus } from "../lib/applications";
import type { Locale } from "../lib/translations";
async function load<T>(url:string,validate:(v:unknown)=>v is T):Promise<T>{const r=await fetch(url,{cache:"no-store"});const v=await r.json();if(!r.ok)throw new Error(v.code??"APPLICATION_UNAVAILABLE");if(!validate(v))throw new Error("APPLICATION_UNAVAILABLE");return v;}
export function ApplicationWorkspace({locale}:{locale:Locale}) {
 const nb=locale==="nb";const labels=applicationLabels[locale];const cache=useQueryClient();const session=useWorkspaceSession();const [selected,setSelected]=useState<ApplicationCase|null>(null);const [draft,setDraft]=useState<ApplicationContent|null>(null);const [creating,setCreating]=useState(false);const [jobId,setJobId]=useState("");const [filter,setFilter]=useState("ALL");const [search,setSearch]=useState("");const [submissionReview,setSubmissionReview]=useState(false);const [deleting,setDeleting]=useState(false);
 const cases=useQuery({queryKey:["private-applications"],gcTime:0,retry:false,queryFn:()=>load("/api/profile/me/applications",isApplications)});
 const jobs=useQuery({queryKey:["private-saved-jobs"],gcTime:0,retry:false,queryFn:()=>load("/api/profile/me/jobs",isSavedJobs)});
 const cvs=useQuery({queryKey:["private-cvs"],gcTime:0,retry:false,queryFn:()=>load("/api/profile/me/cvs",isCvs)});
 async function request(path:string,method:string,value:unknown){const r=await fetch(path,{method,headers:{"Content-Type":"application/json","X-CSRF-TOKEN":session.data?.csrfToken??""},body:JSON.stringify(value)});if(r.status===204)return null;const v=await r.json();if(!r.ok)throw new Error(v.code??"APPLICATION_UNAVAILABLE");if(!isApplication(v))throw new Error("APPLICATION_UNAVAILABLE");return v;}
 function open(value:ApplicationCase){setSelected(value);setDraft({...value.content});save.reset();setSubmissionReview(false);}
 function updated(value:ApplicationCase){cache.setQueryData<ApplicationCase[]>(["private-applications"],old=>[value,...(old??[]).filter(x=>x.id!==value.id)]);void cache.invalidateQueries({queryKey:["private-applications"]});open(value);}
 const create=useMutation({retry:false,mutationFn:()=>request("/api/profile/me/applications","POST",{jobId}),onSuccess:value=>{if(value){setCreating(false);updated(value);}}});
 const save=useMutation({retry:false,mutationFn:async()=>{if(!selected||!draft)throw new Error("APPLICATION_INVALID");return request(`/api/profile/me/applications/${selected.id}`,"PUT",{revision:selected.revision,content:draft});},onSuccess:value=>{if(value)updated(value);}});
 const remove=useMutation({retry:false,mutationFn:()=>request(`/api/profile/me/applications/${selected!.id}`,"DELETE",{revision:selected!.revision}),onSuccess:()=>{setSelected(null);setDraft(null);setDeleting(false);void cases.refetch();}});
 const date=new Date();const today=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
 const due=(value:ApplicationCase)=>!!value.content.nextFollowUpOn&&value.content.nextFollowUpOn<=today&&!["REJECTED","WITHDRAWN","OFFER"].includes(value.content.status);
 const applicationCases=cases.data??[];
 const filtered=applicationCases.filter(value=>(filter==="ALL"||filter==="DUE"&&due(value)||value.content.status===filter)&&`${value.jobTitle} ${value.content.contactName} ${value.content.notes}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const submittedCount=applicationCases.filter(value=>!!value.content.appliedOn).length;
 const dueCount=applicationCases.filter(due).length;
 const hasCases=applicationCases.length>0;
 const allowedCvs=cvs.data?.filter(v=>v.status==="APPROVED"&&(!v.content.jobId||v.content.jobId===selected?.jobId))??[];const attached=allowedCvs.find(v=>v.id===draft?.cvVersionId);const locked=!!selected?.content.appliedOn;
 const error=cases.error??jobs.error??cvs.error;
 const set=(key:keyof ApplicationContent,value:ApplicationContent[keyof ApplicationContent])=>setDraft(draft?{...draft,[key]:value}:null);
 return <section className="application-workspace" aria-label={nb?"Søknadsoppfølging":"Application tracking"}><div className="workspace-heading"><div><h2>{nb?"Søknadssaker":"Application cases"}</h2><p className="hint">{nb?"Følg status, bevart materiale og neste oppfølging. Innsending registrerer du selv.":"Track status, preserved materials and the next follow-up. You record submissions yourself."}</p></div><Button disabled={jobs.isPending||jobs.isError||cases.isError} onClick={()=>{create.reset();setJobId("");setCreating(true);}}><Plus size={16}/>{nb?"Opprett søknadssak":"Create application case"}</Button></div>
 {cases.isPending&&<p role="status">{nb?"Henter saker …":"Loading cases …"}</p>}{error&&<p role="alert" className="notice">{applicationError(error.message,locale)}<Button variant="outline" onClick={()=>{void cases.refetch();void jobs.refetch();void cvs.refetch();}}>{nb?"Hent på nytt":"Reload"}</Button></p>}
 {hasCases&&<><div className="application-summary" aria-label={nb?"Søknadsoversikt":"Application overview"}><div><span>{nb?"Saker":"Cases"}</span><strong>{applicationCases.length}</strong></div><div><span>{nb?"Sendt":"Submitted"}</span><strong>{submittedCount}</strong></div><div data-attention={dueCount>0}><span>{nb?"Oppfølging nå":"Follow-up due"}</span><strong>{dueCount}</strong></div></div>
 <div className="application-toolbar"><div className="application-filters"><label><span className="sr-only">{nb?"Søk i søknadssaker":"Search application cases"}</span><Input value={search} placeholder={nb?"Søk etter stilling, kontakt eller notat …":"Search job, contact or note …"} onChange={e=>setSearch(e.target.value)}/></label><label><span className="sr-only">{nb?"Filtrer søknadsstatus":"Filter application status"}</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">{nb?"Alle saker":"All cases"}</option><option value="DUE">{nb?"Tid for oppfølging":"Follow-up due"}</option>{applicationStatuses.map(status=><option key={status} value={status}>{labels[status]}</option>)}</select></label></div><p className="application-result-count">{filtered.length} {nb?"av":"of"} {applicationCases.length}</p></div></>}
 {cases.data!==undefined&&!hasCases&&<Card className="workspace-empty collection-empty application-empty"><CardContent><div className="collection-empty-icon"><ClipboardList size={25}/></div><div className="collection-empty-copy"><p className="collection-empty-eyebrow">{nb?"KOM I GANG":"GET STARTED"}</p><h3>{nb?"Fra interessant stilling til neste steg":"From interesting job to the next step"}</h3><p>{nb?"Lagre en annonse først. Deretter kan du samle kontakt, status, CV-versjon og neste oppfølging her.":"Save a job first. Then keep its contact, status, CV version and next follow-up together here."}</p><Button asChild><Link href="/jobs/saved">{nb?"Åpne mine stillinger":"Open saved jobs"}<ArrowRight size={15}/></Link></Button></div></CardContent></Card>}
 <div className="application-card-grid">{filtered.map(value=><Card key={value.id} className="application-card" data-follow-up={due(value)}><CardContent><div className="application-card-top"><Badge variant="secondary">{labels[value.content.status]}</Badge>{due(value)&&<Badge variant="outline"><CalendarDays size={13}/>{nb?"Følg opp":"Follow up"}</Badge>}</div><h3>{value.jobTitle}</h3>{value.content.contactName&&<p className="application-contact">{value.content.contactName}</p>}<div className="application-card-meta"><p>{value.content.appliedOn?(nb?"Sendt":"Applied"):(nb?"Ikke sendt":"Not submitted")}</p>{value.content.appliedOn&&<time dateTime={value.content.appliedOn}>{value.content.appliedOn}</time>}</div>{value.content.nextFollowUpOn&&<p className="application-next-step">{nb?"Neste oppfølging":"Next follow-up"} <time dateTime={value.content.nextFollowUpOn}>{value.content.nextFollowUpOn}</time></p>}<Button className="application-open-button" variant="outline" onClick={()=>open(value)}>{nb?"Åpne saken":"Open case"}<ArrowRight size={15}/></Button></CardContent></Card>)}</div>{hasCases&&filtered.length===0&&<p className="application-no-results">{nb?"Ingen saker passer filteret.":"No cases match this filter."}</p>}
 <Dialog open={creating} onOpenChange={open=>{if(!create.isPending)setCreating(open);}}><DialogContent className="claim-dialog"><DialogHeader><DialogTitle>{nb?"Opprett søknadssak":"Create application case"}</DialogTitle><DialogDescription>{nb?"Velg en bevart annonse. En eksisterende sak for samme annonse åpnes igjen.":"Choose a saved advertisement. An existing case for the same advertisement is reopened."}</DialogDescription></DialogHeader><label>{nb?"Lagret stilling":"Saved job"}<select className="workspace-select" value={jobId} onChange={e=>setJobId(e.target.value)}><option value="">{nb?"Velg stilling":"Choose job"}</option>{jobs.data?.map(job=><option key={job.id} value={job.id}>{job.content.title}</option>)}</select></label>{jobs.data?.length===0&&<Link href="/jobs/analyze">{nb?"Analyser og lagre en stilling først":"Analyze and save a job first"}</Link>}{create.isError&&<p role="alert">{applicationError(create.error.message,locale)}</p>}<Button disabled={!jobId||create.isPending} onClick={()=>create.mutate()}>{nb?"Opprett / åpne sak":"Create / open case"}</Button></DialogContent></Dialog>
 <Sheet open={selected!==null} onOpenChange={open=>{if(!open&&!save.isPending){setSelected(null);setDraft(null);}}}><SheetContent className="document-workspace-sheet" closeLabel={nb?"Lukk":"Close"}>{selected&&draft&&<><SheetHeader><SheetTitle>{selected.jobTitle}</SheetTitle><SheetDescription>{nb?"Statusen bygger på det du registrerer. Appen sender ingen søknad eller melding.":"Status reflects what you record. The app sends no application or message."}</SheetDescription></SheetHeader><form className="application-form" onSubmit={e=>{e.preventDefault();if(draft.appliedOn&&!locked)setSubmissionReview(true);else save.mutate();}}><Card><CardContent><div className="cv-form-row"><label>{nb?"Søknadsstatus":"Application status"}<select className="workspace-select" value={draft.status} onChange={e=>set("status",e.target.value as ApplicationStatus)}>{applicationStatuses.map(status=><option key={status} value={status}>{labels[status]}</option>)}</select></label><label>{nb?"Neste oppfølging (valgfritt)":"Next follow-up (optional)"}<Input type="date" value={draft.nextFollowUpOn??""} onChange={e=>set("nextFollowUpOn",e.target.value||null)}/></label></div><label>{nb?"Godkjent CV-versjon":"Approved CV version"}<select className="workspace-select" value={draft.cvVersionId??""} disabled={locked||cvs.isError||cvs.isPending} onChange={e=>set("cvVersionId",e.target.value||null)}><option value="">{nb?"Ikke valgt":"Not selected"}</option>{allowedCvs.map(v=><option key={v.id} value={v.id}>{v.title} · {new Date(v.approvedAt!).toLocaleDateString(locale)}</option>)}</select></label>{attached&&<p className="hint">{nb?"Bevart CV-ID: ":"Preserved CV ID: "}{attached.id}</p>}<Button asChild variant="outline"><Link href="/cv">{nb?"Se eller lag CV-versjoner":"View or create CV versions"}</Link></Button><label>{nb?"Dato du faktisk sendte søknaden":"Date you actually submitted"}<Input type="date" value={draft.appliedOn??""} max={today} disabled={locked} onChange={e=>set("appliedOn",e.target.value||null)}/></label><label>{nb?"Søknadstekst / svar du vil bevare":"Application text / answers to preserve"}<Textarea rows={5} maxLength={5000} disabled={locked} value={draft.applicationText} onChange={e=>set("applicationText",e.target.value)}/></label>{locked&&<p className="notice">{nb?"Innsendingsdato, CV-versjon og søknadstekst er bevart og låst. Du kan fortsatt oppdatere status og oppfølging.":"Submission date, CV version and application text are preserved and locked. You can still update status and follow-up."}</p>}</CardContent></Card>
 <Card><CardContent><h3>{nb?"Kontakt og notater":"Contact and notes"}</h3>{([['contactName',nb?'Kontaktperson':'Contact person'],['contactEmail',nb?'Kontaktens e-post':'Contact email'],['contactPhone',nb?'Kontaktens telefon':'Contact phone']] as const).map(([key,label])=><label key={key}>{label}<Input maxLength={key==='contactPhone'?100:200} value={draft[key]} onChange={e=>set(key,e.target.value)}/></label>)}<label>{nb?"Private notater":"Private notes"}<Textarea rows={4} maxLength={5000} value={draft.notes} onChange={e=>set("notes",e.target.value)}/></label></CardContent></Card>
 {save.isError&&<p role="alert">{applicationError(save.error.message,locale)}</p>}<Button type="submit" disabled={save.isPending}>{save.isPending?(nb?"Lagrer …":"Saving …"):(nb?"Lagre saken":"Save case")}</Button></form><details className="source-evidence"><summary>{nb?"Statushistorikk":"Status history"}</summary><ol>{selected.history.map((h,i)=><li key={i}>{labels[h.status]} · {new Date(h.recordedAt).toLocaleString(locale)}{h.appliedOn&&<p>{nb?"Registrert sendt: ":"Recorded submission: "}{h.appliedOn} · CV {h.cvVersionId}</p>}</li>)}</ol></details><Button variant="ghost" disabled={save.isPending} onClick={()=>{remove.reset();setDeleting(true);}}><Trash2 size={15}/>{nb?"Slett saken":"Delete case"}</Button></>}</SheetContent></Sheet>
 <Dialog open={submissionReview} onOpenChange={open=>{if(!save.isPending)setSubmissionReview(open);}}><DialogContent className="claim-dialog"><DialogHeader><DialogTitle>{nb?"Registrer innsendingen":"Record the submission"}</DialogTitle><DialogDescription>{nb?"Bekreft at dette er materialene du allerede har sendt. Dette sender ingenting til arbeidsgiveren.":"Confirm these are the materials you already submitted. This sends nothing to the employer."}</DialogDescription></DialogHeader><p>{selected?.jobTitle}</p><p>{attached?.title??(nb?"Ingen CV valgt":"No CV selected")} · {draft?.appliedOn}</p><p className="hint">CV {draft?.cvVersionId}</p><blockquote>{draft?.applicationText||(nb?"Ingen søknadstekst registrert":"No application text recorded")}</blockquote>{save.isError&&<p role="alert">{applicationError(save.error.message,locale)}</p>}<DialogFooter><Button variant="outline" disabled={save.isPending} onClick={()=>setSubmissionReview(false)}>{nb?"Tilbake":"Back"}</Button><Button disabled={save.isPending||!draft?.cvVersionId} onClick={()=>save.mutate()}><Send size={15}/>{nb?"Ja, registrer det jeg har sendt":"Yes, record what I submitted"}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={deleting} onOpenChange={open=>{if(!remove.isPending)setDeleting(open);}}><DialogContent><DialogHeader><DialogTitle>{nb?"Slett søknadssaken?":"Delete this application case?"}</DialogTitle><DialogDescription>{nb?"Statushistorikk, kontakt og notater slettes. Lagret annonse og CV-versjoner beholdes.":"Status history, contact and notes are deleted. The saved job and CV versions remain."}</DialogDescription></DialogHeader>{remove.isError&&<p role="alert">{applicationError(remove.error.message,locale)}</p>}<DialogFooter><Button variant="outline" disabled={remove.isPending} onClick={()=>setDeleting(false)}>{nb?"Avbryt":"Cancel"}</Button><Button disabled={remove.isPending} onClick={()=>remove.mutate()}>{nb?"Slett saken":"Delete case"}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
