"use client";
import { useEffect,useState } from "react";
import { useQuery,useMutation,useQueryClient } from "@tanstack/react-query";
import { Plus,BriefcaseBusiness,CalendarDays,FileText,PenLine,ShieldCheck,FolderKanban,GraduationCap,Award,Building2,Clock3,CircleCheck,History,Trash2,ChevronDown } from "lucide-react";
import { isEntries,isEntry,isEntryEvidence,emptyEntry,entryKinds,entryPeriod,entryError,type CareerEntry,type EntryContent,type EntryKind } from "../lib/career-entries";
import type { Locale } from "../lib/translations";
import { Card,CardContent,CardHeader } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Badge } from "./ui/badge";
import { CareerComparison } from "./career-comparison";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "./ui/dialog";
export function CareerEntryPanel({locale,csrfToken,onAuthRequired,sectionActive}:{locale:Locale;csrfToken:string;onAuthRequired:()=>void;sectionActive:boolean}) {
 const nb=locale === "nb";const cache=useQueryClient();const [expanded,setExpanded]=useState(true);const [filter,setFilter]=useState<EntryKind|"ALL">("ALL");const [mode,setMode]=useState<"create"|"edit"|"confirm"|"reject"|"delete"|"history"|"evidence"|null>(null);const [active,setActive]=useState<CareerEntry|null>(null);const [draft,setDraft]=useState<EntryContent>({...emptyEntry});
 async function request(path:string,method="GET",body?:unknown){const r=await fetch(path,{method,cache:"no-store",headers:body ? {"Content-Type":"application/json","X-CSRF-TOKEN":csrfToken} : undefined,body:body ? JSON.stringify(body) : undefined});if(r.status === 204) return null;const v=await r.json();if(!r.ok) throw new Error(v.code ?? "ENTRY_UNAVAILABLE");return v as unknown;}
 const entries=useQuery({queryKey:["private-entries"],gcTime:0,retry:false,enabled:sectionActive || mode !== null,queryFn:async()=>{const v=await request("/api/profile/me/entries");if(!isEntries(v)) throw new Error("ENTRY_UNAVAILABLE");return v;}});
 const history=useQuery({queryKey:["private-entry-history",active?.id],gcTime:0,retry:false,enabled:mode === "history" && active !== null,queryFn:async()=>{const v=await request(`/api/profile/me/entries/${active!.id}/history`);if(!isEntries(v)) throw new Error("ENTRY_UNAVAILABLE");return v;}});
 const evidence=useQuery({queryKey:["private-entry-evidence",active?.id],gcTime:0,retry:false,enabled:mode==="evidence" && active!==null,queryFn:async()=>{const value=await request(`/api/profile/me/entries/${active!.id}/evidence`);if(!isEntryEvidence(value))throw new Error("ENTRY_UNAVAILABLE");return value;}});
 const write=useMutation({retry:false,mutationFn:async()=>{const path="/api/profile/me/entries"+(active ? `/${active.id}` : "");const operation=mode!;const body=operation === "create" ? {content:draft} : operation === "edit" ? {content:draft,revision:active!.revision} : operation === "delete" ? {revision:active!.revision} : {revision:active!.revision,decision:operation === "confirm" ? "CONFIRM" : "REJECT"};const v=await request(path+(["confirm","reject"].includes(operation) ? "/review" : ""),operation === "edit" ? "PUT" : operation === "delete" ? "DELETE" : "POST",body);if(operation !== "delete" && !isEntry(v)) throw new Error("ENTRY_UNAVAILABLE");return v;},onSuccess:()=>{setMode(null);setExpanded(true);void cache.invalidateQueries({queryKey:["private-entries"]});void cache.invalidateQueries({queryKey:["private-entry-history"]});void cache.invalidateQueries({queryKey:["private-claim-context"]});}});
 const error=entries.error ?? history.error ?? evidence.error ?? write.error;
 useEffect(()=>{if(error?.message === "AUTH_REQUIRED") onAuthRequired();},[error,onAuthRequired]);
 function open(next:NonNullable<typeof mode>,entry:CareerEntry|null=null){write.reset();setActive(entry);setDraft(entry ? {...entry.content} : {...emptyEntry,sourceNote:nb ? "Egen opplysning" : "Own statement"});setMode(next);}
 const status=(value:CareerEntry["status"])=>value === "CONFIRMED" ? (nb ? "Bekreftet" : "Confirmed") : value === "REJECTED" ? (nb ? "Avvist" : "Rejected") : (nb ? "Ubekreftet" : "Unverified");
 const labels:Record<string,string>={title:nb ? "Formell tittel / navn" : "Formal title / name",organization:nb ? "Arbeidsgiver / organisasjon" : "Employer / organization",client:nb ? "Kunde (valgfritt)" : "Client (optional)",deliveryRole:nb ? "Faktisk leveranserolle (valgfritt)" : "Actual delivery role (optional)",sourceNote:nb ? "Grunnlag / kilde" : "Evidence / source"};
 const filtered=[...(entries.data ?? [])].filter(e=>filter === "ALL" || e.content.kind === filter).sort((a,b)=>(b.content.startMonth ?? "").localeCompare(a.content.startMonth ?? ""));
 const confirmedCount=(entries.data ?? []).filter(entry=>entry.status==="CONFIRMED").length;
 const reviewCount=(entries.data ?? []).filter(entry=>entry.status==="UNVERIFIED").length;
 const entryIcon=(kind:EntryKind)=>kind==="PROJECT"?FolderKanban:kind==="EDUCATION"?GraduationCap:kind==="CERTIFICATION"?Award:BriefcaseBusiness;
 if (sectionActive && mode === null && entries.isPending) return <Card className="career-empty-state-card" id="profile-career-history"><CardHeader><h2 className="flex items-center gap-2"><BriefcaseBusiness size={20}/>{nb ? "Arbeid, prosjekter og utdanning" : "Employment, projects and education"}</h2></CardHeader><CardContent><p className="profile-section-loading" role="status">{nb ? "Henter arbeidshistorikken din …" : "Loading your career timeline …"}</p></CardContent></Card>;
 if (sectionActive && mode === null && entries.isError) return <Card className="career-empty-state-card" id="profile-career-history"><CardHeader><h2 className="flex items-center gap-2"><BriefcaseBusiness size={20}/>{nb ? "Arbeid, prosjekter og utdanning" : "Employment, projects and education"}</h2></CardHeader><CardContent><div className="profile-empty-error"><p role="alert">{entryError(entries.error.message,locale)}</p><Button variant="outline" onClick={()=>void entries.refetch()}>{nb ? "Prøv igjen" : "Try again"}</Button></div></CardContent></Card>;
 if (sectionActive && mode === null && entries.data?.length === 0) return <Card className="career-empty-state-card" id="profile-career-history"><CardHeader><div className="workspace-heading"><div><h2 className="flex items-center gap-2"><BriefcaseBusiness size={20}/>{nb ? "Arbeid, prosjekter og utdanning" : "Employment, projects and education"}</h2><p className="hint">{nb ? "En strukturert tidslinje til CV-en. Skille mellom arbeidsgiver, kunde og faktisk rolle." : "A structured timeline for your CV. Keep employer, client and actual role distinct."}</p></div><Button variant="outline" onClick={()=>open("create")}><Plus size={15}/>{nb ? "Legg til historikk" : "Add career entry"}</Button></div></CardHeader><CardContent>
   <section className="profile-empty-state career-empty-state">
    <div className="profile-empty-icon"><CalendarDays size={24} aria-hidden="true"/></div>
    <div className="profile-empty-copy">
      <span className="profile-overline">{nb ? "Bygg i ditt tempo" : "Build it at your pace"}</span>
      <h3>{nb ? "Begynn med ett kapittel" : "Start with one chapter"}</h3>
      <p>{nb ? "Legg inn en rolle, et prosjekt eller utdanning. Ukjente datoer kan stå tomme, og nye opplysninger bekreftes først når du har sett over dem." : "Add a role, project or education. Unknown dates can stay blank, and new information is confirmed only after you review it."}</p>
      <ol className="profile-empty-steps">
        <li><span>1</span>{nb ? "Skill arbeidsgiver, kunde og rolle" : "Separate employer, client and role"}</li>
        <li><span>2</span>{nb ? "Beskriv ditt eget bidrag" : "Describe your own contribution"}</li>
        <li><span>3</span>{nb ? "Se over og bekreft selv" : "Review and confirm it yourself"}</li>
      </ol>
      <div className="profile-empty-actions">
        <Button onClick={()=>open("create")}><PenLine size={16} aria-hidden="true"/>{nb ? "Legg til første historikkpunkt" : "Add your first entry"}</Button>
        <Button asChild variant="outline"><a href="#profile-documents"><FileText size={16} aria-hidden="true"/>{nb ? "Bruk et dokument som kilde" : "Use a document as a source"}</a></Button>
      </div>
      <p className="profile-empty-footnote"><ShieldCheck size={14} aria-hidden="true"/>{nb ? "Ubekreftet betyr ikke feil – du bestemmer når opplysningen er gjennomgått." : "Unverified does not mean incorrect—you decide when it has been reviewed."}</p>
    </div>
   </section>
 </CardContent></Card>;
 return <Card id="profile-career-history" className="career-history-panel">
  <CardHeader>
   <div className="workspace-heading career-history-heading">
    <div><span className="profile-overline">{nb?"TIDSLINJE":"TIMELINE"}</span><h2 className="flex items-center gap-2"><BriefcaseBusiness size={20}/>{nb ? "Arbeid, prosjekter og utdanning" : "Employment, projects and education"}</h2><p className="hint">{nb ? "En strukturert tidslinje til CV-en. Skille mellom arbeidsgiver, kunde og faktisk rolle." : "A structured timeline for your CV. Keep employer, client and actual role distinct."}</p></div>
    <div className="career-history-header-actions"><span className="career-history-count"><CalendarDays size={15}/>{entries.data?.length ?? 0} {nb?"oppføringer":"entries"}</span><Button onClick={()=>open("create")}><Plus size={15}/>{nb ? "Legg til historikk" : "Add career entry"}</Button></div>
   </div>
  </CardHeader>
  <CardContent>
   {entries.error && <p role="alert" className="coverage-error">{entryError(entries.error.message,locale)}</p>}
   {entries.isPending && <p role="status" className="profile-section-loading">{nb ? "Henter historikk …" : "Loading history …"}</p>}
   {entries.data?.length === 0 && <p className="hint">{nb ? "Ingen tidslinje registrert. Legg til et arbeidsforhold, prosjekt eller utdanning; bekreft det separat før CV-bruk." : "No timeline yet. Add employment, a project or education; confirm it separately before CV use."}</p>}
   {expanded && !!entries.data?.length && <>
    <div className="career-entry-overview">
     <div className="career-entry-stat"><span className="career-entry-stat-icon"><BriefcaseBusiness size={16}/></span><span>{nb?"Registrerte opplysninger":"Recorded entries"}</span><strong>{entries.data.length}</strong></div>
     <div className="career-entry-stat career-entry-stat-confirmed"><span className="career-entry-stat-icon"><CircleCheck size={16}/></span><span>{nb?"Bekreftet av deg":"Confirmed by you"}</span><strong>{confirmedCount}</strong></div>
     <div className="career-entry-stat career-entry-stat-review"><span className="career-entry-stat-icon"><Clock3 size={16}/></span><span>{nb?"Ubekreftede utkast":"Unverified drafts"}</span><strong>{reviewCount}</strong></div>
    </div>
    <div className="career-entry-toolbar">
     <div className="career-entry-filters" role="group" aria-label={nb?"Filtrer historikk etter type":"Filter career entries by type"}>
      <Button size="sm" aria-pressed={filter==="ALL"} variant={filter === "ALL" ? "default" : "outline"} onClick={()=>setFilter("ALL")}>{nb ? "Alle" : "All"}<span>{entries.data.length}</span></Button>
      {(Object.keys(entryKinds[locale]) as EntryKind[]).map(kind=><Button size="sm" key={kind} aria-pressed={filter===kind} variant={filter === kind ? "default" : "outline"} onClick={()=>setFilter(kind)}>{entryKinds[locale][kind]}<span>{entries.data!.filter(entry=>entry.content.kind===kind).length}</span></Button>)}
     </div>
     <Button className="career-history-collapse" variant="ghost" size="sm" aria-expanded={expanded} aria-label={expanded ? nb ? "Skjul historikk" : "Hide timeline" : nb ? "Vis historikk" : "Show timeline"} onClick={()=>setExpanded(!expanded)}><ChevronDown size={15}/><span>{expanded ? nb ? "Skjul" : "Hide" : nb ? "Vis" : "Show"}</span></Button>
    </div>
    {filtered.length===0 ? <p className="career-filter-empty">{nb?"Ingen oppføringer i denne kategorien ennå.":"No entries in this category yet."}</p> : <div className="career-entry-grid">
     {filtered.map(entry=>{const Icon=entryIcon(entry.content.kind);return <article key={entry.id} className="career-entry" data-status={entry.status} data-kind={entry.content.kind.toLowerCase()}>
      <div className="career-entry-card-heading"><span className={`career-entry-kind-icon career-entry-kind-${entry.content.kind.toLowerCase()}`}><Icon size={18}/></span><div className="career-entry-title-group"><div className="career-entry-badges"><Badge variant="outline">{entryKinds[locale][entry.content.kind]}</Badge><Badge variant="secondary" className="career-entry-status">{status(entry.status)}</Badge></div><h3>{entry.content.title}</h3><p className="career-entry-organization"><Building2 size={14}/>{entry.content.organization}</p></div></div>
      <div className="career-entry-period"><CalendarDays size={14}/><span>{entryPeriod(entry.content,locale)}</span></div>
      {(entry.content.client || entry.content.deliveryRole) && <div className="career-entry-details">{entry.content.client && <p><span>{nb?"Kunde":"Client"}</span>{entry.content.client}</p>}{entry.content.deliveryRole && <p><span>{nb?"Leveranserolle":"Delivery role"}</span>{entry.content.deliveryRole}</p>}</div>}
      {entry.content.description && <p className="career-entry-description">{entry.content.description}</p>}
      <div className="career-entry-actions"><Button size="sm" variant="outline" onClick={()=>open("edit",entry)}><PenLine size={14}/>{nb ? "Rediger" : "Edit"}</Button>{entry.status !== "CONFIRMED" && <Button size="sm" className="career-entry-confirm" onClick={()=>open("confirm",entry)}><ShieldCheck size={14}/>{nb ? "Bekreft" : "Confirm"}</Button>}{entry.status !== "REJECTED" && <Button size="sm" variant="ghost" onClick={()=>open("reject",entry)}>{nb ? "Avvis" : "Reject"}</Button>}<Button size="sm" variant="ghost" onClick={()=>open("evidence",entry)}><FileText size={14}/>{nb ? "Dokumentkilder" : "Document sources"}</Button><Button size="sm" variant="ghost" onClick={()=>open("history",entry)}><History size={14}/>{nb ? "Historikk" : "History"}</Button><Button size="sm" variant="ghost" onClick={()=>open("delete",entry)}><Trash2 size={14}/>{nb ? "Slett" : "Delete"}</Button></div>
     </article>;})}
    </div>}
    <CareerComparison entries={entries.data} locale={locale} onEdit={entry=>open("edit",entry)} onAuthRequired={onAuthRequired}/>
   </>}
 <Dialog open={mode !== null} onOpenChange={open=>{if(!open && !write.isPending)setMode(null);}}><DialogContent className="career-entry-dialog" closeLabel={nb ? "Lukk" : "Close"}><DialogHeader><DialogTitle>{mode === "create" ? (nb ? "Legg til karrierehistorikk" : "Add career history") : mode === "edit" ? (nb ? "Rediger karrierehistorikk" : "Edit career history") : mode === "confirm" ? (nb ? "Bekreft historikkpunktet" : "Confirm career entry") : mode === "reject" ? (nb ? "Avvis historikkpunktet" : "Reject career entry") : mode === "delete" ? (nb ? "Slett historikkpunktet?" : "Delete career entry?") : mode === "evidence" ? (nb ? "Dokumentert grunnlag" : "Document evidence") : (nb ? "Revisjonshistorikk" : "Revision history")}</DialogTitle><DialogDescription>{mode === "delete" ? (nb ? "Historikkpunktet og revisjonene slettes. Tidligere CV-versjoner kan beholde sin kopi. Dette kan ikke angres." : "The entry and its revisions are deleted. Earlier CV versions can retain their snapshot. This cannot be undone.") : (nb ? "Nye og redigerte opplysninger er ubekreftet. Bekreft bare hvis rolle, periode og eget bidrag er riktig. Ukjente datoer beholdes som ukjente." : "New and edited entries are unverified. Confirm only accurate roles, dates and your own contribution. Unknown dates remain unknown.")}</DialogDescription></DialogHeader>
 {write.error && <p role="alert" className="notice">{entryError(write.error.message,locale)}</p>}
 {(mode === "create" || mode === "edit") && <form className="text-form" onSubmit={e=>{e.preventDefault();write.mutate();}}><label htmlFor="entry-kind">{nb ? "Type" : "Type"}</label><select id="entry-kind" value={draft.kind} disabled={write.isPending} onChange={e=>setDraft({...draft,kind:e.target.value as EntryKind})}>{(Object.keys(entryKinds[locale]) as EntryKind[]).map(kind=><option key={kind} value={kind}>{entryKinds[locale][kind]}</option>)}</select>{(["title","organization","client","deliveryRole"] as const).map(field=><div key={field}><label htmlFor={`entry-${field}`}>{labels[field]}</label><Input id={`entry-${field}`} value={draft[field]} required={["title","organization"].includes(field)} maxLength={200} disabled={write.isPending} onChange={e=>setDraft({...draft,[field]:e.target.value})}/></div>)}<div className="career-entry-dates"><div><label htmlFor="entry-start">{nb ? "Fra måned (valgfritt)" : "Start month (optional)"}</label><Input id="entry-start" type="month" value={draft.startMonth ?? ""} disabled={write.isPending} onChange={e=>setDraft({...draft,startMonth:e.target.value || null})}/></div><div><label htmlFor="entry-end">{nb ? "Til måned (valgfritt)" : "End month (optional)"}</label><Input id="entry-end" type="month" value={draft.endMonth ?? ""} disabled={draft.ongoing || write.isPending} onChange={e=>setDraft({...draft,endMonth:e.target.value || null})}/></div></div><label className="ai-consent"><input type="checkbox" checked={draft.ongoing} disabled={write.isPending} onChange={e=>setDraft({...draft,ongoing:e.target.checked,endMonth:e.target.checked ? null : draft.endMonth})}/>{nb ? "Pågår fortsatt" : "Still ongoing"}</label><label htmlFor="entry-description">{nb ? "Eget bidrag / beskrivelse (valgfritt)" : "Your contribution / description (optional)"}</label><Textarea id="entry-description" value={draft.description} maxLength={2000} rows={4} disabled={write.isPending} onChange={e=>setDraft({...draft,description:e.target.value})}/><label htmlFor="entry-source">{labels.sourceNote}</label><Input id="entry-source" value={draft.sourceNote} maxLength={500} required disabled={write.isPending} onChange={e=>setDraft({...draft,sourceNote:e.target.value})}/><Button type="submit" disabled={write.isPending}>{write.isPending ? (nb ? "Lagrer …" : "Saving …") : (nb ? "Lagre som ubekreftet" : "Save as unverified")}</Button></form>}
 {active && ["confirm","reject","delete"].includes(mode ?? "") && <><h3>{active.content.title}</h3><p>{active.content.organization}{active.content.client ? ` · ${active.content.client}` : ""}</p><p>{active.content.deliveryRole}</p><p>{entryPeriod(active.content,locale)}</p><p className="whitespace-pre-wrap">{active.content.description}</p><p className="hint">{active.content.sourceNote}</p><Button disabled={write.isPending} onClick={()=>write.mutate()}>{mode === "confirm" ? (nb ? "Ja, opplysningene er riktige" : "Yes, these details are accurate") : mode === "reject" ? (nb ? "Avvis opplysningen" : "Reject entry") : (nb ? "Slett opplysning og historikk" : "Delete entry and history")}</Button></>}
 {mode === "history" && <>{history.isPending && <p role="status">{nb ? "Henter revisjoner …" : "Loading revisions …"}</p>}{history.error && <p role="alert">{entryError(history.error.message,locale)}</p>}{history.data?.map(entry=><article key={entry.revision} className="career-entry"><Badge variant="outline">{status(entry.status)} · {entry.revision}</Badge><h3>{entry.content.title}</h3><p>{entry.content.organization} · {entryPeriod(entry.content,locale)}</p><p className="whitespace-pre-wrap">{entry.content.description}</p><p className="hint">{entry.content.sourceNote}</p></article>)}</>}
 {mode==="evidence" && <>{evidence.isPending && <p role="status">{nb?"Henter kilder …":"Loading sources …"}</p>}{evidence.error && <p role="alert">{entryError(evidence.error.message,locale)}</p>}{evidence.data?.length===0 && <p>{nb?"Ingen strukturerte dokumentkilder. Se kildebeskrivelsen og revisjonshistorikken.":"No structured document sources. Check the source note and revision history."}</p>}{evidence.data?.map((item,index)=><article className="career-entry" key={index}><h3>{item.originalName}</h3><p className="hint">{nb?"Importrevisjon":"Import revision"} {item.revision} · {item.periodText}{item.documentId?"":nb?" · originalen er slettet":" · original deleted"}</p><blockquote className="whitespace-pre-wrap">{item.quote}</blockquote></article>)}</>}
 </DialogContent></Dialog></CardContent></Card>;
}
