"use client";
import { useEffect,useState } from "react";
import { useQuery,useMutation,useQueryClient } from "@tanstack/react-query";
import { Plus,BriefcaseBusiness } from "lucide-react";
import { isEntries,isEntry,isEntryEvidence,emptyEntry,entryKinds,entryPeriod,entryError,type CareerEntry,type EntryContent,type EntryKind } from "../lib/career-entries";
import type { Locale } from "../lib/translations";
import { Card,CardContent,CardHeader } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Badge } from "./ui/badge";
import { CareerComparison } from "./career-comparison";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "./ui/dialog";
export function CareerEntryPanel({locale,csrfToken,onAuthRequired}:{locale:Locale;csrfToken:string;onAuthRequired:()=>void}) {
 const nb=locale === "nb";const cache=useQueryClient();const [expanded,setExpanded]=useState(false);const [filter,setFilter]=useState<EntryKind|"ALL">("ALL");const [mode,setMode]=useState<"create"|"edit"|"confirm"|"reject"|"delete"|"history"|"evidence"|null>(null);const [active,setActive]=useState<CareerEntry|null>(null);const [draft,setDraft]=useState<EntryContent>({...emptyEntry});
 async function request(path:string,method="GET",body?:unknown){const r=await fetch(path,{method,cache:"no-store",headers:body ? {"Content-Type":"application/json","X-CSRF-TOKEN":csrfToken} : undefined,body:body ? JSON.stringify(body) : undefined});if(r.status === 204) return null;const v=await r.json();if(!r.ok) throw new Error(v.code ?? "ENTRY_UNAVAILABLE");return v as unknown;}
 const entries=useQuery({queryKey:["private-entries"],gcTime:0,retry:false,enabled:expanded || mode !== null,queryFn:async()=>{const v=await request("/api/profile/me/entries");if(!isEntries(v)) throw new Error("ENTRY_UNAVAILABLE");return v;}});
 const history=useQuery({queryKey:["private-entry-history",active?.id],gcTime:0,retry:false,enabled:mode === "history" && active !== null,queryFn:async()=>{const v=await request(`/api/profile/me/entries/${active!.id}/history`);if(!isEntries(v)) throw new Error("ENTRY_UNAVAILABLE");return v;}});
 const evidence=useQuery({queryKey:["private-entry-evidence",active?.id],gcTime:0,retry:false,enabled:mode==="evidence" && active!==null,queryFn:async()=>{const value=await request(`/api/profile/me/entries/${active!.id}/evidence`);if(!isEntryEvidence(value))throw new Error("ENTRY_UNAVAILABLE");return value;}});
 const write=useMutation({retry:false,mutationFn:async()=>{const path="/api/profile/me/entries"+(active ? `/${active.id}` : "");const operation=mode!;const body=operation === "create" ? {content:draft} : operation === "edit" ? {content:draft,revision:active!.revision} : operation === "delete" ? {revision:active!.revision} : {revision:active!.revision,decision:operation === "confirm" ? "CONFIRM" : "REJECT"};const v=await request(path+(["confirm","reject"].includes(operation) ? "/review" : ""),operation === "edit" ? "PUT" : operation === "delete" ? "DELETE" : "POST",body);if(operation !== "delete" && !isEntry(v)) throw new Error("ENTRY_UNAVAILABLE");return v;},onSuccess:()=>{setMode(null);setExpanded(true);void cache.invalidateQueries({queryKey:["private-entries"]});void cache.invalidateQueries({queryKey:["private-entry-history"]});void cache.invalidateQueries({queryKey:["private-claim-context"]});}});
 const error=entries.error ?? history.error ?? evidence.error ?? write.error;
 useEffect(()=>{if(error?.message === "AUTH_REQUIRED") onAuthRequired();},[error,onAuthRequired]);
 function open(next:NonNullable<typeof mode>,entry:CareerEntry|null=null){write.reset();setActive(entry);setDraft(entry ? {...entry.content} : {...emptyEntry,sourceNote:nb ? "Egen opplysning" : "Own statement"});setMode(next);}
 const status=(value:CareerEntry["status"])=>value === "CONFIRMED" ? (nb ? "Bekreftet" : "Confirmed") : value === "REJECTED" ? (nb ? "Avvist" : "Rejected") : (nb ? "Ubekreftet" : "Unverified");
 const labels:Record<string,string>={title:nb ? "Formell tittel / navn" : "Formal title / name",organization:nb ? "Arbeidsgiver / organisasjon" : "Employer / organization",client:nb ? "Kunde (valgfritt)" : "Client (optional)",deliveryRole:nb ? "Faktisk leveranserolle (valgfritt)" : "Actual delivery role (optional)",sourceNote:nb ? "Grunnlag / kilde" : "Evidence / source"};
 const filtered=[...(entries.data ?? [])].filter(e=>filter === "ALL" || e.content.kind === filter).sort((a,b)=>(b.content.startMonth ?? "").localeCompare(a.content.startMonth ?? ""));
 return <Card id="profile-career-history"><CardHeader><div className="workspace-heading"><div><h2 className="flex items-center gap-2"><BriefcaseBusiness size={20}/>{nb ? "Arbeid, prosjekter og utdanning" : "Employment, projects and education"}</h2><p className="hint">{nb ? "En strukturert tidslinje til CV-en. Skille mellom arbeidsgiver, kunde og faktisk rolle." : "A structured timeline for your CV. Keep employer, client and actual role distinct."}</p></div><Button variant="outline" onClick={()=>open("create")}><Plus size={15}/>{nb ? "Legg til historikk" : "Add career entry"}</Button></div></CardHeader><CardContent><Button variant="ghost" onClick={()=>setExpanded(!expanded)}>{expanded ? (nb ? "Skjul karrierehistorikk" : "Hide career history") : (nb ? "Se karrierehistorikk" : "View career history")}</Button>
 {expanded && <>{entries.isPending && <p role="status">{nb ? "Henter historikk …" : "Loading history …"}</p>}{entries.error && <p role="alert">{entryError(entries.error.message,locale)}</p>}<CareerComparison entries={entries.data ?? []} locale={locale} onEdit={entry=>open("edit",entry)} onAuthRequired={onAuthRequired}/><div className="requirement-filters"><Button variant={filter === "ALL" ? "default" : "outline"} onClick={()=>setFilter("ALL")}>{nb ? "Alle" : "All"}</Button>{(Object.keys(entryKinds[locale]) as EntryKind[]).map(kind=><Button key={kind} variant={filter === kind ? "default" : "outline"} onClick={()=>setFilter(kind)}>{entryKinds[locale][kind]}</Button>)}</div>{entries.data?.length === 0 && <p className="hint">{nb ? "Ingen tidslinje registrert. Legg til et arbeidsforhold, prosjekt eller utdanning; bekreft det separat før CV-bruk." : "No timeline yet. Add employment, a project or education; confirm it separately before CV use."}</p>}<div className="career-entry-grid">{filtered.map(entry=><article key={entry.id} className="career-entry"><div className="flex flex-wrap gap-2"><Badge variant="outline">{entryKinds[locale][entry.content.kind]}</Badge><Badge variant="secondary">{status(entry.status)}</Badge></div><h3>{entry.content.title}</h3><p>{entry.content.organization}</p>{entry.content.client && <p className="hint">{nb ? "Kunde" : "Client"}: {entry.content.client}</p>}{entry.content.deliveryRole && <p className="hint">{nb ? "Leveranserolle" : "Delivery role"}: {entry.content.deliveryRole}</p>}<p className="hint">{entryPeriod(entry.content,locale)}</p><p className="career-entry-description">{entry.content.description}</p><div className="profile-actions"><Button size="sm" variant="outline" onClick={()=>open("edit",entry)}>{nb ? "Rediger" : "Edit"}</Button>{entry.status !== "CONFIRMED" && <Button size="sm" onClick={()=>open("confirm",entry)}>{nb ? "Bekreft" : "Confirm"}</Button>}{entry.status !== "REJECTED" && <Button size="sm" variant="ghost" onClick={()=>open("reject",entry)}>{nb ? "Avvis" : "Reject"}</Button>}<Button size="sm" variant="ghost" onClick={()=>open("evidence",entry)}>{nb ? "Dokumentkilder" : "Document sources"}</Button><Button size="sm" variant="ghost" onClick={()=>open("history",entry)}>{nb ? "Historikk" : "History"}</Button><Button size="sm" variant="ghost" onClick={()=>open("delete",entry)}>{nb ? "Slett" : "Delete"}</Button></div></article>)}</div></>}
 <Dialog open={mode !== null} onOpenChange={open=>{if(!open && !write.isPending)setMode(null);}}><DialogContent className="career-entry-dialog" closeLabel={nb ? "Lukk" : "Close"}><DialogHeader><DialogTitle>{mode === "create" ? (nb ? "Legg til karrierehistorikk" : "Add career history") : mode === "edit" ? (nb ? "Rediger karrierehistorikk" : "Edit career history") : mode === "confirm" ? (nb ? "Bekreft historikkpunktet" : "Confirm career entry") : mode === "reject" ? (nb ? "Avvis historikkpunktet" : "Reject career entry") : mode === "delete" ? (nb ? "Slett historikkpunktet?" : "Delete career entry?") : mode === "evidence" ? (nb ? "Dokumentert grunnlag" : "Document evidence") : (nb ? "Revisjonshistorikk" : "Revision history")}</DialogTitle><DialogDescription>{mode === "delete" ? (nb ? "Historikkpunktet og revisjonene slettes. Tidligere CV-versjoner kan beholde sin kopi. Dette kan ikke angres." : "The entry and its revisions are deleted. Earlier CV versions can retain their snapshot. This cannot be undone.") : (nb ? "Nye og redigerte opplysninger er ubekreftet. Bekreft bare hvis rolle, periode og eget bidrag er riktig. Ukjente datoer beholdes som ukjente." : "New and edited entries are unverified. Confirm only accurate roles, dates and your own contribution. Unknown dates remain unknown.")}</DialogDescription></DialogHeader>
 {write.error && <p role="alert" className="notice">{entryError(write.error.message,locale)}</p>}
 {(mode === "create" || mode === "edit") && <form className="text-form" onSubmit={e=>{e.preventDefault();write.mutate();}}><label htmlFor="entry-kind">{nb ? "Type" : "Type"}</label><select id="entry-kind" value={draft.kind} disabled={write.isPending} onChange={e=>setDraft({...draft,kind:e.target.value as EntryKind})}>{(Object.keys(entryKinds[locale]) as EntryKind[]).map(kind=><option key={kind} value={kind}>{entryKinds[locale][kind]}</option>)}</select>{(["title","organization","client","deliveryRole"] as const).map(field=><div key={field}><label htmlFor={`entry-${field}`}>{labels[field]}</label><Input id={`entry-${field}`} value={draft[field]} required={["title","organization"].includes(field)} maxLength={200} disabled={write.isPending} onChange={e=>setDraft({...draft,[field]:e.target.value})}/></div>)}<div className="career-entry-dates"><div><label htmlFor="entry-start">{nb ? "Fra måned (valgfritt)" : "Start month (optional)"}</label><Input id="entry-start" type="month" value={draft.startMonth ?? ""} disabled={write.isPending} onChange={e=>setDraft({...draft,startMonth:e.target.value || null})}/></div><div><label htmlFor="entry-end">{nb ? "Til måned (valgfritt)" : "End month (optional)"}</label><Input id="entry-end" type="month" value={draft.endMonth ?? ""} disabled={draft.ongoing || write.isPending} onChange={e=>setDraft({...draft,endMonth:e.target.value || null})}/></div></div><label className="ai-consent"><input type="checkbox" checked={draft.ongoing} disabled={write.isPending} onChange={e=>setDraft({...draft,ongoing:e.target.checked,endMonth:e.target.checked ? null : draft.endMonth})}/>{nb ? "Pågår fortsatt" : "Still ongoing"}</label><label htmlFor="entry-description">{nb ? "Eget bidrag / beskrivelse (valgfritt)" : "Your contribution / description (optional)"}</label><Textarea id="entry-description" value={draft.description} maxLength={2000} rows={4} disabled={write.isPending} onChange={e=>setDraft({...draft,description:e.target.value})}/><label htmlFor="entry-source">{labels.sourceNote}</label><Input id="entry-source" value={draft.sourceNote} maxLength={500} required disabled={write.isPending} onChange={e=>setDraft({...draft,sourceNote:e.target.value})}/><Button type="submit" disabled={write.isPending}>{write.isPending ? (nb ? "Lagrer …" : "Saving …") : (nb ? "Lagre som ubekreftet" : "Save as unverified")}</Button></form>}
 {active && ["confirm","reject","delete"].includes(mode ?? "") && <><h3>{active.content.title}</h3><p>{active.content.organization}{active.content.client ? ` · ${active.content.client}` : ""}</p><p>{active.content.deliveryRole}</p><p>{entryPeriod(active.content,locale)}</p><p className="whitespace-pre-wrap">{active.content.description}</p><p className="hint">{active.content.sourceNote}</p><Button disabled={write.isPending} onClick={()=>write.mutate()}>{mode === "confirm" ? (nb ? "Ja, opplysningene er riktige" : "Yes, these details are accurate") : mode === "reject" ? (nb ? "Avvis opplysningen" : "Reject entry") : (nb ? "Slett opplysning og historikk" : "Delete entry and history")}</Button></>}
 {mode === "history" && <>{history.isPending && <p role="status">{nb ? "Henter revisjoner …" : "Loading revisions …"}</p>}{history.error && <p role="alert">{entryError(history.error.message,locale)}</p>}{history.data?.map(entry=><article key={entry.revision} className="career-entry"><Badge variant="outline">{status(entry.status)} · {entry.revision}</Badge><h3>{entry.content.title}</h3><p>{entry.content.organization} · {entryPeriod(entry.content,locale)}</p><p className="whitespace-pre-wrap">{entry.content.description}</p><p className="hint">{entry.content.sourceNote}</p></article>)}</>}
 {mode==="evidence" && <>{evidence.isPending && <p role="status">{nb?"Henter kilder …":"Loading sources …"}</p>}{evidence.error && <p role="alert">{entryError(evidence.error.message,locale)}</p>}{evidence.data?.length===0 && <p>{nb?"Ingen strukturerte dokumentkilder. Se kildebeskrivelsen og revisjonshistorikken.":"No structured document sources. Check the source note and revision history."}</p>}{evidence.data?.map((item,index)=><article className="career-entry" key={index}><h3>{item.originalName}</h3><p className="hint">{nb?"Importrevisjon":"Import revision"} {item.revision} · {item.periodText}{item.documentId?"":nb?" · originalen er slettet":" · original deleted"}</p><blockquote className="whitespace-pre-wrap">{item.quote}</blockquote></article>)}</>}
 </DialogContent></Dialog></CardContent></Card>;
}
