"use client";
import { useState } from "react";
import { Eye, CircleHelp, Search, ArrowUpRight, ShieldCheck, ChevronDown } from "lucide-react";
import type { TailoringResult,VisibilityStatus } from "../lib/cv-tailoring";
import type { MatchClaim } from "../lib/personal-match";
import type { Locale } from "../lib/translations";
import { Card,CardHeader,CardContent } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { HelpTip } from "./ui/help-tip";
import { AiIdentity } from "./ai-identity";

export function CvVisibilityReview({result,claims,quotes,locale,current}:{result:TailoringResult;claims:MatchClaim[];quotes:string[];locale:Locale;current:boolean}) {
 const nb=locale==="nb",[filter,setFilter]=useState<VisibilityStatus|"ALL">("ALL"),[search,setSearch]=useState("");
 const labels:Record<VisibilityStatus,string>={VISIBLE:nb?"Tydelig i CV-en":"Visible in CV",WEAKLY_VISIBLE:nb?"Bør fremheves":"Could be clearer",NOT_VISIBLE:nb?"Ikke synlig":"Not visible",NEEDS_CLARIFICATION:nb?"Må avklares":"Needs clarification",UNASSESSED:nb?"Ikke vurdert":"Not assessed"};
 const items=result.visibility??[];
 const shown=items.filter(a=>(filter==="ALL" || a.status===filter) && `${quotes[a.requirementIndex]} ${a.reason}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 return <Card className="cv-visibility-review"><CardHeader><div className="workspace-heading"><div><p className="eyebrow">{nb?"CV OG ERFARING":"CV AND EVIDENCE"}</p><h3>{nb?"Hva viser CV-en din?":"What does your CV show?"}</h3></div><HelpTip label={nb?"Om synlighet i CV-en":"About CV visibility"}>{nb?"AI sammenligner hele den leste CV-teksten med krav og bekreftet erfaring. Ikke synlig betyr en mulig presentasjonsforbedring, ikke manglende kompetanse. Kildesitater kontrolleres, men du må vurdere betydningen selv. Dette er ikke en ATS-score.":"AI compares the full extracted CV text against requirements and confirmed evidence. Not visible means a possible presentation improvement, not missing competence. Quotations are checked; review their meaning yourself. This is not an ATS score."}</HelpTip></div><AiIdentity selections={[{provider:result.provider,model:result.model}]} locale={locale}/><p className="hint">{nb?"Samme analyse som tekstforslagene. Originalen og profilen beholdes.":"The same analysis as the wording suggestions. Your original and profile are retained."}</p></CardHeader><CardContent>
 {!current && <p role="status" className="notice">{nb?"Dette er en tidligere CV-vurdering. Grunnlaget eller valgene er endret; analyser på nytt før du bruker den.":"This is an earlier CV assessment. Evidence or selections changed; analyze again before using it."}</p>}
 {!items.length?<p className="notice">{nb?"Dette resultatet har ingen CV-sammenligning. Tekstforslagene kan fortsatt leses; en ny godkjent analyse kan vurdere synligheten.":"This result contains no CV visibility review. Wording suggestions remain readable; a new approved analysis can assess visibility."}</p>:<>
 <div className="cv-visibility-filters" role="group" aria-label={nb?"Filtrer CV-vurderingen":"Filter CV assessment"}><Button size="sm" variant={filter==="ALL"?"default":"outline"} aria-pressed={filter==="ALL"} onClick={()=>setFilter("ALL")}>{nb?"Alle":"All"}<Badge variant="outline">{items.length}</Badge></Button>{(Object.keys(labels) as VisibilityStatus[]).map(status=><Button key={status} size="sm" variant={filter===status?"default":"outline"} aria-pressed={filter===status} onClick={()=>setFilter(status)}>{labels[status]}<Badge variant="outline">{items.filter(a=>a.status===status).length}</Badge></Button>)}</div>
 <div className="cv-visibility-search"><Search size={16}/><Input value={search} onChange={e=>setSearch(e.target.value)} aria-label={nb?"Søk i CV-vurderingen":"Search CV assessment"} placeholder={nb?"Søk etter krav eller forklaring …":"Search criteria or reasons …"}/></div>
 <div className="cv-visibility-list" tabIndex={0} role="region" aria-label={nb?"Krav og CV-synlighet":"Criteria and CV visibility"}>{shown.map(item=><details className="cv-visibility-item" key={item.requirementIndex} data-state={item.status}><summary>{item.status==="VISIBLE"?<Eye size={17}/>:item.status==="WEAKLY_VISIBLE" || item.status==="NOT_VISIBLE"?<ArrowUpRight size={17}/>:<CircleHelp size={17}/>}<span>{quotes[item.requirementIndex]}</span><Badge variant="outline">{labels[item.status]}</Badge><ChevronDown size={16} className="cv-visibility-toggle" aria-hidden="true"/></summary><p>{item.reason}</p>{item.passages.map((p,index)=><div className="cv-visibility-proof" key={index}><small>{nb?"Fra grunnlags-CV · tekstavsnitt":"From base CV · passage"} {p.paragraphIndex+1}</small><blockquote>{p.quote}</blockquote></div>)}{item.claimIds.map(id=>{const c=claims.find(c=>c.id===id);return <div className="cv-visibility-evidence" key={id}><small><ShieldCheck size={14}/>{nb?"Bekreftet kandidatgrunnlag":"Confirmed candidate evidence"}</small><strong>{c?.skill} · {c?.context}</strong><p>{c?.statement}</p></div>;})}{item.status==="NEEDS_CLARIFICATION" && <p className="hint">{nb?"Åpne matchen over for å avklare erfaringen før du legger nye fakta inn i CV-en.":"Open the match above to clarify experience before adding new facts to your CV."}</p>}{(item.status==="WEAKLY_VISIBLE" || item.status==="NOT_VISIBLE") && <p className="hint">{nb?"Se tekstforslagene under. En foreslått forbedring endrer ikke kompetansen eller matchprosenten.":"Review the wording suggestions below. A proposed improvement does not change your competency or match percentage."}</p>}</details>)}{!shown.length && <p className="hint">{nb?"Ingen krav passer dette filteret.":"No criteria match this filter."}</p>}</div>
 </>}
 </CardContent></Card>;
}
