"use client";
import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { FileText,Plus,Download,Check,Trash2 } from "lucide-react";
import { Button } from "./ui/button";
import { Card,CardContent,CardHeader } from "./ui/card";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Badge } from "./ui/badge";
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from "./ui/sheet";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from "./ui/dialog";
import { useWorkspaceSession } from "../lib/workspace-session";
import { isClaimList } from "../lib/claims";
import { isEntries,entryPeriod,entryKinds } from "../lib/career-entries";
import { isSavedJobs } from "../lib/saved-jobs";
import { isCv,isCvs,cvError,emptyIdentity,type CvVersion,type CvIdentity } from "../lib/cvs";
import type { Locale } from "../lib/translations";
async function read<T>(url:string,validate:(value:unknown)=>value is T):Promise<T>{const r=await fetch(url,{cache:"no-store"});const v=await r.json();if(!r.ok)throw new Error(v.code??"CV_UNAVAILABLE");if(!validate(v))throw new Error("CV_UNAVAILABLE");return v;}
export function CvWorkspace({locale}:{locale:Locale}) {
 const nb=locale==="nb";const session=useWorkspaceSession();const cache=useQueryClient();
 const versions=useQuery({queryKey:["private-cvs"],gcTime:0,retry:false,queryFn:()=>read("/api/profile/me/cvs",isCvs)});
 const claims=useQuery({queryKey:["private-claims"],gcTime:0,retry:false,queryFn:()=>read("/api/profile/me/claims",isClaimList)});
 const entries=useQuery({queryKey:["private-career-entries"],gcTime:0,retry:false,queryFn:()=>read("/api/profile/me/entries",isEntries)});
 const jobs=useQuery({queryKey:["private-saved-jobs"],gcTime:0,retry:false,queryFn:()=>read("/api/profile/me/jobs",isSavedJobs)});
 const cleanup=useQuery({queryKey:["private-cv-cleanup"],gcTime:0,retry:false,queryFn:async()=>{const r=await fetch("/api/profile/me/cvs/cleanup",{cache:"no-store"});const v=await r.json();if(!r.ok||!Number.isSafeInteger(v.remaining))throw new Error("CV_UNAVAILABLE");return v.remaining as number;}});
 const [creating,setCreating]=useState(false);const [title,setTitle]=useState("");const [identity,setIdentity]=useState<CvIdentity>(emptyIdentity);const [selectedClaims,setSelectedClaims]=useState<string[]>([]);const [selectedEntries,setSelectedEntries]=useState<string[]>([]);const [job,setJob]=useState("");const [language,setLanguage]=useState<Locale>(locale);const [selected,setSelected]=useState<CvVersion|null>(null);const [deleting,setDeleting]=useState<CvVersion|null>(null);
 const confirmedClaims=claims.data?.filter(x=>x.status==="CONFIRMED")??[];const confirmedEntries=entries.data?.filter(x=>x.status==="CONFIRMED")??[];
 async function change(url:string,method:string,body?:unknown){const r=await fetch(url,{method,headers:{"Content-Type":"application/json","X-CSRF-TOKEN":session.data?.csrfToken??""},body:body===undefined?undefined:JSON.stringify(body)});if(r.status===204)return null;const v=await r.json();if(!r.ok)throw new Error(v.code??"CV_UNAVAILABLE");return v;}
 function update(version:CvVersion){cache.setQueryData<CvVersion[]>(["private-cvs"],old=>[version,...(old??[]).filter(v=>v.id!==version.id)]);setSelected(version);void cache.invalidateQueries({queryKey:["private-cvs"]});}
 const create=useMutation({retry:false,mutationFn:async()=>{const v=await change("/api/profile/me/cvs","POST",{title,locale:language,identity,claims:confirmedClaims.filter(x=>selectedClaims.includes(x.id)).map(x=>({id:x.id,revision:x.revision})),entries:confirmedEntries.filter(x=>selectedEntries.includes(x.id)).map(x=>({id:x.id,revision:x.revision})),jobId:job||null});if(!isCv(v))throw new Error("CV_UNAVAILABLE");return v;},onSuccess:v=>{setCreating(false);update(v);}});
 const approve=useMutation({retry:false,mutationFn:async(v:CvVersion)=>{const next=await change(`/api/profile/me/cvs/${v.id}/approve`,"POST",{revision:v.revision,approved:true});if(!isCv(next))throw new Error("CV_UNAVAILABLE");return next;},onSuccess:update});
 const remove=useMutation({retry:false,mutationFn:(v:CvVersion)=>change(`/api/profile/me/cvs/${v.id}`,"DELETE",{revision:v.revision}),onSuccess:()=>{setDeleting(null);setSelected(null);void cache.invalidateQueries({queryKey:["private-cvs"]});void cache.invalidateQueries({queryKey:["private-cv-cleanup"]});}});
 const retryCleanup=useMutation({retry:false,mutationFn:()=>change("/api/profile/me/cvs/cleanup","POST"),onSuccess:()=>void cleanup.refetch()});
 const download=useMutation({retry:false,mutationFn:async({version,format}:{version:CvVersion;format:"pdf"|"docx"})=>{const r=await fetch(`/api/profile/me/cvs/${version.id}/download/${format}`,{cache:"no-store"});if(!r.ok){const v=await r.json();throw new Error(v.code??"CV_UNAVAILABLE");}const blob=await r.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`career-cv-${version.id}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
 function openNew(){create.reset();setTitle(nb?"Min CV":"My CV");setIdentity(emptyIdentity);setSelectedClaims([]);setSelectedEntries([]);setJob("");setLanguage(locale);setCreating(true);}
 function toggle(id:string,values:string[],set:(v:string[])=>void){set(values.includes(id)?values.filter(x=>x!==id):[...values,id]);}
 return <section className="cv-workspace" aria-label={nb?"CV-versjoner":"CV versions"}>
 <div className="workspace-heading"><div><h2>{nb?"CV-en du vil sende":"The CV you want to send"}</h2><p className="hint">{nb?"Velg bekreftet erfaring, gjennomgå hele utkastet og godkjenn eksport til DOCX og PDF. Originalene dine beholdes.":"Choose confirmed experience, review the whole draft and approve DOCX and PDF export. Your originals are retained."}</p></div><Button onClick={openNew} disabled={versions.isError||claims.isError||entries.isError}><Plus size={16}/>{nb?"Lag CV-utkast":"Create CV draft"}</Button></div>
 {versions.isPending&&<p role="status">{nb?"Henter CV-versjoner …":"Loading CV versions …"}</p>}
 {versions.isError&&<Card><CardContent><p role="alert">{cvError(versions.error.message,locale)}</p>{versions.error.message==="PROFILE_NOT_CREATED"?<Button asChild><Link href="/career/profile">{nb?"Opprett profil":"Create profile"}</Link></Button>:<Button variant="outline" onClick={()=>void versions.refetch()}>{nb?"Hent på nytt":"Reload"}</Button>}</CardContent></Card>}
 {(claims.isError||entries.isError||jobs.isError)&&<p role="alert">{nb?"Noe av kandidatgrunnlaget kunne ikke hentes. Hent siden på nytt før du lager et utkast.":"Some candidate information could not be loaded. Reload before creating a draft."}<Button variant="ghost" onClick={()=>{void claims.refetch();void entries.refetch();void jobs.refetch();}}>{nb?"Hent på nytt":"Reload"}</Button></p>}
 {versions.data?.length===0&&!creating&&<Card className="workspace-empty"><CardContent><FileText size={32}/><h3>{nb?"En ryddig CV, basert på din erfaring":"A clear CV, based on your experience"}</h3><p>{nb?"Start med et utkast. Vi bruker en standardmal og eksporterer bare punktene du har bekreftet og valgt.":"Start with a draft. We use a standard template and export only the items you have confirmed and selected."}</p><Button variant="outline" asChild><Link href="/career/profile">{nb?"Gå til erfaring og dokumenter":"Go to experience and documents"}</Link></Button></CardContent></Card>}
 <div className="cv-version-grid">{versions.data?.map(v=><Card key={v.id}><CardContent><Badge variant="secondary">{v.status==="APPROVED"?(nb?"Klar til å bruke":"Ready to use"):(nb?"Utkast":"Draft")}</Badge><h3>{v.title}</h3><p>{v.content.jobTitle??(nb?"Generell CV":"General CV")}</p><p className="hint">{v.content.claims.length} {nb?"kompetansepunkter":"competencies"} · {v.content.entries.length} {nb?"historikkpunkter":"career entries"} · {v.content.locale==="nb"?"Norsk":"English"}</p>{v.stale&&<p className="notice">{nb?"Erfaringen er endret siden utkastet ble laget.":"Experience changed after this draft was created."}</p>}<Button variant="outline" onClick={()=>{approve.reset();download.reset();setSelected(v);}}>{v.status==="APPROVED"?(nb?"Se CV og last ned":"View CV and download"):(nb?"Gjennomgå utkast":"Review draft")}</Button></CardContent></Card>)}</div>
 {cleanup.data!==undefined&&cleanup.data>0&&<p className="notice" role="status">{nb?`${cleanup.data} eksportfiler venter på sletting. CV-versjonene er fjernet fra biblioteket.`:`${cleanup.data} export files await deletion. CV versions were removed from the library.`}<Button variant="outline" disabled={retryCleanup.isPending} onClick={()=>retryCleanup.mutate()}>{nb?"Prøv filsletting igjen":"Retry file deletion"}</Button></p>}{retryCleanup.isError&&<p role="alert">{cvError(retryCleanup.error.message,locale)}</p>}
 <Sheet open={creating} onOpenChange={open=>{if(!create.isPending)setCreating(open);}}><SheetContent className="document-workspace-sheet" closeLabel={nb?"Lukk":"Close"}><SheetHeader><SheetTitle>{nb?"Bygg et CV-utkast":"Build a CV draft"}</SheetTitle><SheetDescription>{nb?"Ingen AI-kall. Velg hva du vil fremheve. Etter lagring får du en full forhåndsvisning før eksport.":"No AI call. Choose what to highlight. Saving opens a full preview before export."}</SheetDescription></SheetHeader><form className="cv-builder" onSubmit={event=>{event.preventDefault();create.mutate();}}>
 <Card><CardHeader><h3>{nb?"1. Navn og presentasjon":"1. Name and introduction"}</h3></CardHeader><CardContent><label>{nb?"Navn på CV-versjonen":"CV version title"}<Input value={title} maxLength={200} required onChange={e=>setTitle(e.target.value)}/></label>{([['name',nb?'Fullt navn':'Full name'],['headline',nb?'Overskrift / rolle':'Headline / role'],['email',nb?'E-post':'Email'],['phone',nb?'Telefon':'Phone'],['location',nb?'Bosted':'Location']] as const).map(([key,label])=><label key={key}>{label}<Input value={identity[key]} required={key==='name'} maxLength={key==='phone'?100:200} onChange={e=>setIdentity({...identity,[key]:e.target.value})}/></label>)}<label>{nb?"Kort presentasjon (din egen tekst)":"Short introduction (your own text)"}<Textarea value={identity.summary} maxLength={1500} onChange={e=>setIdentity({...identity,summary:e.target.value})}/></label><div className="cv-form-row"><label>{nb?"Språk i eksport":"Export language"}<select value={language} onChange={e=>setLanguage(e.target.value as Locale)}><option value="nb">Norsk</option><option value="en">English</option></select></label><label>{nb?"Knytt til stilling (valgfritt)":"Link to job (optional)"}<select value={job} onChange={e=>setJob(e.target.value)}><option value="">{nb?"Generell CV":"General CV"}</option>{jobs.data?.map(j=><option key={j.id} value={j.id}>{j.content.title}</option>)}</select></label></div></CardContent></Card>
 <Card><CardHeader><h3>{nb?"2. Velg bekreftet erfaring":"2. Choose confirmed experience"}</h3><p className="hint">{nb?"Teksten brukes slik du har bekreftet den. Velg inntil 30 kompetansepunkter og 20 historikkpunkter.":"Wording is used as you confirmed it. Choose up to 30 competencies and 20 career entries."}</p></CardHeader><CardContent>{confirmedClaims.length===0&&confirmedEntries.length===0&&<p>{nb?"Bekreft erfaring i profilen først.":"Confirm experience in your profile first."}</p>}<div className="cv-selection-list">{confirmedClaims.map(c=><label key={c.id}><Input type="checkbox" data-slot="checkbox" checked={selectedClaims.includes(c.id)} onChange={()=>toggle(c.id,selectedClaims,setSelectedClaims)} disabled={!selectedClaims.includes(c.id)&&selectedClaims.length>=30}/><span><strong>{c.skill}</strong><span>{c.statement}</span><small>{c.context}</small></span></label>)}{confirmedEntries.map(e=><label key={e.id}><Input type="checkbox" data-slot="checkbox" checked={selectedEntries.includes(e.id)} onChange={()=>toggle(e.id,selectedEntries,setSelectedEntries)} disabled={!selectedEntries.includes(e.id)&&selectedEntries.length>=20}/><span><strong>{e.content.title} · {e.content.organization}</strong><span>{e.content.description}</span><small>{entryPeriod(e.content,locale)}</small></span></label>)}</div><p className="hint">{selectedClaims.length+selectedEntries.length} {nb?"punkter valgt":"items selected"}</p></CardContent></Card>
 {create.isError&&<p role="alert" className="notice">{cvError(create.error.message,locale)}</p>}<Button type="submit" disabled={create.isPending||!title.trim()||!identity.name.trim()||selectedClaims.length+selectedEntries.length===0||claims.isPending||entries.isPending||jobs.isError}>{create.isPending?(nb?"Lagrer …":"Saving …"):(nb?"3. Lagre og forhåndsvis":"3. Save and preview")}</Button></form></SheetContent></Sheet>
 <Sheet open={selected!==null} onOpenChange={open=>{if(!open&&!approve.isPending)setSelected(null);}}><SheetContent className="document-workspace-sheet cv-preview-sheet" closeLabel={nb?"Lukk":"Close"}>{selected&&<><SheetHeader><SheetTitle>{selected.title}</SheetTitle><SheetDescription>{selected.status==="APPROVED"?(nb?"Godkjent og låst versjon. Nedlasting bruker alltid de samme filene.":"Approved and locked version. Downloads always use the same files."):(nb?"Kontroller navn, ordlyd og erfaring før du godkjenner eksport.":"Check your name, wording and experience before approving export.")}</SheetDescription></SheetHeader><div className="cv-paper" lang={selected.content.locale}><h2>{selected.content.identity.name}</h2><h3>{selected.content.identity.headline}</h3><p className="cv-contact">{[selected.content.identity.email,selected.content.identity.phone,selected.content.identity.location].filter(Boolean).join(" · ")}</p>{selected.content.identity.summary&&<p>{selected.content.identity.summary}</p>}{selected.content.entries.map(e=><section key={e.id}><h4>{entryKinds[selected.content.locale][e.content.kind]}</h4><h3>{e.content.title} · {e.content.organization}</h3><p>{entryPeriod(e.content,selected.content.locale)}</p>{e.content.client&&<p>{selected.content.locale==='nb'?'Kunde':'Client'}: {e.content.client}</p>}{e.content.deliveryRole&&<p>{selected.content.locale==='nb'?'Leveranserolle':'Delivery role'}: {e.content.deliveryRole}</p>}<p>{e.content.description}</p></section>)}{selected.content.claims.length>0&&<section><h4>{selected.content.locale==='nb'?'Kompetanse':'Competencies'}</h4>{selected.content.claims.map(c=><div key={c.id}><h3>{c.skill}</h3><p>{c.statement}</p><p className="hint">{c.context}</p></div>)}</section>}</div><p className="hint">{nb?"Forhåndsvisningen viser samme innhold som eksporten. Linjeskift og sideinndeling kan variere. Kildenotater eksporteres ikke.":"The preview shows the same content as the export. Line breaks and pagination may differ. Source notes are not exported."}</p><details className="source-evidence"><summary>{nb?"Se grunnlaget for erfaringen":"View experience sources"}</summary>{selected.content.claims.map(c=><div key={c.id}><strong>{c.skill}</strong><p>{c.sourceNote}</p>{c.sourceQuote&&<blockquote>{c.sourceQuote}</blockquote>}</div>)}{selected.content.entries.map(e=><p key={e.id}>{e.content.title}: {e.content.sourceNote}</p>)}</details>
 {selected.stale&&<p className="notice">{nb?"Utkastet bruker erfaring som er endret. Lag et nytt utkast før eksport.":"This draft uses changed experience. Create a new draft before exporting."}</p>}{approve.isError&&<p role="alert">{cvError(approve.error.message,locale)}</p>}{download.isError&&<p role="alert">{cvError(download.error.message,locale)}</p>}
 <div className="document-toolbar"><Button variant="outline" disabled={approve.isPending} onClick={()=>{const previous=selected;setSelected(null);openNew();setTitle(previous.title);setIdentity({...previous.content.identity});setLanguage(previous.content.locale);setJob(jobs.data?.some(j=>j.id===previous.content.jobId)?previous.content.jobId??"":"");setSelectedClaims(previous.content.claims.filter(c=>confirmedClaims.some(current=>current.id===c.id&&current.revision===c.revision)).map(c=>c.id));setSelectedEntries(previous.content.entries.filter(e=>confirmedEntries.some(current=>current.id===e.id&&current.revision===e.revision)).map(e=>e.id));}}>{nb?"Lag revidert utkast":"Create revised draft"}</Button>{selected.status==="DRAFT"?<Button disabled={selected.stale||approve.isPending} onClick={()=>approve.mutate(selected)}><Check size={16}/>{approve.isPending?(nb?"Lager filer …":"Generating files …"):(nb?"Godkjenn og lag DOCX + PDF":"Approve and generate DOCX + PDF")}</Button>:(["pdf","docx"] as const).map(format=><Button key={format} variant="outline" disabled={download.isPending} onClick={()=>download.mutate({version:selected,format})}><Download size={16}/>{nb?"Last ned":"Download"} {format.toUpperCase()}</Button>)}<Button variant="ghost" disabled={approve.isPending} onClick={()=>{remove.reset();setDeleting(selected);}}><Trash2 size={16}/>{nb?"Slett versjon":"Delete version"}</Button></div></>}</SheetContent></Sheet>
 <Dialog open={deleting!==null} onOpenChange={open=>{if(!open&&!remove.isPending)setDeleting(null);}}><DialogContent><DialogHeader><DialogTitle>{nb?"Slett CV-versjonen?":"Delete this CV version?"}</DialogTitle><DialogDescription>{nb?"Denne versjonen og eksportfilene slettes. Originaldokumenter og bekreftet erfaring beholdes. Versjoner brukt i en søknad må frikobles først.":"This version and its export files are deleted. Original documents and confirmed experience remain. Versions used in an application must be unlinked first."}</DialogDescription></DialogHeader>{remove.isError&&<p role="alert">{cvError(remove.error.message,locale)}</p>}<DialogFooter><Button variant="outline" disabled={remove.isPending} onClick={()=>setDeleting(null)}>{nb?"Avbryt":"Cancel"}</Button><Button disabled={remove.isPending} onClick={()=>deleting&&remove.mutate(deleting)}>{nb?"Slett versjon":"Delete version"}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
