"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, ScanSearch, FileCheck2, Bookmark, ShieldCheck, CircleCheck } from "lucide-react";
import { isDocumentList } from "../lib/documents";
import { WorkspaceJourneyGuide } from "./workspace-journey-guide";
import { isProfile } from "../lib/profile";
import { isSavedJobs } from "../lib/saved-jobs";
import { isClaimList } from "../lib/claims";
import type { Locale } from "../lib/translations";
import { Card, CardHeader, CardContent } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
export function DashboardWorkspace({ locale }: { locale: Locale }) {
 const nb = locale === "nb";
 const profile = useQuery({ queryKey: ["private-profile"], gcTime: 0, retry: false, queryFn: async () => { const response = await fetch("/api/profile/me", { cache: "no-store" }); const value = await response.json(); if (response.status === 404 && value?.code === "PROFILE_NOT_CREATED") return null; if (!response.ok || !isProfile(value)) throw new Error("PROFILE_UNAVAILABLE"); return value; } });
 const claims = useQuery({ queryKey: ["private-claims"], gcTime: 0, retry: false, enabled: !!profile.data, queryFn: async () => { const response = await fetch("/api/profile/me/claims", { cache: "no-store" }); const value = await response.json(); if (!response.ok || !isClaimList(value)) throw new Error("CLAIM_UNAVAILABLE"); return value; } });
 const jobs = useQuery({ queryKey: ["private-saved-jobs"], gcTime: 0, retry: false, enabled: !!profile.data, queryFn: async () => { const response = await fetch("/api/profile/me/jobs", { cache: "no-store" }); const value = await response.json(); if (!response.ok || !isSavedJobs(value)) throw new Error("SAVED_JOB_UNAVAILABLE"); return value; } });
 const documents = useQuery({ queryKey: ["private-documents"], gcTime: 0, retry: false, enabled: !!profile.data, queryFn: async () => { const response = await fetch("/api/profile/me/documents", { cache: "no-store" }); const value = await response.json(); if (!response.ok || !isDocumentList(value)) throw new Error("DOCUMENT_UNAVAILABLE"); return value; } });
 const confirmed = claims.data?.filter(claim => claim.status === "CONFIRMED").length ?? 0; const review = claims.data?.filter(claim => ["UNVERIFIED", "INFERRED"].includes(claim.status)).length ?? 0;
 const explore = { title: nb ? "Utforsk ditt arbeidsområde" : "Explore your workspace", text: nb ? "Åpne dokumentene eller stillingene dine. Vi foreslår neste steg når grunnlaget er hentet." : "Open your documents or saved jobs. We suggest a next step once your information is available.", href: "/career/profile", action: nb ? "Åpne kandidatprofil" : "Open candidate profile" };
 const next = !profile.data ? { title: nb ? "Start med din kandidatprofil" : "Start with your candidate profile", text: nb ? "Lagre navn og språk. Deretter kan du laste opp CV og kompetansedokumenter." : "Save your name and language. Then upload your CV and competency documents.", href: "/career/profile", action: nb ? "Opprett profil" : "Create profile" }
 : claims.isPending || claims.isError ? explore
 : review > 0 ? { title: nb ? "Se gjennom kompetanseforslagene" : "Review your competency proposals", text: nb ? `${review} punkter venter på gjennomgang. Kontroller beskrivelsene; godkjente og avviste punkter holdes utenfor køen.` : `${review} items await review. Check the descriptions; approved and rejected items stay outside the queue.`, href: "/career/profile#profile-competencies", action: nb ? "Gjennomgå kompetanse" : "Review competencies" }
 : confirmed === 0 ? documents.isPending || documents.isError ? explore
 : documents.data?.length ? { title: nb ? "La dokumentene bygge profilen" : "Let your documents build your profile", text: nb ? "Dokumentene er lagret. Åpne dem, kontroller at teksten er lest og start en AI-analyse med din godkjenning." : "Your documents are saved. Open them, check the extracted text and approve an AI analysis.", href: "/career/profile#profile-documents", action: nb ? "Gjennomgå dokumentene" : "Review documents" }
 : { title: nb ? "Start med CV og erfaring" : "Start with your CV and experience", text: nb ? "Last opp CV og gjerne prosjektbeskrivelser, attester eller kursbevis. Vi finner og strukturerer erfaringen; du kan rette innholdet." : "Upload your CV and optional project descriptions, work or course certificates. We find and structure the experience; you can correct it.", href: "/career/profile#profile-documents", action: nb ? "Last opp dokumenter" : "Upload documents" }
 : jobs.isPending || jobs.isError ? explore
 : jobs.data?.length ? { title: nb ? "Sammenlign mulighetene dine" : "Compare your opportunities", text: nb ? "Åpne en lagret stilling og gjennomfør personlig match. Velg «Søk på stillingen» for hjelp til å tilspisse CV-teksten." : "Open a saved job and run a personal match. Choose Apply for this job for help tailoring your CV wording.", href: "/jobs/saved", action: nb ? "Åpne mine stillinger" : "Open my saved jobs" }
 : { title: nb ? "Finn din neste mulighet" : "Find your next opportunity", text: nb ? "Analyser en annonse, lagre den og sammenlign kravene med erfaringen i profilen din." : "Analyze a job, save it and compare its criteria with your profile evidence.", href: "/jobs/analyze", action: nb ? "Analyser en stilling" : "Analyze a job" };

 return <section className="dashboard-workspace" aria-label={nb ? "Din jobbsøking" : "Your job search"}>
 {profile.isPending ? <p role="status">{nb ? "Henter ditt arbeidsområde …" : "Loading your workspace …"}</p> : profile.isError ? <Card><CardContent><p role="alert">{nb ? "Kunne ikke hente profilen din." : "Could not load your profile."}</p><Button variant="outline" onClick={() => void profile.refetch()}>{nb ? "Prøv igjen" : "Try again"}</Button></CardContent></Card> : <Card className="dashboard-next"><CardContent><div><Badge variant="secondary">{nb ? "DITT NESTE STEG" : "YOUR NEXT STEP"}</Badge><h2>{next.title}</h2><p>{next.text}</p><Button asChild><Link href={next.href}>{next.action}<ArrowRight size={17}/></Link></Button>{profile.data && next.href!=="/career/profile#profile-documents" && <Button asChild variant="ghost" size="sm"><Link href="/career/profile#profile-documents"><FileCheck2 size={16}/>{nb?"Last opp flere dokumenter":"Upload more documents"}</Link></Button>}</div><div className="dashboard-path" aria-label={nb ? "Foreslått rekkefølge" : "Suggested sequence"}>{[nb ? "Profil og erfaring" : "Profile and experience", nb ? "Stillinger og krav" : "Jobs and requirements", nb ? "Personlig sammenligning" : "Personal comparison"].map((title,index) => <div key={title}><span>{index + 1}</span><p>{title}</p></div>)}</div></CardContent></Card>}
 <WorkspaceJourneyGuide locale={locale}/>
 {profile.data && <div className="dashboard-stats">{[
 { icon: FileCheck2, count: documents.isError ? "—" : documents.isPending ? "…" : documents.data?.length ?? 0, title: nb ? "Dokumenter" : "Documents", href: "/career/profile#profile-documents" },
 { icon: ShieldCheck, count: claims.isError ? "—" : claims.isPending ? "…" : confirmed, title: nb ? "Bekreftede kompetansepunkter" : "Confirmed competencies", href: "/career/profile#profile-competencies" },
 { icon: FileCheck2, count: claims.isError ? "—" : claims.isPending ? "…" : review, title: nb ? "Punkter til gjennomgang" : "Items to review", href: "/career/profile#profile-competencies" },
 { icon: Bookmark, count: jobs.isError ? "—" : jobs.isPending ? "…" : jobs.data?.length ?? 0, title: nb ? "Lagrede stillinger" : "Saved jobs", href: "/jobs/saved" },
 ].map(({ icon: Icon, count, title, href }) => <Link key={title} href={href} className="dashboard-stat"><Icon size={22}/><strong>{count}</strong><span>{title}</span><ArrowRight size={15}/></Link>)}</div>}
 {(claims.isError || jobs.isError || documents.isError) && <p role="alert" className="notice">{nb ? "Noen tall kunne ikke hentes. Åpne profilen eller stillingsbiblioteket for å prøve igjen." : "Some counts could not be loaded. Open your profile or saved jobs to try again."}</p>}
 <div className="dashboard-action-grid">{[
 { icon: FileCheck2, title: nb ? "Gjør CV-en klar" : "Prepare your CV", text: nb ? "Velg bekreftet erfaring, gjennomgå utkastet og godkjenn DOCX og PDF." : "Choose confirmed experience, review the draft and approve DOCX and PDF.", href: "/cv", action: nb ? "Åpne mine CV-er" : "Open my CVs" },
 { icon: Bookmark, title: nb ? "Følg opp søknadene" : "Track your applications", text: nb ? "Bevar CV-en du sendte, registrer status og planlegg neste oppfølging." : "Preserve the CV you submitted, record status and plan your next follow-up.", href: "/applications", action: nb ? "Åpne søknader" : "Open applications" },
 { icon: ScanSearch, title: nb ? "Forstå en stilling" : "Understand a job", text: nb ? "Se rolle, bedrift, frist og krav. Bruk lenke eller annonsetekst." : "Review the role, employer, deadline and requirements. Use a link or advertisement text.", href: "/jobs/analyze", action: nb ? "Åpne stillingsanalyse" : "Open job analysis" },
 { icon: FileCheck2, title: nb ? "Bygg din kandidatprofil" : "Build your candidate profile", text: nb ? "Samle dokumenter, erfaring og kompetanse. Du avgjør hva som er bekreftet." : "Collect documents, experience and competencies. You decide what is confirmed.", href: "/career/profile", action: nb ? "Åpne kandidatprofil" : "Open candidate profile" },
 ].map(({ icon: Icon, title, text, href, action }) => <Card key={title}><CardHeader><Icon size={24}/><h2>{title}</h2><p>{text}</p></CardHeader><CardContent><Button asChild variant="outline"><Link href={href}>{action}<ArrowRight size={16}/></Link></Button></CardContent></Card>)}</div>
 {jobs.data && jobs.data.length > 0 && <section className="dashboard-recent"><div className="workspace-heading"><h2>{nb ? "Sist lagrede muligheter" : "Recently saved opportunities"}</h2><Link href="/jobs/saved">{nb ? "Se alle" : "View all"}<ArrowRight size={15}/></Link></div>{jobs.data.slice(0,3).map(job => <Link key={job.id} href="/jobs/saved" className="recent-job"><Bookmark size={18}/><div><strong>{job.content.title}</strong><span>{job.content.facts.find(f => f.kind === "LOCATION")?.value ?? (nb ? "Sted ikke oppgitt" : "Location not provided")}</span></div><ArrowRight size={17}/></Link>)}</section>}
 <p className="dashboard-note"><CircleCheck size={17}/>{nb ? "Oversikten bruker lagrede dokumenter og bekreftede opplysninger. Nye AI-analyser krever din godkjenning." : "This overview uses saved documents and confirmed evidence. New AI analyses require your approval."}</p></section>;
}
