"use client";
import {useState} from "react";
import {useMutation} from "@tanstack/react-query";
import {CircleCheck,CircleAlert,Circle,ClipboardCheck} from "lucide-react";
import {Button} from "./ui/button";
import {Card,CardContent} from "./ui/card";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "./ui/sheet";
import {isDocumentCheckReport} from "../lib/document-checks";
import type {CareerDocument} from "../lib/documents";
import type {Locale} from "../lib/translations";
const messages:Record<string,[string,string]>={ORIGINAL_MISSING:["Originalfilen kunne ikke åpnes.","Original file could not be opened."],ORIGINAL_CHANGED:["Originalfilen avviker fra lagret kontrollsum.","Original differs from its saved checksum."],ORIGINAL_UNCHANGED:["Originalfilen er intakt.","Original file is intact."],TEXT_EMPTY:["Ingen lesbar tekst. Prøv OCR eller en tekstbasert kopi.","No readable text. Try OCR or a text-based copy."],OCR_REQUIRES_REVIEW:["OCR-tekst finnes. Kontroller den visuelt mot originalen.","OCR text exists. Check it visually against the original."],TEXT_LIMIT_REACHED:["Tekstgrensen er nådd. Deler av dokumentet kan være utelatt.","Text limit reached. Parts of this document may be omitted."],READER_UNAVAILABLE:["Originalen kunne ikke leses på nytt. Lagret tekst er beholdt.","Original could not be reread. Stored text is retained."],READER_DIFFERENT:["Ny lesing ga annen tekst. Åpne dokumentet og vurder å lese det på nytt.","New reading differs. Open the document and consider rereading."],TEXT_READABLE:["Lagret tekst stemmer med en ny lokal lesing.","Stored text matches a fresh local reading."],NOT_ANALYZED:["Ingen lagret AI-analyse ennå.","No stored AI analysis yet."],NOT_INCLUDED:["Dokumentet var ikke med i den samlede analysen.","Document was not included in the combined analysis."],EVIDENCE_CHANGED:["Ett eller flere kildesitater finnes ikke i dagens tekst. Kontroller analysen.","Some source quotes are absent from the current text. Review the analysis."],NO_SUGGESTIONS:["Ingen kildebelagte forslag fra dette dokumentet. Kontroller teksten og prøv et annet utdrag.","No sourced suggestions from this document. Check the text and try another excerpt."],PARTIAL_ANALYSIS:["Kildesitatene finnes i teksten. Analysen dekker bare et utvalg.","Source quotes exist in the text. Analysis covers only a selection."],EVIDENCE_SUPPORTED:["Kildesitatene finnes i den lagrede teksten. Vurder fortsatt om tolkningen stemmer.","Source quotes exist in stored text. Still review whether the interpretation is correct."]};
export function DocumentChecks({documents,csrfToken,locale,onOpen,onAuthRequired}:{documents:CareerDocument[];csrfToken:string;locale:Locale;onOpen:(doc:CareerDocument)=>void;onAuthRequired:()=>void}){
 const nb=locale==="nb";const [open,setOpen]=useState(false);
 const check=useMutation({retry:false,mutationFn:async()=>{const r=await fetch("/api/profile/me/documents/check",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-TOKEN":csrfToken},body:"{}"});const v=await r.json();if(!r.ok)throw new Error(v.code??"DOCUMENT_UNAVAILABLE");if(!isDocumentCheckReport(v))throw new Error("DOCUMENT_UNAVAILABLE");return v;},onError:e=>{if(e.message==="AUTH_REQUIRED")onAuthRequired();}});
 return <><Button variant="outline" className="mt-4" onClick={()=>{setOpen(true);check.mutate();}} disabled={check.isPending||!documents.length}><ClipboardCheck size={16}/>{nb?"Kontroller dokumentene":"Check documents"}</Button><Sheet open={open} onOpenChange={setOpen}><SheetContent className="document-workspace-sheet" closeLabel={nb?"Lukk":"Close"}><SheetHeader><SheetTitle>{nb?"Dokumentkontroll":"Document check"}</SheetTitle><SheetDescription>{nb?"Lokal kontroll av originalfil, lesbar tekst og lagrede AI-kildesitater. Ingen nye AI-kall; ingenting endres. Grønne lys bekrefter tekniske kontroller, ikke at all kompetanse er funnet eller tolket riktig.":"Local checks of originals, readable text and stored AI source quotes. No new AI call or changes. Green indicators confirm technical checks, not exhaustive or correct competency interpretation."}</SheetDescription></SheetHeader>{check.isPending&&<p role="status">{nb?"Kontrollerer originaler og sitater …":"Checking originals and quotes …"}</p>}{check.isError&&<p role="status">{nb?"Kontrollen kunne ikke fullføres. Dokumentene er beholdt; prøv igjen.":"The check could not finish. Documents are retained; try again."}</p>}{check.data&&<><p className="hint">{nb?"Kontrollert: ":"Checked: "}{new Date(check.data.checkedAt).toLocaleString(locale)}</p>{check.data.documents.map(v=>{const document=documents.find(d=>d.id===v.documentId);return <Card key={v.documentId}><CardContent><h3>{document?.originalName??(nb?"Dokument":"Document")}</h3><p className="hint">{v.characters.toLocaleString(locale)} {nb?"tegn tilgjengelig":"characters available"}</p><ul className="document-check-list">{v.checks.map(c=><li key={c.kind} data-state={c.state}>{c.state==="PASS"?<CircleCheck size={17}/>:c.state==="MISSING"?<Circle size={17}/>:<CircleAlert size={17}/>}<div><strong>{({ORIGINAL:nb?"Original":"Original",TEXT:nb?"Tekstlesing":"Text reading",INDIVIDUAL_AI:nb?"Dokumentanalyse":"Individual analysis",COMBINED_AI:nb?"Samlet analyse":"Combined analysis"})[c.kind]}</strong><p>{messages[c.code][nb?0:1]}{c.items>0&&` (${c.items} ${nb?"punkter":"items"})`}</p></div></li>)}</ul>{document&&<Button variant="outline" onClick={()=>{setOpen(false);onOpen(document);}}>{nb?"Åpne dokumentet":"Open document"}</Button>}</CardContent></Card>;})}</>}<Button className="mt-4" variant="outline" disabled={check.isPending} onClick={()=>check.mutate()}>{nb?"Kontroller igjen":"Check again"}</Button></SheetContent></Sheet></>;
}
