"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Upload, FileText, Download, Star, Trash2, RefreshCw, ScanText, CheckCircle2, AlertCircle } from "lucide-react";
import { Card, CardContent, CardHeader } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Badge } from "./ui/badge";
import { Alert, AlertDescription } from "./ui/alert";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "./ui/sheet";
import { isDocument, isDocumentList, isDocumentDetail, type CareerDocument } from "../lib/documents";
import { isClaim, type CompetencyClaim } from "../lib/claims";
import { DocumentChecks } from "./document-checks";
import { DocumentWorkflow } from "./document-workflow";
import type { Locale } from "../lib/translations";
const copy = {
  nb: {
    linked: "Erfaringen finnes fra før. Kilden er knyttet til samme punkt; bekreftelsesstatusen er beholdt.", title: "CV og dokumenter", intro: "Last opp CV-er, attester, kursbevis og andre kompetansedokumenter som DOCX, PDF, UTF-8 tekst eller Markdown. Originalen beholdes. Tekstuttrekk skjer lokalt; AI-analyse med Groq er et eget valg etter at du har kontrollert teksten.", file: "Dokumentfil", language: "Dokumentspråk", upload: "Last opp dokument", busy: "Behandler …", loading: "Henter dokumenter …", empty: "Bygg dokumentgrunnlaget ditt. Start med CV-en og legg til attester og kursbevis.", open: "Analyser dokumentet", download: "Last ned original", master: "Bruk som master-CV", masterLabel: "Master-CV", remove: "Slett", close: "Lukk", cancel: "Avbryt", text: "Tekst hentet fra dokumentet", select: "Kontroller dokumentgrunnlaget, bygg profilen med AI og rediger forslagene før du bekrefter dem.", selected: "Bruk valgt tekst", quote: "Valgt kildesitat", skill: "Kompetanse", statement: "Hva gjorde du selv?", context: "Prosjekt eller arbeidsforhold", save: "Lagre som ubekreftet kompetanse", review: "Opplysningen krever egen bekreftelse i kompetansedelen etter lagring.", noText: "Ingen lesbar tekst funnet. Dette kan være en skannet PDF. Prøv lokal OCR nedenfor, eller last opp en kopi med markerbar tekst.", deleteTitle: "Slett original CV?", deleteHint: "Originalfilen og dokumentteksten slettes. Kompetansepunkter og historikk som du har opprettet beholdes, inkludert kildesitat. Slett disse separat hvis du vil fjerne dem.", deleteAction: "Slett dokumentet permanent", uploaded: "Dokumentet er lagret. Åpne teksten for å hente kompetanse fra det.", saved: "Kompetansen er lagret som ubekreftet. Gå til kompetanseoversikten for å vurdere den.", masterSaved: "Master-CV er valgt. Dette endrer ikke originalfilen.", deleted: "Dokumentet er slettet.", reread: "Originalen er lest på nytt. Kontroller teksten før en ny AI-analyse. Tidligere kompetanseopplysninger beholdes; endret dokumenttekst fjerner gamle analyser.", refresh: "Hent dokumenter på nytt", limits: "DOCX / PDF / TXT / Markdown · maks 5 MB og 20 dokumenter. Uttrekket gjenskaper ikke layouten. Se Mine CV-er for gjennomgått standardeksport.",
    errors: { CLAIM_EVIDENCE_LIMIT: "Dette kompetansepunktet har allerede 100 dokumentkilder.", DOCUMENT_AI_NO_TEXT: "Den nye lesingen ga ingen tekst. Tidligere tekst er beholdt. Prøv OCR eller bruk en kopi med markerbar tekst.", DOCUMENT_OCR_UNAVAILABLE: "Lokal OCR er ikke tilgjengelig. Installer Tesseract på backend-maskinen og kontroller språkpakken. Originalen er beholdt.", DOCUMENT_OCR_TIMEOUT: "OCR tok for lang tid. Prøv en mindre PDF. Originalen er beholdt.", DOCUMENT_OCR_TOO_LARGE: "OCR støtter maks 10 PDF-sider og begrenset bildestørrelse. Del opp skannen.", DOCUMENT_UNAVAILABLE: "Dokumenttjenesten er utilgjengelig. Prøv igjen.", PROFILE_UNAVAILABLE: "Tjenesten er utilgjengelig. Prøv igjen.", DOCUMENT_TYPE: "Velg en DOCX-, PDF-, UTF-8 TXT- eller Markdown-fil.", DOCUMENT_INVALID: "Dokumentet kunne ikke leses. Kontroller filtype og innhold.", DOCUMENT_TOO_LARGE: "Dokumentet overskrider grensene: 5 MB, 100 PDF-sider eller 60 000 teksttegn.", DOCUMENT_ENCRYPTED: "Passordbeskyttet PDF støttes ikke. Bruk en ubeskyttet kopi.", DOCUMENT_QUOTE_INVALID: "Velg et sitat som finnes nøyaktig i den hentede teksten, maks 1000 tegn.", DOCUMENT_NOT_FOUND: "Dokumentet finnes ikke eller er utilgjengelig.", DOCUMENT_LIMIT: "Pilotgrensen på 20 dokumenter er nådd.", DOCUMENT_ANALYSIS_CONFLICT: "Analysen er erstattet. Åpne dokumentet på nytt og velg forslaget fra siste analyse.", DOCUMENT_BUSY: "Et dokument behandles allerede. Prøv igjen etterpå.", CLAIM_INVALID: "Kontroller kompetanse og kontekst.", CLAIM_LIMIT: "Pilotgrensen på 100 kompetansepunkter er nådd.", ACCESS_DENIED: "Endringen ble avvist. Last siden på nytt.", AUTH_REQUIRED: "Sesjonen er utløpt. Logg inn igjen.", PROFILE_NOT_CREATED: "Lagre basisprofilen først.", PROFILE_DISABLED: "Profillagring er ikke aktivert." },
  },
  en: {
    linked: "This experience already exists. The source is linked to the same item; its review status is retained.", title: "CV and documents", intro: "Upload documents, employment attestations, certificates and other competency documents as DOCX, PDF, UTF-8 text or Markdown. The original is retained. Text extraction is local; Groq AI analysis is a separate choice after reviewing the text.", file: "Document file", language: "Document language", upload: "Upload document", busy: "Processing …", loading: "Loading documents …", empty: "Build your document sources. Start with your CV, then add certificates and employment attestations.", open: "Analyze document", download: "Download original", master: "Use as master CV", masterLabel: "Master CV", remove: "Delete", close: "Close", cancel: "Cancel", text: "Text extracted from the document", select: "Review document sources, build your profile with AI and edit proposals before confirming them.", selected: "Use selected text", quote: "Selected source quote", skill: "Competency", statement: "What did you personally do?", context: "Project or employment", save: "Save as unverified competency", review: "The statement needs a separate confirmation in the competency section after saving.", noText: "No readable text found. This may be a scanned PDF. Try local OCR below, or upload a copy with selectable text.", deleteTitle: "Delete the original CV?", deleteHint: "The original file and document text will be deleted. Competencies and history you created are retained, including source quotes. Delete these separately if you want to remove them.", deleteAction: "Permanently delete document", uploaded: "Document saved. Open its text to record competencies from it.", saved: "Competency saved as unverified. Review it in the competency overview.", masterSaved: "Master CV selected. This does not change the original file.", deleted: "Document deleted.", reread: "Original reread. Check the text before another AI analysis. Existing competencies are retained; changed document text removes old analyses.", refresh: "Reload documents", limits: "DOCX / PDF / TXT / Markdown · max 5 MB and 20 documents. Extraction does not recreate the layout. Approved CV export uses a separate standard template.",
    errors: { CLAIM_EVIDENCE_LIMIT: "This competency already has 100 document sources.", DOCUMENT_AI_NO_TEXT: "The new reading found no text. Previous text is retained. Try OCR or a copy with selectable text.", DOCUMENT_OCR_UNAVAILABLE: "Local OCR is unavailable. Install Tesseract on the backend machine and check its language pack. The original is retained.", DOCUMENT_OCR_TIMEOUT: "OCR timed out. Try a smaller PDF. The original is retained.", DOCUMENT_OCR_TOO_LARGE: "OCR supports up to 10 PDF pages and bounded image sizes. Split the scan.", DOCUMENT_UNAVAILABLE: "The document service is unavailable. Try again.", PROFILE_UNAVAILABLE: "The service is unavailable. Try again.", DOCUMENT_TYPE: "Choose a DOCX, PDF, UTF-8 TXT or Markdown file.", DOCUMENT_INVALID: "The document could not be read. Check the file type and content.", DOCUMENT_TOO_LARGE: "The document exceeds the limits: 5 MB, 100 PDF pages or 60,000 text characters.", DOCUMENT_ENCRYPTED: "Password-protected PDFs are not supported. Use an unprotected copy.", DOCUMENT_QUOTE_INVALID: "Select a quote found exactly in the extracted text, up to 1000 characters.", DOCUMENT_NOT_FOUND: "The document does not exist or is unavailable.", DOCUMENT_LIMIT: "The pilot limit of 20 documents has been reached.", DOCUMENT_ANALYSIS_CONFLICT: "The analysis was replaced. Reopen the document and choose a suggestion from the latest analysis.", DOCUMENT_BUSY: "Another document is being processed. Try again afterwards.", CLAIM_INVALID: "Check the competency and context.", CLAIM_LIMIT: "The pilot limit of 100 competency statements has been reached.", ACCESS_DENIED: "The change was rejected. Reload the page.", AUTH_REQUIRED: "Your session expired. Sign in again.", PROFILE_NOT_CREATED: "Save the basic profile first.", PROFILE_DISABLED: "Profile storage is not enabled." },
  },
};
type SourceDraft = { skill: string; statement: string; context: string; quote: string; analysisId?: string };
type Command = { kind: "upload"; file: File; language: Locale } | { kind: "master" | "delete"; document: CareerDocument } | { kind: "reread"; document: CareerDocument; ocr: boolean } | { kind: "claim"; document: CareerDocument; content: SourceDraft };
const blank: SourceDraft = { skill: "", statement: "", context: "", quote: "" };
export function DocumentPanel({ locale, csrfToken, onAuthRequired }: { locale: Locale; csrfToken: string; onAuthRequired: () => void }) {
  const t = copy[locale]; const cache = useQueryClient(); const source = useRef<HTMLTextAreaElement>(null); const fileField = useRef<HTMLInputElement>(null);
  const [readingRevision, setReadingRevision] = useState(0);
  const [file, setFile] = useState<File | null>(null); const [language, setLanguage] = useState<Locale>(locale);
  const [modal, setModal] = useState<{ kind: "read" | "delete" | "collection"; document: CareerDocument } | null>(null);
  const [draft, setDraft] = useState<SourceDraft>(blank); const [notice, setNotice] = useState<"uploaded" | "saved" | "masterSaved" | "deleted" | "reread" | "linked" | null>(null);
  async function json(response: Response) { if (response.status === 401) onAuthRequired(); const value = await response.json(); if (!response.ok) throw new Error(typeof value?.code === "string" ? value.code : "DOCUMENT_UNAVAILABLE"); return value as unknown; }
  const list = useQuery({ queryKey: ["private-documents"], gcTime:0, refetchOnReconnect:false, queryFn: async () => { const value = await json(await fetch("/api/profile/me/documents", { cache:"no-store" })); if (!isDocumentList(value)) throw new Error("DOCUMENT_UNAVAILABLE"); return value; } });
  const collection = useQuery({ queryKey:["private-document-collection-text"], enabled:modal?.kind === "collection", gcTime:0, retry:false, refetchOnReconnect:false, queryFn:async () => Promise.all((list.data ?? []).map(async document => { const value = await json(await fetch(`/api/profile/me/documents/${document.id}`, { cache:"no-store" })); if (!isDocumentDetail(value)) throw new Error("DOCUMENT_UNAVAILABLE"); return value; })) });
  const selectedId = modal?.kind === "read" ? modal.document.id : undefined;
  const detail = useQuery({ queryKey:["private-document-detail", selectedId], enabled:!!selectedId, gcTime:0, refetchOnReconnect:false, queryFn:async () => { const value = await json(await fetch(`/api/profile/me/documents/${selectedId}`, { cache:"no-store" })); if (!isDocumentDetail(value)) throw new Error("DOCUMENT_UNAVAILABLE"); return value; } });
  useEffect(() => { if (draft.quote && detail.data) window.document.querySelector(".manual-source-tools")?.setAttribute("open", ""); }, [draft.quote, detail.data]);
  const mutation = useMutation({ mutationFn:async (command: Command) => {
    let body: BodyInit | undefined; const headers = new Headers({ "X-CSRF-TOKEN":csrfToken });
    if (command.kind === "upload") {
      if (!/\.(docx|pdf|txt|md)$/i.test(command.file.name)) throw new Error("DOCUMENT_TYPE");
      if (command.file.size < 1 || command.file.size > 5242880) throw new Error("DOCUMENT_TOO_LARGE");
      const form = new FormData(); form.append("file", command.file); form.append("language", command.language); body = form;
    } else if (command.kind === "reread") { headers.set("Content-Type", "application/json"); body = JSON.stringify({ ocr:command.ocr }); } else if (command.kind === "claim") { headers.set("Content-Type", "application/json"); body = JSON.stringify(command.content); }
    const path = `/api/profile/me/documents${command.kind === "upload" ? "" : `/${command.document.id}`}${command.kind === "reread" ? "/reread" : command.kind === "master" ? "/master" : command.kind === "claim" ? "/claims" : ""}`;
    const response = await fetch(path, { method:command.kind === "delete" ? "DELETE" : "POST", headers, body, signal:AbortSignal.timeout(command.kind === "reread" ? 125000 : 35000) });
    if (response.status === 401) onAuthRequired();
    if (command.kind === "delete" && response.status === 204) return;
    const value = await json(response); if (!(command.kind === "claim" ? isClaim(value) : command.kind === "reread" ? isDocumentDetail(value) : isDocument(value))) throw new Error("DOCUMENT_UNAVAILABLE"); return value;
  }, onSuccess:async (value, command) => {
    const existing=command.kind === "claim" && isClaim(value) && ((cache.getQueryData<CompetencyClaim[]>(["private-claims"])??[]).some(item=>item.id===value.id) || value.status!=="UNVERIFIED");
    if (command.kind !== "reread") setModal(null); setDraft(blank); setNotice(command.kind === "upload" ? "uploaded" : command.kind === "claim" ? existing ? "linked" : "saved" : command.kind === "master" ? "masterSaved" : command.kind === "reread" ? "reread" : "deleted");
    if (command.kind === "upload") { setFile(null); if (fileField.current) fileField.current.value = ""; }
    if (command.kind === "reread" && isDocumentDetail(value)) { cache.setQueryData(["private-document-detail",command.document.id],value); setReadingRevision(previous => previous + 1); } else cache.removeQueries({ queryKey:["private-document-detail"] }); cache.removeQueries({ queryKey:["private-document-analysis"] }); cache.removeQueries({ queryKey:["private-document-collection-text"] });
    await cache.invalidateQueries({ queryKey:["private-documents"] });
    if (command.kind === "claim" || command.kind === "delete") { cache.removeQueries({ queryKey:["private-claim-history"] }); cache.removeQueries({ queryKey:["private-claim-evidence"] }); await cache.invalidateQueries({ queryKey:["private-claims"] }); }
  } });
  const message = (error: Error | null) => error ? t.errors[error.message as keyof typeof t.errors] ?? t.errors.DOCUMENT_UNAVAILABLE : null;
  function open(document: CareerDocument, kind: "read" | "delete" | "collection") { mutation.reset(); setNotice(null); setDraft(blank); setModal({ document, kind }); }
  function close() { if (!mutation.isPending) { setModal(null); setDraft(blank); mutation.reset(); } }
  function selected() { const field = source.current; if (!field) return; const quote = field.value.slice(field.selectionStart, field.selectionEnd); if (quote.trim() && quote.length <= 1000) setDraft(previous => ({ skill:previous.skill, context:previous.context, quote, statement:quote })); }
  function submit(event: FormEvent) { event.preventDefault(); if (modal?.kind === "read" && !mutation.isPending) mutation.mutate({ kind:"claim", document:modal.document, content:draft }); }
  return <Card className="document-panel" id="profile-documents"><CardHeader><h2 className="flex items-center gap-2"><FileText size={20}/>{t.title}</h2><p className="hint">{t.intro}</p></CardHeader><CardContent>
    <form className="document-upload" onSubmit={event => { event.preventDefault(); if (file && !mutation.isPending) mutation.mutate({ kind:"upload", file, language }); }}>
      <div><label htmlFor="cv-file">{t.file}</label><Input id="cv-file" ref={fileField} type="file" accept=".docx,.pdf,.txt,.md" onChange={event => { setFile(event.target.files?.[0] ?? null); mutation.reset(); }} disabled={mutation.isPending}/></div>
      <div><label htmlFor="cv-language">{t.language}</label><select id="cv-language" value={language} onChange={event => setLanguage(event.target.value as Locale)} disabled={mutation.isPending}><option value="nb">Norsk</option><option value="en">English</option></select></div>
      <Button type="submit" disabled={!file || mutation.isPending || list.isError}><Upload size={16}/>{mutation.isPending ? t.busy : t.upload}</Button>
    </form><p className="hint">{t.limits}</p>
    {notice && <p role="status" className="claim-notice mt-4">{t[notice]}</p>}
    {(list.isError || mutation.isError && !modal) && <Alert variant="destructive" role="alert"><AlertDescription>{message(list.error ?? mutation.error)}</AlertDescription></Alert>}
    {list.isPending && <p role="status">{t.loading}</p>}
    {list.data && (list.data.length ? <div className="document-list">{list.data.map(document => <article key={document.id} aria-label={document.originalName} className="document-tile"><div className="claim-heading"><h3>{document.originalName}</h3>{document.isMaster && <Badge>{t.masterLabel}</Badge>}</div><div className="document-read-status" data-readable={document.textCharacters === undefined ? "unknown" : document.textCharacters > 0 ? "yes" : "no"}>{document.textCharacters === 0 ? <AlertCircle size={16}/> : <CheckCircle2 size={16}/>}<span>{document.textCharacters === undefined ? locale === "nb" ? "Åpne for å kontrollere teksten" : "Open to check extracted text" : document.textCharacters === 0 ? locale === "nb" ? "Ingen lesbar tekst · prøv OCR" : "No readable text · try OCR" : `${document.textCharacters.toLocaleString(locale)} ${locale === "nb" ? "tegn lest" : "characters read"}${document.extractionMethod === "OCR" ? " · OCR" : ""}`}</span></div><p className="hint">{Math.ceil(document.byteSize/1024)} KB · {document.language === "nb" ? "Norsk" : "English"}</p><div className="claim-actions">
      <Button variant="outline" size="sm" onClick={() => open(document, "read")} disabled={mutation.isPending}>{t.open}</Button><Button variant="ghost" size="sm" asChild><a href={`/api/profile/me/documents/${document.id}/original`}><Download size={14}/>{t.download}</a></Button>
      {!document.isMaster && ["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document"].includes(document.mediaType) && <Button variant="ghost" size="sm" disabled={mutation.isPending} onClick={() => mutation.mutate({ kind:"master", document })}><Star size={14}/>{t.master}</Button>}<Button variant="ghost" size="sm" disabled={mutation.isPending} onClick={() => open(document, "delete")}><Trash2 size={14}/>{t.remove}</Button>
    </div></article>)}</div> : <p className="hint mt-4">{t.empty}</p>)}
    {!!list.data?.length && <Button className="mt-4" variant="outline" disabled={mutation.isPending} onClick={() => open(list.data![0], "collection")}>{locale === "nb" ? "Oppsummer alle dokumentene med AI" : "Summarize all documents with AI"}</Button>}
    {!!list.data?.length && <DocumentChecks key={list.data.map(d=>`${d.id}-${d.textCharacters}`).join(",")} documents={list.data} csrfToken={csrfToken} locale={locale} onAuthRequired={onAuthRequired} onOpen={document=>open(document,"read")}/> }
    {list.isError && <Button variant="outline" onClick={() => void list.refetch()}>{t.refresh}</Button>}
    <Sheet open={!!modal} onOpenChange={value => { if (!value) close(); }}><SheetContent className="document-workspace-sheet" closeLabel={t.close}><SheetHeader className="document-review-header"><SheetTitle>{modal?.kind === "delete" ? t.deleteTitle : modal?.kind === "collection" ? locale === "nb" ? "Samlet kompetanseoversikt" : "Combined competency overview" : modal?.document.originalName}</SheetTitle><SheetDescription>{modal?.kind === "delete" ? t.deleteHint : modal?.kind === "collection" ? locale === "nb" ? "CV, attester, kursbevis og andre dokumenter vurderes samlet. Kontroller hvilke dokumenter som sendes." : "CVs, certificates and other documents are considered together. Review the documents before sending." : t.select}</SheetDescription></SheetHeader>
      {mutation.isError && <Alert variant="destructive" role="alert"><AlertDescription>{message(mutation.error)}</AlertDescription></Alert>}
      {modal?.kind === "collection" && <>{collection.isPending && <p role="status">{t.loading}</p>}{collection.isError && <Alert variant="destructive"><AlertDescription>{message(collection.error)}</AlertDescription></Alert>}{collection.data && <DocumentWorkflow scope="collection" documents={collection.data} locale={locale} csrfToken={csrfToken} onAuthRequired={onAuthRequired}/> }</>}
      {modal?.kind === "delete" && <Button variant="destructive" disabled={mutation.isPending} onClick={() => mutation.mutate({ kind:"delete", document:modal.document })}>{mutation.isPending ? t.busy : t.deleteAction}</Button>}
      {modal?.kind === "read" && <><div className="document-reading-tools"><Button variant="outline" size="sm" disabled={mutation.isPending} onClick={() => mutation.mutate({ kind:"reread", document:modal.document, ocr:false })}><RefreshCw size={15}/>{locale === "nb" ? "Les originalen på nytt" : "Reread original"}</Button>{modal.document.mediaType === "application/pdf" && <Button variant="outline" size="sm" disabled={mutation.isPending} onClick={() => mutation.mutate({ kind:"reread", document:modal.document, ocr:true })}><ScanText size={15}/>{locale === "nb" ? "Les skannet PDF med OCR" : "Read scanned PDF with OCR"}</Button>}<p className="hint">{mutation.isPending ? t.busy : locale === "nb" ? "Lokal lesing. Originalen og lagret kompetanse beholdes. OCR-tekst kan inneholde feil og må kontrolleres." : "Local reading. The original and saved competencies are retained. OCR text may contain errors and needs checking."}</p></div>{detail.isPending && <p role="status">{t.loading}</p>}{detail.isError && <Alert variant="destructive" role="alert"><AlertDescription>{message(detail.error)}</AlertDescription></Alert>}{detail.data && (detail.data.text ? <>
        <DocumentWorkflow key={`${selectedId}-${readingRevision}`} scope={selectedId!} documents={[detail.data]} locale={locale} csrfToken={csrfToken} onAuthRequired={onAuthRequired}/>
        <details className="manual-source-tools"><summary>{locale === "nb" ? "Originaltekst og manuell registrering" : "Extracted text and manual entry"}</summary><label htmlFor="document-text">{t.text}</label><Textarea id="document-text" ref={source} value={detail.data.text} readOnly rows={12}/><Button variant="outline" size="sm" onClick={selected}>{t.selected}</Button>
        <form className="claim-form" onSubmit={submit}><div><label htmlFor="document-quote">{t.quote}</label><Textarea id="document-quote" value={draft.quote} onChange={event => setDraft({ ...draft, quote:event.target.value })} maxLength={1000} required rows={3} disabled={mutation.isPending}/></div>
          {(["skill", "statement", "context"] as const).map(key => <div key={key}><label htmlFor={`document-${key}`}>{t[key]}</label>{key === "skill" ? <Input id={`document-${key}`} required maxLength={120} value={draft[key]} onChange={event => setDraft({ ...draft, [key]:event.target.value })} disabled={mutation.isPending}/> : <Textarea id={`document-${key}`} required maxLength={key === "statement" ? 1000 : 500} value={draft[key]} onChange={event => setDraft({ ...draft, [key]:event.target.value })} disabled={mutation.isPending}/>}</div>)}
          <p className="hint">{t.review}</p><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? t.busy : t.save}</Button>
        </form></details>
      </> : <p>{t.noText}</p>)}</>}
      <Button variant="outline" disabled={mutation.isPending} onClick={close}>{t.cancel}</Button>
    </SheetContent></Sheet>
  </CardContent></Card>;
}
