"use client";
import { HelpTip } from "./ui/help-tip";
import { DocumentCoverage } from "./document-coverage";

import { useAiChoice } from "../lib/use-ai-configuration";
import { aiRecipients } from "../lib/ai-configuration";
import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, Pause, Play, Sparkles, BriefcaseBusiness, Layers, Check } from "lucide-react";
import { Card, CardContent, CardHeader } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { Alert, AlertDescription } from "./ui/alert";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "./ui/sheet";
import { isDocumentRun, categoryLabels, profileLabels, type DocumentRun } from "../lib/document-workflow";
import { isClaim } from "../lib/claims";
import { isEntry, entryKinds, type EntryContent } from "../lib/career-entries";
import { retryAfterSeconds, retryWaitLabel } from "../lib/retry-after";
import type { DocumentDetail } from "../lib/documents";
import type { CompetencySuggestion, CareerDraft, ProposalReviewState } from "../lib/document-analysis";
import type { Locale } from "../lib/translations";

import { AiActivity, AiChoice, AiIdentity } from "./ai-identity";
import { CompetencyProposalGroups } from "./competency-proposal-groups";

const base = "/api/profile/me/documents/workflow";
export function DocumentWorkflow({ scope, documents, locale, csrfToken, onAuthRequired, onOpenProfile }: {
  scope: string; documents: DocumentDetail[]; locale: Locale; csrfToken: string; onAuthRequired: () => void; onOpenProfile?:()=>void;
}) {
  const nb = locale === "nb"; const cache = useQueryClient();
  const choice=useAiChoice("documents"); const {configuration,approval}=choice; const recipients=aiRecipients(approval);
  const [previews, setPreviews] = useState(() => documents.map(d => ({documentId:d.document.id, text:d.text, included:!!d.text.trim()})));
  const [populateProfile,setPopulateProfile]=useState(true);
  const [coverageReview,setCoverageReview]=useState(true);
  const [consent, setConsent] = useState(false); const consentInput=useRef<HTMLInputElement>(null);
  useEffect(()=>setConsent(false),[approval?.token]); const [run, setRun] = useState<DocumentRun | null>(null);
  const [active, setActive] = useState(false); const control = useRef<{stop:boolean; abort:AbortController} | null>(null);
  const [retryUntil,setRetryUntil]=useState(0);
  const [now, setNow] = useState(Date.now()); const [filter, setFilter] = useState("ALL"); const [search,setSearch]=useState("");
  const [queueView,setQueueView]=useState("PENDING");
  const [decisions,setDecisions]=useState<Record<number,ProposalReviewState>>({});
  const [review, setReview] = useState<{index:number; draft:CompetencySuggestion} | null>(null);
  const [history, setHistory] = useState<CareerDraft | null>(null); const [confirmed, setConfirmed] = useState(false);
  const [resultSection,setResultSection]=useState<"competencies"|"profile"|"history">("competencies");
  const [notice, setNotice] = useState<string | null>(null); const [saved, setSaved] = useState<string[]>([]);
  useEffect(() => { const timer=setInterval(()=>setNow(Date.now()),1000); return ()=> { clearInterval(timer); if(control.current){control.current.stop=true;control.current.abort.abort();} }; }, []);
  async function request(path:string, method="GET", body?:unknown, signal?:AbortSignal):Promise<unknown> {
    const response=await fetch(path,{method,cache:"no-store",headers:{"Content-Type":"application/json","X-CSRF-TOKEN":csrfToken},body:body===undefined?undefined:JSON.stringify(body),signal});
    if(response.status===401)onAuthRequired();const value=await response.json();
    if(!response.ok){const error=new Error(typeof value?.code==="string"?value.code:"DOCUMENT_UNAVAILABLE") as Error & {seconds?:number};error.seconds=retryAfterSeconds(response.headers.get("retry-after"));throw error;} return value;
  }
  const latest=useQuery({queryKey:["private-document-workflow",scope],gcTime:0,retry:false,refetchOnReconnect:false,refetchOnWindowFocus:false,queryFn:async()=>{
    const value=await request(`${base}?scope=${encodeURIComponent(scope)}`);if(value!==null && !isDocumentRun(value))throw new Error("DOCUMENT_UNAVAILABLE");return value;
  }});
  const current=run ?? latest.data ?? null;
  const analysis=current?.analysis;
  const savedPlan=current?.plannedSelections?.length?current.plannedSelections:current?.aiApproval===configuration.data?.documents.token?configuration.data?.documents.selections:choice.options.find(o=>o.approval.token===current?.aiApproval)?.approval.selections;
  const changingProvider=!!current?.aiApproval && !!approval && current.aiApproval!==approval.token;
  const wait=changingProvider?0:Math.max(0,Math.ceil((Math.max(current?.nextAt?Date.parse(current.nextAt):0,retryUntil)-now)/1000));
  const selected=previews.filter(p=>p.included && p.text.trim()).map(({documentId,text})=>({documentId,text}));
  const matchesSavedPreview=!current?.approvedDocuments || current.approvedDocuments.length===selected.length && current.approvedDocuments.every(d=>selected.some(p=>p.documentId===d.documentId && p.text===d.text));
  const size=selected.reduce((sum,p)=>sum+p.text.length,0);
  function remember(value:unknown):DocumentRun { if(!isDocumentRun(value))throw new Error("DOCUMENT_UNAVAILABLE");setRun(value);cache.setQueryData(["private-document-workflow",scope],value);void cache.invalidateQueries({queryKey:["private-document-profile"]});if(value.populateProfile && value.completedBatches>0){void cache.invalidateQueries({queryKey:["private-claims"]});void cache.invalidateQueries({queryKey:["private-entries"]});void cache.invalidateQueries({queryKey:["private-claim-context"]});}return value; }
  const process=useMutation({retry:false,mutationFn:async(fresh:boolean)=>{
    if(control.current)throw new Error("AI_BUSY");
    if(!approval || !consent)throw new Error("AI_APPROVAL_CHANGED");
    const session={stop:false,abort:new AbortController()};control.current=session;setActive(true);setNotice(null);
    try {
      let next:DocumentRun;
      if(fresh){setSaved([]);setDecisions({});setQueueView("PENDING");next=remember(await request(base,"POST",{scope,documents:selected,locale,consent,aiApproval:approval?.token,populateProfile,coverageReview},session.abort.signal));}
      else {if(!current)throw new Error("DOCUMENT_UNAVAILABLE");next=remember(await request(`${base}/${current.id}`,"GET",undefined,session.abort.signal));
        if(!matchesSavedPreview)throw new Error("DOCUMENT_ANALYSIS_CONFLICT");
        if(next.aiApproval!==approval.token && !(next.aiApproval==null && recipients==="Groq"))next=remember(await request(`${base}/${next.id}/provider`,"POST",{revision:next.revision,consent,aiApproval:approval.token},session.abort.signal));}
      while(!session.stop && next.status!=="COMPLETED") {
        // Waiting is genuine quota pacing. Never retry a rejected provider call automatically.
        while(!session.stop && next.nextAt && Date.parse(next.nextAt)>Date.now())await new Promise(resolve=>setTimeout(resolve,250));
        if(session.stop)break;
        next=remember(await request(`${base}/${next.id}/next`,"POST",{revision:next.revision},session.abort.signal));
        if(next.status==="PAUSED")break;
      }
      return next;
    } finally {if(control.current===session){control.current=null;setActive(false);}}
  },onError:error=>{const seconds=(error as Error & {seconds?:number}).seconds;if(seconds)setRetryUntil(Date.now()+seconds*1000);}});
  const save=useMutation({retry:false,mutationFn:async(command:{kind:"claim"|"entry"|"summary";body:unknown;index?:number;decision?:ProposalReviewState})=>{
    if(!current)throw new Error("DOCUMENT_UNAVAILABLE");const value=await request(`${base}/${current.id}/${command.kind==="claim"?"claims":command.kind==="entry"?"entries":"summary"}`,command.kind==="summary"?"PUT":"POST",command.body);if(!(command.kind==="claim"?isClaim(value):command.kind==="entry"?isEntry(value):isDocumentRun(value)))throw new Error("DOCUMENT_UNAVAILABLE");return {command,value};
  },onSuccess:async({command,value})=>{
    if(command.kind==="summary")remember(value);
    else if(command.kind==="claim" && isClaim(value)){setSaved(previous=>[...previous,`claim:${command.index}`]);if(command.index!==undefined)setDecisions(previous=>({...previous,[command.index!]:value.status==="CONFIRMED"?(value.confirmationBasis==="DOCUMENT"?"DOCUMENTED":"CONFIRMED"):value.status==="REJECTED"?"REJECTED":"DRAFT"}));setReview(null);await cache.invalidateQueries({queryKey:["private-claims"]});await cache.invalidateQueries({queryKey:["private-claim-context"]});}
    else if(command.kind==="entry" && isEntry(value)){setSaved(previous=>[...previous,`entry:${history?.key}`]);setHistory(null);await cache.invalidateQueries({queryKey:["private-entries"]});await cache.invalidateQueries({queryKey:["private-claim-context"]});}
    else throw new Error("DOCUMENT_UNAVAILABLE");
    if(command.kind!=="summary" && current){try{remember(await request(`${base}/${current.id}`));}catch{ /* Keep the successful local decision if refreshing is unavailable. */ }}
    setNotice(nb?"Lagret. Bekreftede opplysninger er klare for videre bruk; andre er utkast.":"Saved. Confirmed information is ready for use; other information remains a draft.");
  }});
  function stop(){if(control.current)control.current.stop=true;}
  function failure(code:string){
    if(code==="AI_APPROVAL_CHANGED")return nb?"AI-oppsettet er endret. Hent oppsettet på nytt, kontroller mottakeren og start en ny analyse. Lagrede forslag beholdes.":"The AI configuration changed. Refresh it, review the recipient and start a new analysis. Saved drafts are retained.";
    if(code==="AI_RATE_LIMITED")return nb?"AI-kvoten er midlertidig brukt opp. Fremdrift og forslag er bevart. Fortsett når ventetiden er over.":"AI quota is temporarily exhausted. Progress and drafts are preserved. Continue when the wait ends.";
    if(code==="AI_INVALID_RESULT")return nb?"Denne delen ga ikke brukbare AI-forslag. Dokumentene og tidligere forslag er bevart; du kan prøve å fortsette.":"This step produced no usable AI drafts. Documents and previous drafts are preserved; you can try continuing.";
    if(code==="AI_BUDGET_REACHED")return nb?"Pilotens grense for dokumentkall er nådd. Forslagene er bevart; grensen gjelder frem til backend starter på nytt.":"The pilot document-call budget was reached. Drafts are preserved; the budget lasts until backend restart.";
    if(code==="DOCUMENT_AI_OUTPUT_TOO_LARGE")return nb?"Dette grunnlaget eller resultatet er større enn pilotens lagringsgrense. Tidligere fremdrift er bevart. Velg færre dokumenter for en ny analyse.":"These sources or results exceed the pilot storage limit. Previous progress is retained. Select fewer documents for a new analysis.";
    if(code==="DOCUMENT_ANALYSIS_CONFLICT" || code==="DOCUMENT_NOT_FOUND")return nb?"Dokumentgrunnlaget er endret. Lukk oversikten og åpne dokumentene på nytt før en ny analyse.":"Document sources changed. Close this review and reopen the documents before a new analysis.";
    if(code==="AUTH_REQUIRED")return nb?"Logg inn igjen. Lagret fremdrift beholdes.":"Sign in again. Saved progress is retained.";
    return nb?"Vi kunne ikke fullføre dette nå. Dokumentene og lagrede forslag er beholdt. Prøv igjen senere.":"We could not complete this now. Documents and saved drafts are retained. Try again later.";
  }
  const error=save.error ?? process.error ?? latest.error;
  const issue=error?.name==="AbortError"?null:error?.message ?? current?.issue;
  const names=new Map(documents.map(d=>[d.document.id,d.document.originalName]));
  const languages=new Map(documents.map(d=>[d.document.id,d.document.language]));
  function reviewState(draft:CompetencySuggestion,index:number) {return decisions[index]??draft.reviewState??(draft.profileClaimId?"DOCUMENTED":saved.includes(`claim:${index}`)?"DRAFT":"PENDING");}
  const viewFor=(state:string)=>["DOCUMENTED","CONFIRMED"].includes(state)?"READY":["REJECTED","REMOVED"].includes(state)?"REJECTED":state;
  const queueViews=[{key:"PENDING",label:nb?"Venter på gjennomgang":"Waiting for review"},{key:"READY",label:nb?"Godkjent / dokumentert":"Approved / documented"},{key:"DRAFT",label:nb?"Lagrede utkast":"Saved drafts"},{key:"REJECTED",label:nb?"Avvist / fjernet":"Rejected / removed"}];
  const countFor=(key:string)=>(analysis?.suggestions??[]).filter((draft,index)=>viewFor(reviewState(draft,index))===key).length;
  function decide(index:number,draft:CompetencySuggestion,decision:"confirm"|"draft"|"reject") {
    save.mutate({kind:"claim",index,decision:decision==="confirm"?"CONFIRMED":decision==="reject"?"REJECTED":"DRAFT",body:{revision:current!.revision,index,skill:draft.skill,statement:draft.statement,context:draft.context,confirm:decision==="confirm",...(decision==="reject"?{reject:true}:{})}});
  }
  const proposals=(analysis?.suggestions??[]).map((draft,index)=>({draft,index})).filter(({draft,index})=>viewFor(reviewState(draft,index))===queueView && (filter==="ALL" || (draft.category??"OTHER")===filter) && `${draft.skill} ${draft.context} ${draft.statement}`.toLocaleLowerCase(locale).includes(search.trim().toLocaleLowerCase(locale)));

  return <div className="full-document-workflow" data-completed={current?.status==="COMPLETED"}>
    <div className="document-flow-heading"><div><Badge>{nb?"Dokumenter → din profil":"Documents → your profile"}</Badge><h3>{nb?"La dokumentene gjøre grunnarbeidet":"Let your documents do the groundwork"}</h3><p className="hint">{nb?"Vi leser hele grunnlaget og lager redigerbare forslag. Du kontrollerer hva som faktisk beskriver deg.":"We read the entire source selection and draft editable proposals. You decide what accurately describes you."}</p></div></div>
    <details className="document-source-settings" open={!current || current.status!=="COMPLETED"}><summary><FileText size={16}/>{nb?"Dokumentgrunnlag og analyse":"Sources and analysis"}<span>{documents.length} {nb?"dokumenter":"documents"}</span></summary><Card><CardHeader><h3 className="flex items-center gap-2"><FileText size={18}/>{nb?"Dokumentgrunnlag":"Document sources"}</h3><p className="hint">{nb?"Åpne for å kontrollere teksten eller fjerne private opplysninger. Innholdet behandles automatisk i mindre deler; du trenger ikke dele det selv.":"Open to review text or remove private details. Processing uses smaller portions automatically; you do not need to split documents."}</p></CardHeader><CardContent>
      <div className="document-source-grid">{previews.map((p,index)=><details key={p.documentId} className="source-review-tile"><summary><span>{names.get(p.documentId)}</span><Badge variant="outline">{p.text.length.toLocaleString(locale)} {nb?"tegn":"characters"}</Badge></summary>
        <label className="consent-row"><input type="checkbox" checked={p.included} disabled={active} onChange={e=>{setConsent(false);setPreviews(previews.map((v,i)=>i===index?{...v,included:e.target.checked}:v));}}/>{nb?"Ta med dokumentet":"Include document"}</label>
        {!p.text.trim() && <p>{nb?"Ingen lesbar tekst. Les originalen med OCR, eller last opp en lesbar kopi.":"No readable text. Reread using OCR or upload a readable copy."}</p>}
        <Textarea lang={languages.get(p.documentId)} aria-label={`${nb?"Tekst som sendes fra":"Text sent from"} ${names.get(p.documentId)}`} rows={8} maxLength={60000} value={p.text} disabled={active} onChange={e=>{setConsent(false);setPreviews(previews.map((v,i)=>i===index?{...v,text:e.target.value}:v));}}/>
      </details>)}</div>
      <p className="hint mt-3">{selected.length} {nb?"dokumenter valgt":"documents selected"} · {size.toLocaleString(locale)} {nb?"tegn. Originalene beholdes. Forslagene lagres privat og er ubekreftet.":"characters. Originals are retained. Drafts are stored privately and remain unverified."}</p>
      <label className="consent-row"><input type="checkbox" checked={populateProfile} disabled={active} onChange={e=>{setPopulateProfile(e.target.checked);setConsent(false);}}/>{nb?"Fyll ut kompetanse og karrierehistorikk automatisk":"Populate competencies and career history automatically"}</label>
      <p className="hint">{nb?"Ordrette kompetanseopplysninger lagres som dokumentert med kilde. Historikk og AI-formuleringer er redigerbare utkast. Egne endringer, avvisninger og slettinger beholdes.":"Literal competency statements are saved with document evidence. Career history and AI wording remain editable drafts. Your edits, rejections and deletions are preserved."}</p>
      {current && current.status!=="COMPLETED" && <p className="hint">{nb?"Lagret analyse:":"Saved run:"} {current.populateProfile?(nb?"automatisk profilutfylling":"automatic profile population"):(nb?"kun forslag; start en ny analyse for automatisk utfylling":"proposals only; start a new run for automatic population")}</p>}
      <label className="consent-row"><input type="checkbox" checked={coverageReview} disabled={active} onChange={e=>{setCoverageReview(e.target.checked);setConsent(false);}}/>{nb?"Kontroller passasjer som kan være oversett":"Check potentially missed passages"}</label>
      <p className="hint">{nb?"Nye analyser kan bruke opptil fire ekstra AI-kall på oversette passasjer, med valgt modell og samme godkjente tekst. Lagrede eldre analyser utvides ikke automatisk.":"New analyses may use up to four additional AI calls on missed passages, using the selected model and approved text. Older saved runs are not automatically extended."}</p>
      <label className="consent-row"><input ref={consentInput} type="checkbox" checked={consent} disabled={active || !approval} onChange={e=>setConsent(e.target.checked)}/>{nb?`Jeg godkjenner at valgt tekst sendes til ${recipients} for denne analysen`:`I approve sending the selected text to ${recipients} for this analysis`}</label>
      <AiChoice approval={approval} options={choice.options} choose={choice.choose} disabled={active} locale={locale}/>{(configuration.isError || issue==="AI_APPROVAL_CHANGED") && <Button variant="outline" onClick={()=>void configuration.refetch()}>{nb?"Hent AI-oppsett på nytt":"Refresh AI configuration"}</Button>}
      {current && !matchesSavedPreview && <p className="hint">{nb?"Tekstutvalget er endret. Start en ny analyse, eller hent det godkjente utvalget fra den lagrede analysen.":"The text selection changed. Start a new analysis, or restore the approved selection from the saved run."} <Button size="sm" variant="ghost" disabled={active} onClick={()=>{const approved=new Map(current.approvedDocuments?.map(d=>[d.documentId,d.text]));setPreviews(previews.map(p=>({...p,included:approved.has(p.documentId),text:approved.get(p.documentId)??p.text})));setConsent(false);}}>{nb?"Hent lagret tekstutvalg":"Restore saved text selection"}</Button></p>}
      <div className="claim-actions"><Button disabled={!approval || !consent || size<40 || wait>0 || active || save.isPending || latest.isPending} onClick={()=>process.mutate(true)}><Sparkles size={16}/>{current?nb?"Start ny analyse":"Start new analysis":nb?"Bygg profil fra dokumentene":"Build profile from documents"}</Button>
        {current && current.status!=="COMPLETED" && !active && <Button variant="outline" disabled={!approval || !consent || !matchesSavedPreview || wait>0 || save.isPending} onClick={()=>process.mutate(false)}><Play size={16}/>{nb?"Fortsett lagret analyse":"Continue saved analysis"}</Button>}
        {active && <Button variant="outline" onClick={stop}><Pause size={16}/>{nb?"Stopp etter dette kallet":"Stop after this call"}</Button>}</div>
    </CardContent></Card></details>
    {active && <AiActivity waiting={wait>0} label={wait>0?(nb?"Kort pause mellom AI-kall":"Pausing between AI calls"):(current?.phase==="REPAIR"?(nb?"Går gjennom mulige mangler …":"Reviewing potentially missed evidence …"):current?.phase==="SUMMARY"?(nb?"Samler profilen din …":"Putting your profile together …"):(nb?"Venter på AI-svar …":"Waiting for the AI response …"))} detail={wait>0?retryWaitLabel(wait):(nb?"Dokumentene leses, og kildebaserte forslag lagres underveis.":"Reading document evidence and saving source-backed drafts along the way.")}/>}
    {!active && wait>0 && <AiActivity waiting label={current?.issue==="AI_RATE_LIMITED"?(nb?"Venter på ledig AI-kvote":"Waiting for available AI quota"):(nb?"Kort pause mellom AI-kall":"Pausing between AI calls")} detail={retryWaitLabel(wait)}/>}
    {current && <div className={`document-run-status ${current.status==="COMPLETED"?"document-run-completed":""}`} role="status"><AiIdentity selections={savedPlan} provider={savedPlan?undefined:current.analysis.provider} locale={locale} label={active?(nb?"Kjører med":"Running with"):(nb?"Lagret kjøreplan":"Saved run plan")}/><div><strong>{current.status==="COMPLETED"?(nb?"Gjennomgangen er klar":"Review ready"):active?(wait?nb?"Venter på neste kall":"Waiting for next call":nb?"Leser dokumentgrunnlaget":"Reading document sources"):nb?"Fremdriften er lagret":"Progress saved"}</strong><span>{current.completedBatches} / {current.totalBatches} {nb?"behandlingstrinn":"processing steps"}{wait>0?` · ${retryWaitLabel(wait)}`:""}</span></div><progress aria-label={nb?"Dokumentanalyse":"Document analysis"} max={current.totalBatches} value={current.completedBatches}/><p className="hint">{analysis?.inputCharacters.toLocaleString(locale)} / {analysis?.sourceCharacters.toLocaleString(locale)} {nb?"kildetegn behandlet. Tekstdekning betyr ikke at AI har funnet all kompetanse.":"source characters processed. Text coverage does not mean AI found every competency."}</p></div>}
    {issue && <Alert><AlertDescription>{changingProvider?(nb?"Ny mottaker/modell valgt. Godkjenn og fortsett; lagrede forslag beholdes.":"New recipient/model selected. Approve and continue; saved drafts are retained."):failure(issue)}{!active && !changingProvider && ["AI_RATE_LIMITED","AI_UNAVAILABLE","AI_INVALID_RESULT","AI_ACCESS_DENIED"].includes(issue) && choice.alternatives.map(option=><Button key={option.approval.token} size="sm" variant="outline" className="mt-3 mr-2" onClick={()=>{choice.choose(option.approval.token);setConsent(false);process.reset();consentInput.current?.scrollIntoView({block:"center",behavior:"smooth"});}}>{nb?"Prøv med":"Try with"} {option.approval.selections.map(s=>`${s.provider} · ${s.model}`).join(" / ")}</Button>)}</AlertDescription></Alert>}
    {notice && <p role="status">{notice}</p>}
    {current && <DocumentCoverage run={current} nb={nb}/>}
    {analysis && <>
      <AiIdentity selections={analysis.aiSelections} provider={analysis.aiSelections?.length?undefined:analysis.inputCharacters>0?analysis.provider:undefined} locale={locale} label={analysis.aiSelections?.length?(nb?"Brukt i resultatet":"Used in this result"):(nb?"Lagret leverandør":"Recorded provider")}/><div className="document-results-heading"><h3><Sparkles size={18}/>{nb?"Din dokumentbaserte profil":"Your document-based profile"}</h3><HelpTip label={nb?"Om dokumentprofilen":"About your document profile"}>{nb?"Dokumenterte fakta lagres med kilde. AI-sammendrag og nye formuleringer er redigerbare utkast. Godkjente, avviste og lagrede utkast ligger utenfor køen som venter.":"Documented facts retain their sources. AI summaries and new wording remain editable drafts. Approved, rejected and saved drafts are outside the pending queue."}</HelpTip><Badge variant="outline">{nb?"AI-utkast · kontroller før bruk":"AI draft · review before use"}</Badge></div>
      {analysis.partial && <p className="hint">{nb?"Grunnlaget er delvis behandlet eller redigert. Det som mangler, er ikke et kompetansegap.":"Sources are partly processed or edited. Missing information is not a skill gap."}</p>}
      {current?.populateProfile && <p className="hint document-population-note"><strong>{nb?"Profilen fylles ut underveis":"Your profile is populated along the way"}</strong> · {new Set(analysis.suggestions.map(s=>s.profileClaimId).filter(Boolean)).size} {nb?"kompetanseopplysninger":"competency statements"} · {new Set(analysis.careerEntries?.map(e=>e.profileEntryId).filter(Boolean)).size} {nb?"historikkoppføringer":"career entries"}{current.populationLimited && <span> · {nb?"Lagringsgrensen er nådd; resterende forslag er bevart.":"Storage limit reached; remaining proposals are retained."}</span>}</p>}
      {!!analysis.suggestions.filter(s=>s.recovered).length && <p className="hint">{analysis.suggestions.filter(s=>s.recovered).length} {nb?"etiketter fra eksplisitte kompetanselister er kontrollert og tatt med lokalt, uten ekstra AI-kall.":"labels from explicit skills lists were recovered locally, without extra AI calls."}</p>}
      <nav className="document-review-navigation" aria-label={nb?"Gjennomgå dokumentforslag":"Review document proposals"}>{([
        ["competencies",nb?"Kompetanse":"Competencies",analysis.suggestions.length],
        ["profile",nb?"Profilsammendrag":"Profile summary",analysis.profile?.length??0],
        ["history",nb?"Karrierehistorikk":"Career history",analysis.careerEntries?.length??0],
      ] as const).map(([section,label,count])=><Button key={section} variant={resultSection===section?"default":"outline"} aria-label={label} aria-pressed={resultSection===section} aria-controls={`document-results-${section}`} onClick={()=>setResultSection(section)}>{section==="competencies"?<Layers size={16}/>:section==="history"?<BriefcaseBusiness size={16}/>:<FileText size={16}/>} {label}<Badge variant="outline">{count}</Badge></Button>)}</nav>
      <details className="document-source-coverage"><summary>{nb?"Se behandling per dokument":"View processing by document"}</summary><p className="hint">{nb?"Dette viser tekstmengde og antall forslag, ikke en garanti for at all kompetanse er funnet.":"This shows processed text and proposal counts, not a guarantee that every competency was found."}</p><div className="document-source-grid">{analysis.documents.map(doc=><div key={doc.documentId} className="source-review-tile"><strong>{doc.originalName}</strong><p>{doc.inputCharacters.toLocaleString(locale)} {nb?"tegn behandlet":"characters processed"} · {doc.sourceCharacters.toLocaleString(locale)} {nb?"tegn i originalteksten":"characters in original text"}</p><p className="hint">{analysis.suggestions.filter(draft=>draft.documentId===doc.documentId || draft.additionalSources?.some(source=>source.documentId===doc.documentId)).length} {nb?"kompetanseforslag med kilde her":"competency proposals citing this source"}</p></div>)}</div></details>
      <div id="document-results-profile" hidden={resultSection!=="profile"}>
      <div className="profile-summary-grid">{(analysis.profile??[]).map((item,index)=><SummaryDraft key={`${current!.id}-${index}-${item.kind}`} label={profileLabels[locale][item.kind as keyof typeof profileLabels.nb]} text={item.text} quote={item.quote} source={names.get(item.documentId)??""} language={analysis.locale} sourceLanguage={languages.get(item.documentId)??locale} additionalSources={(item.additionalSources??[]).map(source=>({quote:source.quote,source:names.get(source.documentId)??"",language:languages.get(source.documentId)??locale}))} locale={locale} disabled={active || save.isPending || current!.status!=="COMPLETED"} onSave={text=>save.mutate({kind:"summary",body:{revision:current!.revision,index,text}})}/>)}</div>
      {!analysis.profile?.length && <p className="hint">{nb?"Sammendraget fylles ut når vi har kildegrunnlag. Utdanning og interesser legges bare til når dokumentene beskriver dem.":"A summary appears when source evidence is available. Education and interests require explicit document evidence."}</p>}
      </div><div id="document-results-history" hidden={resultSection!=="history"}>
      <div className="document-results-heading"><h3>{nb?"Arbeid, prosjekter og utdanning":"Employment, projects and education"}</h3><Badge variant="outline">{analysis.careerEntries?.length??0}</Badge></div>
      <div className="career-draft-grid">{(analysis.careerEntries??[]).map(draft=><Card key={draft.key}><CardContent className="pt-5"><Badge variant="outline">{entryKinds[locale][draft.content.kind]}</Badge><h4>{draft.content.title}</h4><p>{draft.content.organization}{draft.content.client?` · ${draft.content.client}`:""}</p><p className="hint">{draft.periodText || (nb?"Periode ikke oppgitt":"Period not stated")}</p><p lang={analysis.locale}>{draft.content.description}</p>{draft.profileEntryId?<Button asChild variant="outline" size="sm"><a onClick={onOpenProfile} href="/career/profile#profile-career-history">{nb?"Åpne i karrierehistorikken":"Open career history"}</a></Button>:<Button variant="outline" size="sm" disabled={active || save.isPending} onClick={()=>{setHistory(draft);setConfirmed(false);save.reset();}}>{saved.includes(`entry:${draft.key}`)?nb?"Se igjen":"Review again":nb?"Kontroller og legg til historikk":"Review and add history"}</Button>}</CardContent></Card>)}</div>
      </div><div id="document-results-competencies" hidden={resultSection!=="competencies"}>
      <div className="review-queue-toolbar"><div className="document-results-heading"><h3>{nb?"Gjennomgå kompetansen":"Review competencies"}</h3><Badge>{countFor("PENDING")} {nb?"venter":"waiting"}</Badge></div>
      <nav className="review-state-navigation" aria-label={nb?"Status på kompetanseforslag":"Competency proposal status"}>{queueViews.map(view=><Button key={view.key} size="sm" variant={queueView===view.key?"default":"ghost"} aria-pressed={queueView===view.key} onClick={()=>setQueueView(view.key)}>{view.label}<Badge variant="outline">{countFor(view.key)}</Badge></Button>)}</nav>
      <Input aria-label={nb?"Søk i AI-forslag":"Search AI proposals"} placeholder={nb?"Søk etter kompetanse, firma eller prosjekt …":"Search skills, company or project …"} value={search} onChange={e=>setSearch(e.target.value)}/>
      <div className="competency-filter-row" aria-label={nb?"Kompetansekategorier":"Competency categories"}>{["ALL",...Object.keys(categoryLabels[locale])].map(category=><Button key={category} size="sm" variant={filter===category?"default":"outline"} aria-pressed={filter===category} onClick={()=>setFilter(category)}>{category==="ALL"?nb?"Alle":"All":categoryLabels[locale][category as keyof typeof categoryLabels.nb]}</Button>)}</div>
      <p className="hint">{queueView==="PENDING"?(nb?"Godkjenn hvis teksten beskriver din erfaring. Rediger ved behov, eller legg til side som utkast. Valget lagres uten nye AI-kall.":"Approve when the statement describes your experience. Edit it or set it aside as a draft. Decisions are saved without new AI calls."):(nb?"Disse opplysningene er ferdigbehandlet og ligger utenfor gjennomgangskøen. Du kan fortsatt endre dem i profilen.":"These statements have been processed and are outside the review queue. You can still edit them in your profile.")}</p><small className="hint">{proposals.length} / {countFor(queueView)} {nb?"opplysninger i dette utvalget":"statements in this selection"}</small></div>
      {queueView==="PENDING" && countFor("PENDING")===0 && countFor("READY")>0 && <div className="document-review-complete" role="status"><Check size={18}/><span>{nb?"Ingen kompetanse venter på godkjenning. Se dokumenterte og godkjente opplysninger, eller åpne profilen for å redigere.":"No competencies are waiting for approval. Inspect documented and approved statements, or edit them in your profile."}</span><Button size="sm" variant="outline" onClick={()=>setQueueView("READY")}>{nb?"Se kompetansen din":"View your competencies"}</Button></div>}
      <CompetencyProposalGroups proposals={proposals} names={names} locale={locale} language={analysis.locale} pending={queueView==="PENDING"} onOpenProfile={onOpenProfile} onDecision={decide} disabled={active || save.isPending} onReview={(index,draft)=>{setReview({index,draft:{...draft}});setConfirmed(false);save.reset();}}/>
      </div>
      {!!analysis.omittedItems && <p className="hint">{analysis.omittedItems} {nb?"forslag manglet kontrollerbart grunnlag eller overskred grensene. Kildeteksten er bevart.":"proposals lacked verifiable evidence or exceeded limits. Source text is retained."}</p>}
    </>}
    <Sheet open={!!review || !!history} onOpenChange={open=>{if(!open && !save.isPending){setReview(null);setHistory(null);save.reset();}}}><SheetContent className="document-draft-sheet" closeLabel={nb?"Lukk":"Close"}><SheetHeader><SheetTitle>{nb?"Kontroller opplysningen":"Review this information"}</SheetTitle><SheetDescription>{nb?"AI har fylt ut et utkast. Rett teksten slik at den beskriver din egen erfaring. Kilden beholdes.":"AI has filled a draft. Edit it to describe your own experience accurately. Evidence is retained."}</SheetDescription></SheetHeader>
      {review && <><label htmlFor="draft-skill">{nb?"Kompetanse":"Competency"}</label><Input id="draft-skill" value={review.draft.skill} maxLength={120} onChange={e=>setReview({...review,draft:{...review.draft,skill:e.target.value}})}/><label htmlFor="draft-statement">{nb?"Hva gjorde du selv?":"What did you personally do?"}</label><Textarea id="draft-statement" value={review.draft.statement} maxLength={1000} rows={5} onChange={e=>setReview({...review,draft:{...review.draft,statement:e.target.value}})}/><label htmlFor="draft-context">{nb?"Firma / prosjekt":"Company / project"}</label><Input id="draft-context" value={review.draft.context} maxLength={500} onChange={e=>setReview({...review,draft:{...review.draft,context:e.target.value}})}/></>}
      {history && <HistoryFields content={history.content} locale={locale} onChange={content=>setHistory({...history,content})}/>}
      <details open className="draft-evidence"><summary>{nb?"Dokumentert grunnlag":"Source evidence"}</summary><p className="hint">{names.get(review?.draft.documentId??history?.documentId??"")}</p><blockquote>{review?.draft.quote??history?.quote}</blockquote>{(review?.draft.additionalSources??history?.additionalSources)?.map((source,index)=><div key={index}><p className="hint">{names.get(source.documentId)}</p><blockquote>{source.quote}</blockquote></div>)}</details>
      <label className="consent-row"><input type="checkbox" checked={confirmed} disabled={save.isPending} onChange={e=>setConfirmed(e.target.checked)}/>{nb?"Jeg har kontrollert teksten og bekrefter at dette er min erfaring":"I reviewed the text and confirm this is my experience"}</label>
      {save.error && <Alert><AlertDescription>{failure(save.error.message)}</AlertDescription></Alert>}
      <Button disabled={save.isPending || active || (review?!review.draft.skill.trim() || !review.draft.statement.trim() || !review.draft.context.trim():!history?.content.title.trim() || !history?.content.organization.trim())} onClick={()=>{if(review)save.mutate({kind:"claim",index:review.index,decision:confirmed?"CONFIRMED":"DRAFT",body:{revision:current!.revision,index:review.index,skill:review.draft.skill,statement:review.draft.statement,context:review.draft.context,confirm:confirmed}});else if(history)save.mutate({kind:"entry",body:{key:history.key,content:history.content,confirm:confirmed}});}}>{save.isPending?nb?"Lagrer …":"Saving …":confirmed?nb?"Lagre og bekreft":"Save and confirm":nb?"Lagre som utkast":"Save as draft"}</Button>
    </SheetContent></Sheet>
  </div>;
}
function SummaryDraft({label,text,quote,source,language,sourceLanguage,additionalSources,locale,disabled,onSave}:{label:string;text:string;quote:string;source:string;language:Locale;sourceLanguage:Locale;additionalSources:{source:string;quote:string;language:Locale}[];locale:Locale;disabled:boolean;onSave:(text:string)=>void}) {
  const [editing,setEditing]=useState(false);const [draft,setDraft]=useState(text);useEffect(()=>setDraft(text),[text]);
  return <Card><CardContent className="pt-5"><h4>{label}</h4>{editing?<Textarea aria-label={label} lang={language} value={draft} maxLength={1000} rows={6} onChange={e=>setDraft(e.target.value)}/>:<p lang={language}>{text}</p>}<details><summary>{locale==="nb"?"Se kilde":"View source"}</summary><p className="hint">{source}</p><blockquote lang={sourceLanguage}>{quote}</blockquote>{additionalSources.map((evidence,index)=><div key={index}><p className="hint">{evidence.source}</p><blockquote lang={evidence.language}>{evidence.quote}</blockquote></div>)}</details><div className="claim-actions"><Button variant="ghost" size="sm" disabled={disabled} onClick={()=>{if(editing){setDraft(text);}setEditing(!editing);}}>{editing?locale==="nb"?"Avbryt":"Cancel":locale==="nb"?"Rediger sammendrag":"Edit summary"}</Button>{editing && <Button size="sm" disabled={disabled || !draft.trim()} onClick={()=>{onSave(draft);setEditing(false);}}>{locale==="nb"?"Lagre utkast":"Save draft"}</Button>}</div></CardContent></Card>;
}
function HistoryFields({content,locale,onChange}:{content:EntryContent;locale:Locale;onChange:(content:EntryContent)=>void}) {
  const nb=locale==="nb";const fields={title:nb?"Tittel / rolle":"Title / role",organization:nb?"Arbeidsgiver / organisasjon":"Employer / organization",client:nb?"Kunde (hvis oppgitt)":"Client (if stated)",deliveryRole:nb?"Faktisk leveranserolle":"Delivery role",description:nb?"Beskrivelse av erfaring":"Experience description"};
  return <div className="claim-form"><label htmlFor="history-kind">{nb?"Type historikk":"History type"}</label><select id="history-kind" value={content.kind} onChange={e=>onChange({...content,kind:e.target.value as EntryContent["kind"]})}>{Object.entries(entryKinds[locale]).map(([kind,label])=><option key={kind} value={kind}>{label}</option>)}</select>{Object.entries(fields).map(([key,label])=><div key={key}><label htmlFor={`history-${key}`}>{label}</label>{key==="description"?<Textarea id={`history-${key}`} rows={5} maxLength={2000} value={content.description} onChange={e=>onChange({...content,description:e.target.value})}/>:<Input id={`history-${key}`} maxLength={200} value={content[key as keyof typeof fields]} onChange={e=>onChange({...content,[key]:e.target.value})}/>}</div>)}<div className="grid grid-cols-2 gap-3">{(["startMonth","endMonth"] as const).map(key=><div key={key}><label htmlFor={`history-${key}`}>{key==="startMonth"?nb?"Startmåned (valgfri)":"Start month (optional)":nb?"Sluttmåned (valgfri)":"End month (optional)"}</label><Input id={`history-${key}`} type="month" value={content[key]??""} disabled={key==="endMonth" && content.ongoing} onChange={e=>onChange({...content,[key]:e.target.value||null})}/></div>)}</div><label className="consent-row"><input type="checkbox" checked={content.ongoing} onChange={e=>onChange({...content,ongoing:e.target.checked,endMonth:e.target.checked?null:content.endMonth})}/>{nb?"Pågår fortsatt":"Ongoing"}</label><p className="hint">{nb?"Årstall uten måned beholdes i beskrivelsen; vi finner ikke på datoer.":"Year-only dates remain in the description; we do not invent months."}</p></div>;
}
