"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useQuery,useMutation } from "@tanstack/react-query";
import { CircleCheck,ArrowRight,HelpCircle } from "lucide-react";
import { isSavedJob } from "../lib/saved-jobs";
import { isDocumentList,isDocumentDetail } from "../lib/documents";
import { isClaimList } from "../lib/claims";
import { isPersonalMatch,type PersonalMatch } from "../lib/personal-match";
import { isTailoringResult,type TailoringResult,tailoringPassages } from "../lib/cv-tailoring";
import { matchCoverage } from "../lib/match-planning";
import { useWorkspaceSession } from "../lib/workspace-session";
import { useAiChoice } from "../lib/use-ai-configuration";
import { aiRecipients } from "../lib/ai-configuration";
import { retryAfterSeconds,retryWaitLabel } from "../lib/retry-after";
import type { Locale } from "../lib/translations";
import { ReviewedCvText } from "./reviewed-cv-text";
import { CvVisibilityReview } from "./cv-visibility-review";
import { MatchApplicationFocus } from "./match-application-focus";
import { PersonalJobMatch } from "./personal-job-match";
import { AiChoice,AiActivity,AiIdentity } from "./ai-identity";
import { Button } from "./ui/button";
import { Card,CardContent,CardHeader } from "./ui/card";
import { Badge } from "./ui/badge";
import { Textarea } from "./ui/textarea";

async function read(path:string):Promise<unknown> {const r=await fetch(path,{cache:"no-store"});const v:unknown=await r.json();if(!r.ok)throw new Error(r.status===401?"AUTH_REQUIRED":"UNAVAILABLE");return v;}
export function JobApplicationPreparation({jobId,locale}:{jobId:string;locale:Locale}) {
 const nb=locale==="nb",session=useWorkspaceSession(),choice=useAiChoice("tailoring");
 const [selected,setSelected]=useState<string | undefined>(),[consent,setConsent]=useState(false),[tutorial,setTutorial]=useState(false),[showProcessed,setShowProcessed]=useState(false);
 const [waits,setWaits]=useState<Record<string,number>>({}),[seconds,setSeconds]=useState(0);
 const [saved,setSaved]=useState<{result:TailoringResult;text:string;fingerprint:string;claims:PersonalMatch["claims"];quotes:string[]}|null>(null);
 const [edits,setEdits]=useState<Record<number,string>>({}),[decisions,setDecisions]=useState<Record<number,"ACCEPTED"|"REJECTED">>({});
 const job=useQuery({queryKey:["private-job",jobId],gcTime:0,retry:false,queryFn:async()=>{const v=await read(`/api/profile/me/jobs/${jobId}`);if(!isSavedJob(v))throw new Error("UNAVAILABLE");return v;}});
 const documents=useQuery({queryKey:["private-documents"],gcTime:0,retry:false,queryFn:async()=>{const v=await read("/api/profile/me/documents");if(!isDocumentList(v))throw new Error("UNAVAILABLE");return v;}});
 const claims=useQuery({queryKey:["private-claims"],gcTime:0,retry:false,queryFn:async()=>{const v=await read("/api/profile/me/claims");if(!isClaimList(v))throw new Error("UNAVAILABLE");return v;}});
 const match=useQuery({queryKey:["private-job-match",jobId],gcTime:0,retry:false,queryFn:async()=>{const v=await read(`/api/profile/me/jobs/${jobId}/match`);if(v!==null && !isPersonalMatch(v))throw new Error("UNAVAILABLE");return v;}});
 const masterId=documents.data?.find(d=>d.isMaster)?.id ?? "";
 const requestedDocumentId=selected ?? masterId;
 const documentId=documents.data?.some(d=>d.id===requestedDocumentId)?requestedDocumentId:"";
 const base=useQuery({queryKey:["private-tailoring-source",documentId],gcTime:0,retry:false,enabled:!!documentId,queryFn:async()=>{const v=await read(`/api/profile/me/documents/${documentId}`);if(!isDocumentDetail(v))throw new Error("UNAVAILABLE");return v;}});
 const confirmed=claims.data?.filter(c=>c.status==="CONFIRMED") ?? [];
 const stale=!!match.data && (match.data.stale || !match.data.automaticEvidence || claims.data!==undefined && (confirmed.length!==match.data.claims.length || match.data.claims.some(c=>!confirmed.some(n=>n.id===c.id && n.revision===c.revision))));
 const fingerprint=JSON.stringify([jobId,documentId,base.data?.text,match.data?.id,confirmed.map(c=>[c.id,c.revision]),locale,choice.approval?.token]);
 useEffect(()=>setConsent(false),[fingerprint]);
 const waitUntil=waits[choice.approval?.token??""]??0;
 useEffect(()=>{const update=()=>setSeconds(Math.max(0,Math.ceil((waitUntil-Date.now())/1000)));update();if(waitUntil<=Date.now())return;const timer=setInterval(update,1000);return()=>clearInterval(timer);},[waitUntil]);
 const recipients=aiRecipients(choice.approval);
 const analyze=useMutation({retry:false,mutationFn:async(input:{text:string;documentId:string;matchId:string;aiApproval:string;fingerprint:string;claims:PersonalMatch["claims"];quotes:string[]})=>{
  const r=await fetch(`/api/profile/me/jobs/${jobId}/tailoring`,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-TOKEN":session.data?.csrfToken??""},body:JSON.stringify({text:input.text,documentId:input.documentId,matchId:input.matchId,aiApproval:input.aiApproval,locale,consent:true})});
  const v:unknown=await r.json();if(!r.ok){if(r.status===429)setWaits(previous=>({...previous,[input.aiApproval]:Date.now()+(retryAfterSeconds(r.headers.get("retry-after"))??60)*1000}));throw new Error(v && typeof v==="object" && "code" in v?String(v.code):"UNAVAILABLE");}
  const paragraphs=tailoringPassages(input.text);
  if(!isTailoringResult(v) || v.documentId!==input.documentId || v.matchId!==input.matchId || v.proposals.some(p=>p.oldText!==paragraphs[p.paragraphIndex] || p.claimIds.some(id=>!input.claims.some(c=>c.id===id)) || p.requirementIndexes.some(i=>i>=input.quotes.length)) || v.visibility && (v.visibility.length!==input.quotes.length || v.visibility.some(a=>a.requirementIndex>=input.quotes.length || a.claimIds.some(id=>!input.claims.some(c=>c.id===id)) || a.passages.some(p=>!paragraphs[p.paragraphIndex]?.includes(p.quote)))))throw new Error("AI_INVALID_RESULT");
  return v;
 },onSuccess:(result,input)=>{setSaved({result,text:input.text,fingerprint:input.fingerprint,claims:input.claims,quotes:input.quotes});setEdits({});setDecisions({});setConsent(false);setShowProcessed(false);}});
 const error=job.error??documents.error??claims.error??match.error??base.error;
 const current=!!saved && saved.fingerprint===fingerprint && !stale && !error;
 const pending=saved?.result.proposals.filter(p=>!decisions[p.paragraphIndex])??[];
 const visible=showProcessed?saved?.result.proposals.filter(p=>!!decisions[p.paragraphIndex])??[]:pending;
 const ready=!!job.data && !!match.data && !stale && !error && !!base.data?.text && base.data.text.trim().length>=40 && confirmed.length>0;
 const coverage=match.data && job.data?matchCoverage(match.data,job.data.content):null;
 if(job.isPending)return <AiActivity label={nb?"Henter stillingen …":"Loading your job …"}/>;
 if(!job.data)return <Card><CardContent><p>{nb?"Stillingen kunne ikke åpnes. Gå tilbake til dine lagrede stillinger.":"Could not open this job. Return to your saved jobs."}</p><Button asChild><Link href="/jobs/saved">{nb?"Mine stillinger":"Saved jobs"}</Link></Button></CardContent></Card>;
 return <section className="application-preparation">
  <Link href="/jobs/saved" className="underline">{nb?"← Tilbake til mine stillinger":"← Back to saved jobs"}</Link>
  <div className="workspace-heading"><div><p className="eyebrow">{nb?"SØKNADSFORBEREDELSE":"APPLICATION PREPARATION"}</p><h2>{job.data.content.title}</h2><p className="hint">{nb?"Bruk erfaringen din til å gjøre CV-en tydeligere for denne rollen. Du har kontroll over hver endring.":"Make your actual experience clearer for this role. You control every change."}</p></div><Button size="sm" variant="outline" onClick={()=>setTutorial(!tutorial)}><HelpCircle size={16}/>{nb?"Slik fungerer det":"How this works"}</Button></div>
  {tutorial && <Card><CardContent><ol className="preparation-guide"><li>{nb?"Start med CV og dokumenter som beskriver egne roller, perioder, ansvar, prosjekter og resultater.":"Start with a CV and documents describing your roles, dates, responsibilities, projects and outcomes."}</li><li>{nb?"Les og kontroller profilen. Vurder matchen, og svar på det som må avklares.":"Read and review your profile. Assess the match and answer unresolved questions."}</li><li>{nb?"Velg grunnlags-CV, se hva som sendes til AI, og gjennomgå forslagene ett av gangen.":"Select the base CV, inspect the AI preview and review individual suggestions."}</li></ol><Button variant="ghost" onClick={()=>setTutorial(false)}>{nb?"Lukk veiledningen":"Close guide"}</Button></CardContent></Card>}
  <div className="preparation-readiness" aria-label={nb?"Grunnlag for søknaden":"Application readiness"}><Card><CardContent><strong>1 · {nb?"Din erfaring":"Your experience"}</strong><p>{confirmed.length} {nb?"bekreftede kompetansebidrag":"confirmed competency contributions"}</p><Link href="/career/profile" className="underline">{nb?"Se dokumenter og profil":"View documents and profile"}</Link></CardContent></Card><Card><CardContent><strong>2 · {nb?"Stillingsmatch":"Job match"}</strong><p>{coverage?`${coverage.percent}% · ${stale?(nb?"oppdater vurderingen":"update assessment"):coverage.pending>0?(nb?"foreløpig kravmatch":"provisional coverage"):(nb?"dokumentert kravmatch":"documented coverage")}`:nb?"Vurder erfaringen mot kravene":"Assess experience against requirements"}</p><small>{nb?"Prosenten er kravdekning, ikke sannsynlighet for å få jobben.":"This is requirement coverage, not a probability of getting hired."}</small></CardContent></Card><Card><CardContent><strong>3 · {nb?"Grunnlags-CV":"Base CV"}</strong><p>{base.data?.document.originalName??(nb?"Velg eller last opp CV":"Choose or upload a CV")}</p><small>{nb?"Originalen beholdes. Ingen søknad sendes her.":"Your original is retained. This does not submit an application."}</small></CardContent></Card></div>
  {error && <p role="status" className="notice">{nb?"Noe av grunnlaget kunne ikke hentes. Du kan fortsatt se stillingen. Last siden på nytt før nye forslag.":"Some evidence could not be loaded. Your job remains visible. Reload before requesting suggestions."}</p>}
  {(!confirmed.length || !documents.data?.length) && <Card><CardContent><h3>{nb?"Start med dokumentene dine":"Start with your documents"}</h3><p>{nb?"Last opp CV og gjerne prosjektbeskrivelser, attester eller kursbevis. Ta med firma, rolle, periode, egne oppgaver og dokumenterte resultater. DOCX eller tekstbasert PDF gir normalt et bedre grunnlag enn skannede bilder. TXT og Markdown støttes også.":"Upload your CV and optional project descriptions, work certificates or course certificates. Include employer, role, dates, your contribution and documented results. DOCX or text-based PDF usually gives better source text than scanned images. TXT and Markdown are also supported."}</p><Button asChild><Link href="/career/profile">{nb?"Last opp og bygg profilen":"Upload and build your profile"}<ArrowRight size={16}/></Link></Button></CardContent></Card>}
  <details className="preparation-match" open={!match.data || stale}><summary>{nb?"Se matchen og avklar erfaring":"View the match and clarify experience"}</summary><PersonalJobMatch job={job.data} csrfToken={session.data?.csrfToken??""} locale={locale}/></details>
  {match.data && <MatchApplicationFocus result={match.data} job={job.data.content} locale={locale} stale={stale}/>}
  <Card><CardHeader><h3>{nb?"Tilspiss teksten i CV-en":"Tailor your CV wording"}</h3><p className="hint">{nb?"AI vurderer hva CV-en viser og foreslår inntil 12 tekstendringer med grunnlag og begrunnelse. Det er ikke en garanti for at alle forbedringer blir funnet.":"AI assesses CV visibility and suggests up to 12 evidence-linked text changes with reasons. It cannot guarantee that every improvement is found."}</p></CardHeader><CardContent>
   <label htmlFor="preparation-base">{nb?"Velg CV som utgangspunkt":"Choose your base CV"}</label><select id="preparation-base" value={documentId} disabled={analyze.isPending || documents.isPending || documents.isError} aria-describedby="preparation-base-guidance" onChange={e=>{setSelected(e.target.value);setConsent(false);}}><option value="">{nb?"Velg CV-dokument":"Choose a CV document"}</option>{documents.data?.map(d=><option value={d.id} key={d.id}>{d.originalName}{d.isMaster?nb?" · Master-CV":" · Master CV":""}</option>)}</select>
   <p id="preparation-base-guidance" className="hint">{documents.isPending?(nb?"Henter dokumentene dine …":"Loading your documents …"):documentId && selected===undefined?(nb?"Master-CV-en din er valgt automatisk. Du kan velge en annen CV i listen.":"Your master CV is selected automatically. You can choose another CV above."):nb?"Velg dokumentet som er CV-en din. Attester, kursbevis og prosjektbeskrivelser bidrar til kompetanseprofilen, men velges ikke automatisk som CV.":"Choose the document that is your CV. Certificates and project descriptions support your competency profile but are not automatically selected as your CV."}</p>
   {!documents.isPending && !documents.isError && !documentId && !!documents.data?.length && <p role="status" className="notice">{nb?"Velg en CV for å fortsette til tekstforslag. Vi gjetter ikke hvilket dokument som er CV-en din.":"Choose a CV to continue to wording suggestions. We do not guess which document is your CV."}</p>}
   {base.data && base.data.text.trim().length<40 && <div role="status" className="notice"><p>{nb?"Det ble hentet for lite tekst fra dette dokumentet til å foreslå CV-endringer. Prøv en annen CV, eller åpne dokumentet i profilen for å lese originalen på nytt. Skannede PDF-er kan trenge OCR.":"Too little text was extracted from this document to suggest CV changes. Choose another CV or open the document in your profile to reread the original. Scanned PDFs may need OCR."}</p><Link href="/career/profile" className="underline">{nb?"Åpne dokumentene mine":"Open my documents"}</Link></div>}
   {base.isFetching && documentId && <AiActivity label={nb?"Leser grunnlags-CV …":"Reading base CV …"}/>}
   {base.data && <details className="source-evidence"><summary>{nb?"Se CV-teksten som sendes":"Inspect CV text to be sent"}</summary><pre tabIndex={0}>{base.data.text}</pre></details>}
   <details className="source-evidence"><summary>{nb?"Hva brukes til forslagene?":"What supports these suggestions?"}</summary><p>{nb?`CV-teksten kan inneholde kontaktopplysninger. Hele teksten, den lagrede annonsen, aktuell match og alle bekreftede kompetansebidrag sendes til ${recipients}. Utkast og avviste kompetanser brukes ikke som faktagrunnlag.`:`The CV text may contain contact details. Full CV text, saved advertisement, current assessment and all confirmed competency contributions are sent to ${recipients}. Draft and rejected claims are not factual evidence.`}</p><pre tabIndex={0}>{job.data.content.text}</pre>{match.data?.claims.map(c=><p key={c.id}><strong>{c.skill}</strong> · {c.statement} · {c.context}</p>)}</details>
   <AiChoice configuration={choice.configuration} approval={choice.approval} options={choice.options} choose={token=>{choice.choose(token);setConsent(false);analyze.reset();}} disabled={analyze.isPending} locale={locale}/>
   {analyze.error?.message==="AI_APPROVAL_CHANGED" && <Button variant="outline" onClick={()=>{setConsent(false);void choice.configuration.refetch();analyze.reset();}}>{nb?"Hent AI-oppsett på nytt":"Refresh AI configuration"}</Button>}
   {!ready && <p className="hint">{nb?"For nye tekstforslag trenger vi en lesbar CV, bekreftet kompetanse og en oppdatert automatisk match. Avklaringer kan stå åpne, men de blir ikke til erfaring i CV-en.":"New suggestions require a readable CV, confirmed evidence and a current automatic match. Unresolved questions may remain, but cannot become CV experience."}</p>}
   <label className="ai-consent"><input type="checkbox" checked={consent} disabled={!ready || analyze.isPending || !choice.approval} onChange={e=>setConsent(e.target.checked)}/>{nb?`Jeg godkjenner at dette grunnlaget sendes til ${recipients} for CV-forslag`:`I approve sending this evidence to ${recipients} for CV suggestions`}</label>
   <Button disabled={!ready || !consent || !choice.approval || analyze.isPending || seconds>0 || analyze.error?.message==="AI_BUDGET_REACHED"} onClick={()=>{if(base.data && match.data && choice.approval)analyze.mutate({text:base.data.text,documentId,matchId:match.data.id,aiApproval:choice.approval.token,fingerprint,claims:match.data.claims,quotes:job.data!.content.requirements.map(r=>r.quote)});}}>{nb?"Foreslå tilspisset CV-tekst":"Suggest targeted CV wording"}</Button>
   {analyze.isPending && <AiActivity label={nb?"Sammenligner CV, erfaring og stillingskrav …":"Comparing CV, evidence and job criteria …"} detail={`${recipients} · ${nb?"Originalen beholdes":"Original retained"}`}/>}
   {seconds>0 && <AiActivity waiting label={nb?"Vent før nytt forsøk":"Wait before retrying"} detail={retryWaitLabel(seconds)}/>}
   {analyze.error && <p role="status" className="notice">{analyze.error.message==="AI_BUDGET_REACHED"?nb?"Denne AI-økten har nådd bruksgrensen for tekstforslag. Grunnlaget og tidligere forslag er beholdt.":"This AI session reached its text-suggestion usage limit. Evidence and earlier proposals are retained.":analyze.error.message==="CV_SOURCE_CONFLICT"?nb?"Grunnlaget er endret. Hent CV og match på nytt før du prøver igjen.":"Evidence changed. Refresh your CV and match before retrying.":nb?"AI-forslagene kunne ikke fullføres nå. Grunnlaget og tidligere forslag beholdes. Du kan prøve igjen eller velge en annen tilgjengelig modell med ny godkjenning.":"AI suggestions could not complete now. Evidence and earlier proposals are retained. Retry or select another available model with renewed approval."}</p>}
  </CardContent></Card>
  {saved && <CvVisibilityReview result={saved.result} claims={saved.claims} quotes={saved.quotes} locale={locale} current={current}/>}
  {saved && saved.result.proposals.length>0 && <ReviewedCvText source={saved.text} proposals={saved.result.proposals} decisions={decisions} edits={edits} locale={locale} current={current}/>}
  {saved && <Card><CardHeader><div className="workspace-heading"><h3>{nb?"Gjennomgå tekstforslag":"Review text suggestions"}</h3><Badge variant="outline">{pending.length} {nb?"venter på gjennomgang":"pending review"}</Badge></div><AiIdentity selections={[{provider:saved.result.provider,model:saved.result.model}]} locale={locale}/><p className="hint">{nb?"Forslag og valg finnes bare mens denne siden er åpen. Ingen ny CV-fil lagres. Kontroller fakta og behold bare tekst du kan stå inne for.":"Proposals and decisions last only while this page is open. No new CV file is saved. Review facts and keep only wording you can defend."}</p></CardHeader><CardContent>
   {!current && <p role="alert" className="notice">{nb?"Grunnlaget eller språk/modellvalget er endret. Disse forslagene kan leses, men må lages på nytt før godkjenning.":"Evidence or language/model choice changed. These proposals remain readable but need regeneration before approval."}</p>}
   {saved.result.omittedItems>0 && <p>{saved.result.omittedItems} {nb?"forslag uten gyldige referanser ble utelatt":"proposals with invalid references were omitted"}</p>}
   {!saved.result.proposals.length && <p>{nb?"Ingen gyldige tekstendringer ble foreslått. Det betyr ikke at CV-en er ferdig eller at alle krav er dekket.":"No valid changes were proposed. This does not mean the CV is complete or covers every requirement."}</p>}
   <div className="profile-actions"><Button variant={!showProcessed?"default":"outline"} onClick={()=>setShowProcessed(false)}>{nb?"Til gjennomgang":"Pending"} · {pending.length}</Button><Button variant={showProcessed?"default":"outline"} onClick={()=>setShowProcessed(true)}>{nb?"Behandlet":"Processed"} · {Object.keys(decisions).length}</Button></div>
   {visible.map(p=><article className="tailoring-proposal" key={p.paragraphIndex}><div className="workspace-heading"><h4>{nb?"Tekstavsnitt":"Text passage"} {p.paragraphIndex+1}</h4>{decisions[p.paragraphIndex] && <Badge>{decisions[p.paragraphIndex]==="ACCEPTED"?nb?"Godkjent tekst":"Approved wording":nb?"Avvist":"Rejected"}</Badge>}</div><p className="hint">{p.reason}</p><div className="tailoring-text-columns"><div><h5>{nb?"Nåværende tekst":"Current text"}</h5><p tabIndex={0}>{p.oldText}</p></div><div><label htmlFor={`tailoring-${p.paragraphIndex}`}>{nb?"Forslag – kan redigeres":"Suggestion – editable"}</label><Textarea id={`tailoring-${p.paragraphIndex}`} rows={5} maxLength={4000} value={edits[p.paragraphIndex]??p.newText} disabled={!current} onChange={e=>{setEdits({...edits,[p.paragraphIndex]:e.target.value});setDecisions(previous=>{const next={...previous};delete next[p.paragraphIndex];return next;});}}/></div></div><details><summary>{nb?"Se krav og kompetansegrunnlag":"Inspect requirements and evidence"}</summary>{p.requirementIndexes.map(i=><blockquote key={i}>{saved.quotes[i]}</blockquote>)}{p.claimIds.map(id=>{const c=saved.claims.find(c=>c.id===id);return <p key={id}><strong>{c?.skill}</strong> · {c?.statement} · {c?.context}</p>;})}</details><div className="profile-actions"><Button size="sm" disabled={!current || !(edits[p.paragraphIndex]??p.newText).trim()} onClick={()=>setDecisions({...decisions,[p.paragraphIndex]:"ACCEPTED"})}><CircleCheck size={16}/>{nb?"Godkjenn teksten":"Approve wording"}</Button><Button size="sm" variant="outline" disabled={!current} onClick={()=>setDecisions({...decisions,[p.paragraphIndex]:"REJECTED"})}>{nb?"Avvis forslaget":"Reject suggestion"}</Button></div></article>)}
  </CardContent></Card>}
 </section>;
}
