"use client";
import Link from "next/link";
import { ArrowRight, Check, FileCheck2, ScanSearch, ShieldCheck, Bookmark, Sparkles } from "lucide-react";
import { useLocale } from "../lib/use-locale";
import { SiteHeader } from "./site-header";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Card, CardContent } from "./ui/card";
export function LandingPage() {
  const { locale, changeLocale } = useLocale(); const nb = locale === "nb";
  const features = [
    { icon: ScanSearch, title: nb ? "Forstå stillingen" : "Understand the job", text: nb ? "Lim inn en lenke eller annonsetekst. Få oversikt over rollen, arbeidsgiveren og kravene, med kildegrunnlaget synlig." : "Paste a link or advertisement. Review the role, employer and requirements with visible source evidence." },
    { icon: FileCheck2, title: nb ? "Få frem din kompetanse" : "Bring your experience forward", text: nb ? "Samle CV, attester og prosjekter. AI foreslår kompetansepunkter; du kontrollerer og bekrefter hva som stemmer." : "Collect your CV, certificates and projects. AI proposes competencies; you review and confirm what is accurate." },
    { icon: Bookmark, title: nb ? "Behold mulighetene" : "Keep your opportunities", text: nb ? "Lagre interessante annonser og sammenlign kravene med kompetansen du har bekreftet. Ukjent erfaring blir et spørsmål." : "Save interesting jobs and compare their requirements with confirmed competencies. Unknown experience becomes a question." },
  ];
  return <div className="public-site"><a href="#landing-content" className="skip-link">{nb ? "Hopp til innhold" : "Skip to content"}</a><SiteHeader locale={locale} onChange={changeLocale}/>
    <main id="landing-content" className="landing-main"><section className="landing-hero"><div className="hero-copy"><Badge variant="outline"><span className="live-dot"/>{nb ? "Lokal pilot · Norsk og engelsk" : "Local pilot · Norwegian and English"}</Badge><h1>{nb ? <>Din erfaring.<br/>Din neste <span>mulighet.</span></> : <>Your experience.<br/>Your next <span>opportunity.</span></>}</h1><p className="hero-lead">{nb ? "Gjør jobbsøkingen mer oversiktlig. Forstå annonsene, samle kompetansen din og vurder muligheter med et grunnlag du kan stole på." : "Bring clarity to your job search. Understand advertisements, collect your competencies and evaluate opportunities with evidence you can inspect."}</p><div className="hero-actions"><Button asChild size="lg"><Link href="/login">{nb ? "Åpne ditt arbeidsområde" : "Open your workspace"}<ArrowRight size={18}/></Link></Button><Button asChild variant="outline" size="lg"><Link href="/jobs/analyze">{nb ? "Prøv stillingsanalyse" : "Try job analysis"}</Link></Button></div><p className="hero-reassurance"><ShieldCheck size={16}/>{nb ? "AI foreslår. Du bekrefter. Erfaring blir aldri automatisk sannhet." : "AI suggests. You confirm. Experience never automatically becomes a fact."}</p></div>
    <div className="hero-preview" aria-label={nb ? "Illustrasjon av arbeidsflyten" : "Workflow illustration"}><div className="preview-top"><span><Sparkles size={15}/>{nb ? "En tydelig vei videre" : "A clear way forward"}</span><Badge variant="secondary">{nb ? "Eksempel" : "Example"}</Badge></div><div className="preview-job"><span className="preview-company">{nb ? "DIN NESTE MULIGHET" : "YOUR NEXT OPPORTUNITY"}</span><h2>{nb ? "Fra annonse til handling" : "From advertisement to action"}</h2><p>{nb ? "Ett steg om gangen. Du beholder kontrollen." : "One step at a time. You stay in control."}</p></div><ol className="preview-steps">{[
      [nb ? "Forstå" : "Understand", nb ? "Se krav, frist og arbeidssted" : "Review requirements, deadline and location"],
      [nb ? "Sammenlign" : "Compare", nb ? "Knytt krav til bekreftet erfaring" : "Connect requirements to confirmed experience"],
      [nb ? "Avklar" : "Clarify", nb ? "Svar på det som ikke er dokumentert" : "Answer what has not been documented"],
    ].map(([title,text], index) => <li key={title}><span className="preview-step-icon">{index === 0 ? <Check size={17}/> : index + 1}</span><div><strong>{title}</strong><p>{text}</p></div></li>)}</ol><div className="preview-note"><ShieldCheck size={18}/><p>{nb ? "Ingen oppdiktet erfaring. Ingen skjult matchscore." : "No invented experience. No hidden match score."}</p></div></div></section>
    <section id="how-it-works" className="landing-features"><div className="section-heading"><p className="eyebrow">{nb ? "JOBBSØKING MED OVERSIKT" : "JOB SEARCH WITH CLARITY"}</p><h2>{nb ? "Et arbeidsområde som hjelper deg videre." : "A workspace that helps you move forward."}</h2><p>{nb ? "Verktøyene følger jobbsøkingen din. Fakta, forslag og neste handling er tydelig skilt." : "Tools follow your job search. Facts, suggestions and the next action stay clearly separated."}</p></div><div className="landing-feature-grid">{features.map(({ icon: Icon, title, text }, index) => <Card key={title}><CardContent><div className="feature-top"><Icon size={23}/><span>0{index + 1}</span></div><h3>{title}</h3><p>{text}</p></CardContent></Card>)}</div></section>
    <section className="landing-principle"><ShieldCheck size={34}/><div><h2>{nb ? "Din historie er din." : "Your story belongs to you."}</h2><p>{nb ? "Dokumenter lagres lokalt i piloten. Når du ber om AI-analyse, viser vi hva som sendes til Groq. Kompetanseforslag må bekreftes før de brukes som din erfaring." : "Documents are stored locally in the pilot. When you request AI analysis, we show what is sent to Groq. Competency proposals require confirmation before they become your experience."}</p></div><Button asChild variant="outline"><Link href="/login">{nb ? "Kom i gang" : "Get started"}<ArrowRight size={16}/></Link></Button></section></main>
    <footer className="site-footer"><span>Career Agent · {nb ? "Lokal pilot" : "Local pilot"}</span><span>{nb ? "Bekreftede fakta. Dine valg." : "Confirmed facts. Your choices."}</span></footer></div>;
}
