"use client";
import { useEffect, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { Sparkles, ShieldCheck } from "lucide-react";
import { isClaimList, type CompetencyClaim } from "../lib/claims";
import { isPersonalMatch, matchError, type PersonalMatch } from "../lib/personal-match";
import type { SavedJob } from "../lib/saved-jobs";
import type { Locale } from "../lib/translations";
import { WorkflowNotice } from "./workflow-notice";
import { Button } from "./ui/button";
import { Textarea } from "./ui/textarea";
import { Badge } from "./ui/badge";
import { Card, CardHeader, CardContent } from "./ui/card";
export function PersonalJobMatch({ job, csrfToken, locale }: { job: SavedJob; csrfToken: string; locale: Locale }) {
 const nb = locale === "nb"; const cache = useQueryClient();
 const [preview, setPreview] = useState(false); const [text, setText] = useState(job.content.text.slice(0,6000)); const [selected, setSelected] = useState<string[]>([]); const [consent,setConsent] = useState(false); const [retryUntil,setRetryUntil] = useState(0); const [seconds,setSeconds] = useState(0);
 const claims = useQuery({ queryKey:["private-claims"], gcTime:0, retry:false, queryFn:async () => { const r = await fetch("/api/profile/me/claims", { cache:"no-store" }); const v = await r.json(); if (!r.ok) throw new Error(v.code ?? "MATCH_UNAVAILABLE"); if (!isClaimList(v)) throw new Error("MATCH_UNAVAILABLE"); return v; } });
 const stored = useQuery({ queryKey:["private-job-match",job.id], gcTime:0, retry:false, queryFn:async () => { const r = await fetch(`/api/profile/me/jobs/${job.id}/match`, { cache:"no-store" }); const v = await r.json(); if (!r.ok) throw new Error(v.code ?? "MATCH_UNAVAILABLE"); if (v !== null && !isPersonalMatch(v)) throw new Error("MATCH_UNAVAILABLE"); return v as PersonalMatch | null; } });
 const confirmed = claims.data?.filter(c => c.status === "CONFIRMED") ?? []; const chosen = confirmed.filter(c => selected.includes(c.id));
 const characters = text.length + chosen.reduce((sum,c) => sum+c.skill.length+c.statement.length+c.context.length,0);
 function choose(c: CompetencyClaim) { setSelected(previous => previous.includes(c.id) ? previous.filter(id => id !== c.id) : [...previous,c.id]); setConsent(false); }
 const analyze = useMutation({ retry:false, mutationFn:async () => { const r = await fetch(`/api/profile/me/jobs/${job.id}/match`, { method:"POST", headers:{ "Content-Type":"application/json", "X-CSRF-TOKEN":csrfToken }, body:JSON.stringify({ text,claims:chosen.map(c => ({ id:c.id,revision:c.revision })),locale,consent }) }); const v = await r.json(); if (!r.ok) { if (r.status === 429 && v.code === "AI_RATE_LIMITED") setRetryUntil(Date.now()+Math.min(300,Math.max(1,Number(r.headers.get("retry-after")) || 60))*1000); throw new Error(v.code ?? "MATCH_UNAVAILABLE"); } if (!isPersonalMatch(v)) throw new Error("MATCH_UNAVAILABLE"); return v; }, onSuccess:result => { cache.setQueryData(["private-job-match",job.id],result); setConsent(false); setPreview(false); } });
 useEffect(() => { if (!retryUntil) return; const tick = () => setSeconds(Math.max(0,Math.ceil((retryUntil-Date.now())/1000))); tick(); const timer = setInterval(tick,1000); return () => clearInterval(timer); },[retryUntil]);
 const error = claims.error ?? stored.error ?? analyze.error; const expired = error?.message === "AUTH_REQUIRED";
 const result = stored.data;
 const stale = result?.stale || result?.claims.some(c => { const latest = claims.data?.find(x => x.id === c.id); return claims.data !== undefined && (!latest || latest.status !== "CONFIRMED" || latest.revision !== c.revision); });
 const labels = { STRONG:nb ? "Dokumentert relevant" : "Documented relevance", PARTIAL:nb ? "Delvis relevant" : "Partial relevance", CLARIFY:nb ? "Må avklares" : "Needs clarification" };
 return <Card className="personal-match-panel"><CardHeader><h3 className="flex items-center gap-2"><Sparkles size={19}/>{nb ? "Hvordan passer stillingen for deg?" : "How does this job fit you?"}</h3><p className="hint">{nb ? "En forklarbar vurdering mot dine bekreftede påstander. Ingen tilfeldig matchprosent." : "Explainable comparison against your confirmed statements. No arbitrary percentage score."}</p></CardHeader><CardContent>
 {error && error.message.startsWith("AI_") && <WorkflowNotice code={error.message} locale={locale} area="matching" retained previous={!!stored.data}/>}
 {error && !error.message.startsWith("AI_") && <p role="alert" className="notice">{matchError(error.message,locale)}{expired && <Link href="/login" className="underline"> {nb ? "Logg inn" : "Sign in"}</Link>}</p>}
 {!expired && <>{!job.content.requirements.length ? <p className="hint">{nb ? "Annonsen er lagret uten sorterte krav. Analyser teksten og lagre den nye versjonen før matching." : "This snapshot has no structured requirements. Analyze its text and save a new snapshot before matching."}</p> : <Button variant="outline" onClick={() => { setPreview(!preview); setConsent(false); analyze.reset(); }} disabled={analyze.isPending || claims.isPending}>{preview ? (nb ? "Lukk forhåndsvisning" : "Close preview") : (nb ? "Velg grunnlag for personlig matching" : "Choose evidence for personal matching")}</Button>}
 {preview && <div className="match-preview"><p className="notice"><ShieldCheck size={16} className="inline"/> {nb ? "Bare annonseteksten nedenfor og de valgte bekreftede påstandene sendes til Groq. Dokumenter, profilnavn og øvrige påstander sendes ikke." : "Only the advertisement text below and selected confirmed statements go to Groq. Documents, profile name and other statements are not sent."}</p><label htmlFor={`match-source-${job.id}`}>{nb ? "Annonsetekst som sendes" : "Advertisement text to send"}</label><Textarea id={`match-source-${job.id}`} rows={6} value={text} maxLength={12000} onChange={e => { setText(e.target.value); setConsent(false); }} disabled={analyze.isPending}/><p className="hint">{nb ? "Lang tekst starter med et utdrag. Fjern hele linjer med unødvendige opplysninger eller velg relevante passasjer fra lagret annonsetekst. Krav utenfor utvalget merkes som uavklart." : "Long text starts as an excerpt. Remove entire unnecessary lines or choose relevant passages from the saved text. Requirements outside the selection remain unknown."}</p><h4>{nb ? "Velg bekreftet kompetanse" : "Choose confirmed competencies"}</h4>{!confirmed.length && <p>{nb ? "Bekreft relevante kompetansepunkter i Min profil først." : "Confirm relevant competency statements in My profile first."} <Link href="/career/profile" className="underline">{nb ? "Åpne profilen" : "Open profile"}</Link></p>}<div className="match-claims">{confirmed.map(c => <label key={c.id} className="match-claim"><input type="checkbox" checked={selected.includes(c.id)} disabled={analyze.isPending} onChange={() => choose(c)}/><span><strong>{c.skill}</strong><span>{c.statement}</span><small>{c.context} · {nb ? "revisjon" : "revision"} {c.revision}</small></span></label>)}</div><p className="hint">{chosen.length} / 30 · {characters.toLocaleString(nb ? "nb-NO" : "en-US")} / 12 000 {nb ? "tegn" : "characters"}</p><label className="ai-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} disabled={analyze.isPending}/>{nb ? "Jeg godkjenner at dette grunnlaget sendes til Groq for denne matchingen" : "I approve sending this evidence to Groq for this matching analysis"}</label><Button disabled={!consent || !chosen.length || chosen.length > 30 || characters > 12000 || text.trim().length < 40 || analyze.isPending || seconds > 0} onClick={() => analyze.mutate()}>{analyze.isPending ? (nb ? "Sammenligner krav og erfaring …" : "Comparing requirements and experience …") : (nb ? "Analyser personlig match" : "Analyze personal match")}</Button></div>}
 {seconds > 0 && <p role="status">{nb ? "Vent før nytt forsøk" : "Wait before retrying"}: {seconds}s</p>}
 {stored.isPending && <p role="status">{nb ? "Henter lagret vurdering …" : "Loading stored assessment …"}</p>}
 {result && <div className="match-result">{stale && <p role="alert" className="notice">{nb ? "Vurderingen er utdatert fordi kompetansegrunnlaget er endret. Lag en ny vurdering før du bruker den videre." : "This assessment is stale because candidate evidence changed. Analyze again before using it."}</p>}<p className="hint">{nb ? "AI-vurdering, kontroller selv. Lagret" : "AI assessment, review it yourself. Saved"}: {new Date(result.createdAt).toLocaleString(nb ? "nb-NO" : "en-US")}</p><div className="competency-stats">{(["STRONG","PARTIAL","CLARIFY"] as const).map(kind => <div key={kind}><strong>{result.assessments.filter(a => a.classification === kind).length}</strong><span>{labels[kind]}</span></div>)}</div>{result.omittedItems > 0 && <p className="hint">{nb ? "Ugyldige elementer utelatt" : "Invalid items omitted"}: {result.omittedItems}</p>}<div className="match-assessments">{result.assessments.map(a => <details key={a.requirementIndex} className="match-assessment"><summary><Badge variant="outline">{labels[a.classification]}</Badge><strong>{job.content.requirements[a.requirementIndex]?.label ?? (nb ? "Krav" : "Requirement")}</strong></summary><p>{a.reason}</p><blockquote>{job.content.requirements[a.requirementIndex]?.quote}</blockquote>{a.evidence.map((e,i) => <div className="match-proof" key={i}><p><strong>{result.claims.find(c => c.id === e.claimId)?.skill}</strong> · {nb ? "Bekreftet kandidatgrunnlag" : "Confirmed candidate evidence"}</p><blockquote>{e.quote}</blockquote></div>)}{a.question && <p className="notice">{a.question}</p>}</details>)}</div></div>}</>}
 </CardContent></Card>;
}
