"use client";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { Bookmark, ArrowUpRight, Search, Trash2 } from "lucide-react";
import { isSession } from "../lib/profile";
import { isSavedJobs, savedError, type SavedJob } from "../lib/saved-jobs";
import type { Locale } from "../lib/translations";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Badge } from "./ui/badge";
import { Card, CardContent, CardHeader } from "./ui/card";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "./ui/sheet";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "./ui/dialog";
import { PersonalJobMatch } from "./personal-job-match";
import { JobOverview } from "./job-overview";
import { RequirementResults } from "./requirement-results";
export function SavedJobsWorkspace({ locale }: { locale: Locale }) {
 const nb = locale === "nb"; const cache = useQueryClient(); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<SavedJob | null>(null); const [deleting, setDeleting] = useState<SavedJob | null>(null);
 const session = useQuery({ queryKey: ["private-session"], gcTime: 0, retry: false, queryFn: async () => { const r = await fetch("/api/auth/session", { cache: "no-store" }); const v = await r.json(); if (!r.ok || !isSession(v)) throw new Error("AUTH_REQUIRED"); return v; } });
 const jobs = useQuery({ queryKey: ["private-saved-jobs"], gcTime: 0, retry: false, enabled: session.data?.authenticated === true && session.data.profilesAvailable, queryFn: async () => { const r = await fetch("/api/profile/me/jobs", { cache: "no-store" }); const v = await r.json(); if (!r.ok) throw new Error(v.code ?? "SAVED_JOB_UNAVAILABLE"); if (!isSavedJobs(v)) throw new Error("SAVED_JOB_UNAVAILABLE"); return v; } });
 const remove = useMutation({ retry: false, mutationFn: async (job: SavedJob) => { const r = await fetch(`/api/profile/me/jobs/${job.id}`, { method: "DELETE", headers: { "X-CSRF-TOKEN": session.data?.csrfToken ?? "" } }); if (r.status !== 204) { const v = await r.json(); throw new Error(v.code ?? "SAVED_JOB_UNAVAILABLE"); } }, onSuccess: () => { setSelected(null); setDeleting(null); void cache.invalidateQueries({ queryKey: ["private-saved-jobs"] }); } });
 const error = session.error ?? jobs.error ?? remove.error; const expired = error?.message === "AUTH_REQUIRED"; const allowed = !!session.data?.authenticated && !expired;
 const filtered = jobs.data?.filter(job => [job.content.title, ...job.content.facts.map(f => f.value)].join(" ").toLocaleLowerCase().includes(search.toLocaleLowerCase())) ?? [];
 return <section className="saved-job-workspace" aria-labelledby="saved-jobs-title"><div className="workspace-heading"><div><h2 id="saved-jobs-title">{nb ? "Mine stillinger" : "My saved jobs"}</h2><p>{nb ? "Mulighetene du vil følge videre, med annonsegrunnlaget bevart." : "Opportunities to follow, with the received advertisement preserved."}</p></div><Button asChild variant="outline"><Link href="/jobs/analyze">{nb ? "Analyser en ny stilling" : "Analyze another job"}</Link></Button></div>
 {session.isPending && <p role="status">{nb ? "Henter innlogging …" : "Checking sign-in …"}</p>}
 {error && <p role="alert" className="notice">{savedError(error.message, locale)}{!expired && <Button variant="ghost" onClick={() => void jobs.refetch()}>{nb ? "Prøv igjen" : "Try again"}</Button>}</p>}
 {session.data && !allowed && <Card><CardContent className="p-6"><h3>{nb ? "Stillingsbiblioteket er ditt" : "Your personal job library"}</h3><p>{nb ? "Logg inn og lagre profilen for å beholde annonser mellom besøk." : "Sign in and save your profile to keep jobs between visits."}</p><Button asChild><Link href="/career/profile">{nb ? "Gå til min profil" : "Go to my profile"}</Link></Button></CardContent></Card>}
 {allowed && <><label className="sr-only" htmlFor="saved-job-search">{nb ? "Søk i lagrede stillinger" : "Search saved jobs"}</label><div className="claim-search"><Search size={17}/><Input id="saved-job-search" placeholder={nb ? "Søk etter rolle, bedrift eller sted …" : "Search role, employer or location …"} value={search} onChange={e => setSearch(e.target.value)}/></div>{jobs.isPending && <p role="status">{nb ? "Henter stillinger …" : "Loading jobs …"}</p>}
 {jobs.data && <div className="saved-job-summary"><strong>{filtered.length}</strong><span>{nb ? "av" : "of"} {jobs.data.length} {nb ? "lagrede stillinger" : "saved jobs"}</span><span className="saved-job-summary-caption">{nb ? "Annonsetekst og analyse er bevart i hver versjon." : "Advertisement text and analysis are preserved in each snapshot."}</span></div>}
 {jobs.data?.length === 0 && <Card className="empty-state"><CardContent><Bookmark size={30}/><h3>{nb ? "Behold din neste mulighet" : "Keep your next opportunity"}</h3><p>{nb ? "Analyser en annonse og velg Lagre stillingen. Både tekst og analyse beholdes." : "Analyze an advertisement and choose Save job. Its text and analysis are retained."}</p></CardContent></Card>}
 {jobs.data && jobs.data.length > 0 && !filtered.length && <p>{nb ? "Ingen stillinger passer søket." : "No jobs match your search."}</p>}
 <div className="saved-job-grid">{filtered.map(job => <Card key={job.id} className="saved-job-card"><CardHeader><Badge variant="outline">{job.content.sourceType === "GROQ_BROWSER_EXCERPT" ? (nb ? "Nettleserutdrag" : "Browser excerpt") : (nb ? "Lagret annonse" : "Saved advertisement")}</Badge><h3>{job.content.title}</h3>{job.content.facts.find(f => f.kind === "COMPANY")?.value&&<p className="saved-job-company">{job.content.facts.find(f => f.kind === "COMPANY")?.value.slice(0, 160)}</p>}</CardHeader><CardContent><div className="saved-job-facts">{job.content.facts.filter(f => ["LOCATION", "DEADLINE"].includes(f.kind)).slice(0, 2).map((f,i) => <p key={i}><strong>{f.label}</strong><span>{f.value}</span></p>)}</div><p className="saved-job-meta">{nb ? "Lagret" : "Saved"} <time dateTime={job.createdAt}>{new Date(job.createdAt).toLocaleDateString(nb ? "nb-NO" : "en-US")}</time><span>{job.content.requirements.length} {nb ? "sorterte krav" : "structured requirements"}</span></p><Button className="saved-job-open-button" variant="outline" onClick={() => setSelected(job)}>{nb ? "Åpne stilling" : "Open job"}<ArrowUpRight size={14}/></Button></CardContent></Card>)}</div>
 <Sheet open={selected !== null} onOpenChange={open => { if (!open) setSelected(null); }}><SheetContent className="document-workspace-sheet saved-job-sheet" closeLabel={nb ? "Lukk" : "Close"}>{selected && <><SheetHeader className="document-review-header"><SheetTitle>{selected.content.title}</SheetTitle><SheetDescription>{nb ? "Bevart annonseversjon. Kilden kan ha blitt endret siden lagringen." : "Preserved advertisement snapshot. Its source may have changed since saving."}</SheetDescription></SheetHeader>{selected.content.sourceUrl && <a className="underline" href={selected.content.sourceUrl} target="_blank" rel="noopener noreferrer">{nb ? "Åpne originalannonsen" : "Open original advertisement"}</a>}{selected.content.sourceType === "GROQ_BROWSER_EXCERPT" && <p className="notice">{nb ? "Dette er et kildeutdrag, som kan være ufullstendig eller utdatert." : "This is a source excerpt, which may be incomplete or outdated."}</p>}<div className="document-toolbar"><Button asChild variant="outline"><Link href="/cv">{nb ? "Lag en CV-versjon" : "Create a CV version"}</Link></Button><Button asChild variant="outline"><Link href="/applications">{nb ? "Følg opp søknaden" : "Track the application"}</Link></Button></div><PersonalJobMatch key={selected.id} job={selected} csrfToken={session.data?.csrfToken ?? ""} locale={locale}/><JobOverview sourceText={selected.content.text} facts={selected.content.facts} locale={locale} sourceLocale={selected.content.locale} fallbackText={!selected.content.requirements.length && !selected.content.facts.length ? selected.content.text : undefined}/><RequirementResults requirements={selected.content.requirements} source={selected.content.text} locale={locale} resultLocale={selected.content.locale} browserExcerpt={selected.content.sourceType === "GROQ_BROWSER_EXCERPT"} outdated={false}/><details className="source-evidence"><summary>{nb ? "Lagret annonsetekst" : "Saved advertisement text"}</summary><pre>{selected.content.text}</pre></details><Button variant="outline" onClick={() => { remove.reset(); setDeleting(selected); }}><Trash2 size={14}/>{nb ? "Slett lagret stilling" : "Delete saved job"}</Button></>}</SheetContent></Sheet>
 <Dialog open={deleting !== null} onOpenChange={open => { if (!open && !remove.isPending) setDeleting(null); }}><DialogContent closeLabel={nb ? "Lukk" : "Close"}><DialogHeader><DialogTitle>{nb ? "Slette denne stillingsversjonen?" : "Delete this job snapshot?"}</DialogTitle><DialogDescription>{nb ? "Denne lagrede annonseteksten og analysen slettes permanent. Originalannonsen hos arbeidsgiveren påvirkes ikke." : "Permanently delete this saved text and analysis. The employer's advertisement is unaffected."}</DialogDescription></DialogHeader>{remove.error && <p role="alert">{savedError(remove.error.message, locale)}</p>}<Button disabled={remove.isPending} onClick={() => { if (deleting) remove.mutate(deleting); }}>{nb ? "Ja, slett stillingen" : "Yes, delete job"}</Button></DialogContent></Dialog></>}
 </section>;
}
