"use client";
import { useState } from "react";
import Link from "next/link";
import { BookOpen, Upload, ShieldCheck, ScanSearch, ChartNoAxesCombined, FilePenLine, ArrowRight, ChevronLeft, ChevronRight } from "lucide-react";
import type { Locale } from "../lib/translations";
import { Card, CardContent } from "./ui/card";
import { Button } from "./ui/button";
import { HelpTip } from "./ui/help-tip";

/** Optional local guidance; opening or advancing never starts an AI request. */
export function WorkspaceJourneyGuide({locale}:{locale:Locale}) {
 const nb=locale==="nb",[open,setOpen]=useState(false),[step,setStep]=useState(0);
 const steps=[
  {icon:Upload,title:nb?"Samle dokumentene":"Gather your documents",text:nb?"Last opp en CV og gjerne prosjektbeskrivelser, attester og kursbevis. Ta med firma, rolle, periode, egne oppgaver og resultater. DOCX eller tekstbasert PDF gir vanligvis best lesbarhet; TXT og Markdown støttes også.":"Upload a CV and optional project descriptions, work and course certificates. Include employer, role, period, your contributions and results. DOCX or text-based PDF usually reads best; TXT and Markdown are also supported.",href:"/career/profile#profile-documents",action:nb?"Åpne dokumentene":"Open documents"},
  {icon:ShieldCheck,title:nb?"Kontroller profilen":"Review your profile",text:nb?"AI finner kompetanse, historikk og et profilsammendrag fra dokumentene. Dokumenterte opplysninger kan lagres med kilde; kontroller og rett innholdet. Utkast og avviste punkter brukes ikke som bekreftet erfaring.":"AI finds competencies, career history and a profile summary from your documents. Documentary facts can be saved with their sources; check and correct the content. Drafts and rejected items are not used as confirmed experience.",href:"/career/profile#profile-competencies",action:nb?"Se kompetansen":"View competencies"},
  {icon:ScanSearch,title:nb?"Finn og lagre en stilling":"Find and save a job",text:nb?"Bruk en annonse-lenke eller lim inn teksten. Se hva arbeidsgiveren søker, kontroller kilden og lagre stillingen. Hvis AI ikke kan fullføre, beholdes annonseteksten vi har hentet.":"Use an advertisement link or paste its text. Review the criteria and source, then save the job. If AI cannot complete, the received advertisement text is retained.",href:"/jobs/analyze",action:nb?"Analyser en annonse":"Analyze a job"},
  {icon:ChartNoAxesCombined,title:nb?"Gjennomfør personlig match":"Run a personal match",text:nb?"Åpne stillingen og godkjenn vist AI-leverandør og modell. Systemet bruker bekreftet kompetanse automatisk. Prosenten viser dokumentert kravdekning, ikke sjansen for å få jobben. Avklar spørsmål i matchen og vurder på nytt etter rettelser.":"Open the job and approve the displayed AI provider and model. Confirmed competencies are included automatically. The percentage describes documented criterion coverage, not hiring probability. Clarify questions in the match and reassess after corrections.",href:"/jobs/saved",action:nb?"Åpne lagrede stillinger":"Open saved jobs"},
  {icon:FilePenLine,title:nb?"Tilspiss CV-teksten":"Tailor your CV wording",text:nb?"Velg «Søk på stillingen», velg grunnlags-CV og godkjenn analysen. Se tekstforslag med begrunnelse og kilder; rediger, godkjenn eller avvis. Originalen beholdes. Valgene varer mens siden er åpen; ingen søknad sendes eller ny CV-fil lagres her.":"Choose Apply for this job, select the base CV and approve the analysis. Review wording proposals with reasons and sources; edit, approve or reject. Your original is retained. Choices last while the page is open; no application is submitted or new CV file saved here.",href:"/jobs/saved",action:nb?"Velg stillingen du vil søke":"Choose a job to prepare"},
 ];
 const selected=steps[step],Icon=selected.icon;
 return <Card className="workspace-journey"><CardContent><div className="workspace-heading"><div><h2>{nb?"Fra CV til neste mulighet":"From your CV to your next opportunity"}</h2><p className="hint">{nb?"En kort guide du kan åpne når du trenger den.":"A short guide to open whenever you need it."}</p></div><Button size="sm" variant="outline" aria-expanded={open} aria-controls="workspace-journey-guide" onClick={()=>setOpen(!open)}><BookOpen size={16}/>{open?nb?"Skjul guiden":"Hide guide":nb?"Vis guiden":"Show guide"}</Button></div>
 {open && <div id="workspace-journey-guide" className="workspace-journey-body"><ol aria-label={nb?"Steg i guiden":"Guide steps"}>{steps.map((item,index)=><li key={index}><Button variant={step===index?"default":"ghost"} aria-current={step===index?"step":undefined} onClick={()=>setStep(index)}><span>{index+1}</span>{item.title}</Button></li>)}</ol><div className="workspace-journey-detail" aria-live="polite"><p className="eyebrow">{nb?"GUIDE":"GUIDE"} · {step+1} / {steps.length}</p><h3><Icon size={20}/>{selected.title}</h3><p>{selected.text}</p><HelpTip label={nb?"Om guiden og fremdrift":"About the guide and progress"}>{nb?"Stegene er veiledning, ikke en ferdigstatus. Du kan hoppe mellom dem. Å lese guiden starter ingen AI-kall og endrer ingen profilopplysninger.":"Steps are guidance, not completion status. Skip between them freely. Reading the guide starts no AI calls and changes no profile information."}</HelpTip><Button asChild size="sm"><Link href={selected.href}>{selected.action}<ArrowRight size={15}/></Link></Button><div className="workspace-journey-controls"><Button size="sm" variant="outline" disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft size={15}/>{nb?"Forrige":"Previous"}</Button><Button size="sm" variant="outline" disabled={step===steps.length-1} onClick={()=>setStep(step+1)}>{nb?"Neste":"Next"}<ChevronRight size={15}/></Button></div></div></div>}
 </CardContent></Card>;
}
